[WIP] fixing hidden creature health
opentibiabr/otservbr-global-archived pull request #1053
Opened 2020-04-18 22:28 UTC by jlcvp

fixes #962

2020-04-18 22:28 UTC, jlcvp commented
@gpedro pode testar esse commit?

2020-04-19 04:56 UTC, gpedro requested changes
funcionou, mas precisa ver o lance dos emblemas para não dar problemas.

2020-04-19 04:56 UTC, gpedro commented on src/enums.h
> +    CREATURETYPE_MONSTER_HIDDEN = 5,
troca espaço por tab, só pra manter o codestyle neste arquivo

2020-04-19 04:56 UTC, gpedro commented on src/luascript.cpp
> +    registerEnum(CREATURETYPE_MONSTER_HIDDEN)
troca espaço por tab, só pra manter o codestyle neste arquivo

2020-04-19 04:56 UTC, gpedro commented on src/protocolgame.cpp
> +    if (player->getProtocolVersion() >= 1120 && creatureType == CREATURETYPE_MONSTER && creature->isHealthHidden()) {
isso vai cagar os emblemas lá em baixo, porque ele não vai reconhecer como MONSTER e não vai adicionar os emblemas de summons.

talvez uma flag pra lançar ou algo do tipo...

2020-04-19 13:55 UTC, jlcvp commented on src/protocolgame.cpp
> +    if (player->getProtocolVersion() >= 1120 && creatureType == CREATURETYPE_MONSTER && creature->isHealthHidden()) {
Monstros hidden health não são summonáveis

2020-04-19 14:04 UTC, jlcvp commented on src/luascript.cpp
> +    registerEnum(CREATURETYPE_MONSTER_HIDDEN)
done

2020-04-19 14:06 UTC, jlcvp commented on src/protocolgame.cpp
> +    if (player->getProtocolVersion() >= 1120 && creatureType == CREATURETYPE_MONSTER && creature->isHealthHidden()) {
refiz a lógica pra não alterar o type (apesar do if do summon alterar), de qualquer forma se um monstro hidden for sumonável algum dia, ele não vai ter badge né? senão deixa de ser hidden

2020-04-19 14:22 UTC, jlcvp commented
corrigi os pontos, no client 12.30 ficou aparecendo o nome da criatura, coloquei uma verificação pra enviar string vazia

2020-04-19 17:42 UTC, gpedro requested changes

2020-04-19 17:42 UTC, gpedro commented on src/protocolgame.cpp
> +			msg.addByte(CREATURETYPE_MONSTER_HIDDEN);
tabs pls, vou testar e já te falo se deu certo

2020-04-20 16:12 UTC, guiismiti commented
Still not working:
1 - setting hidden health with setHiddenHealth:
Players can still see the name and health bar of a god using /hide:
![god_hide_health](https://user-images.githubusercontent.com/7709510/79770565-f82c1300-8303-11ea-8c98-7cc3a7d7f87e.png)

2 - when killing a monster, the health bar and name are not disappearing immediately:
![ezgif com-optimize (1)](https://user-images.githubusercontent.com/7709510/79773316-b309e000-8307-11ea-8666-0272c9adca8c.gif)

Behavior in client 10 (correct behavior #1) - the name and healthbar disappear immediately, before the corpse hits the ground:
![ezgif com-optimize (2)](https://user-images.githubusercontent.com/7709510/79773391-ccab2780-8307-11ea-9372-d2165b5496c4.gif)

Behavior in real Tibia (correct behavior #2) - the corpse hits the ground immediately:
![ezgif com-optimize (3)](https://user-images.githubusercontent.com/7709510/79773864-5c50d600-8308-11ea-9180-44a1b27922a1.gif)

2020-04-20 17:45 UTC, guiismiti commented
maybe something in sendCreatureHealth in protocolgame.cpp?

2020-04-21 12:11 UTC, jlcvp commented
Hi guys, done some more changes to address the hidden gamemaster / god / accessplayer problem. 

@guiismiti I've done an adjust regarding not sending health of hidden health creatures at all, but I think a more definitive solution would be to rewrite the creature dying logic.

The client 10 automatically hides the healthbar if a value of 0 is sent. clients 11/12 don't. 

On the TFS when we kill a creature, first we send health 0 and in the next tick we send the remove creature/body logic. this needs to be changed.

Since it's unrelated to #962 I would recommend opening a different issue regarding this behavior.

2020-04-21 14:03 UTC, gpedro commented
@jlcvp https://otland.net/threads/sendcreaturehealth-issue-with-clients-11.270003/

2020-04-23 14:29 UTC, jlcvp commented
@gpedro I've sent a more in-depth response in the otland topic. But I'll stick with my opinion that the empty creature health on death is not related with this particular issue. #962 is a complain about the healthbar and name showing for creatures with hiddenHealth flag/status. I recommend we create another issue to investigate the possibilities of redoing the monster death routine

2020-04-24 03:02 UTC, gpedro commented
![image](https://user-images.githubusercontent.com/2898638/80170665-731c5480-85b6-11ea-88f4-8fa36693d967.png)

2020-04-24 03:02 UTC, merged

2020-04-25 17:29 UTC, Zbizu commented
does the monster wait 1s for onThink to drop the corpse?
https://github.com/opentibiabr/otservbr-global/blob/develop/src/creature.h#L72