monster updates, fix summonable monster
opentibiabr/otservbr-global-archived pull request #1079
Opened 2020-04-26 14:45 UTC by FearLucien

Skeleton elite warrior shouldn't be summonable by player. Updated other monsters per tibia fandom.

2020-04-26 15:05 UTC, dudantas requested changes

2020-04-26 15:05 UTC, dudantas commented on data/monster/skeletons/dreadbeast.xml
> +		<item id="5925" chance="650"/>					<!-- hardened bone -->
Please, set for:
```
		<item name="gold coin" countmax="88" chance="11690"/>
		<item id="2230" chance="8230"/><!-- bone -->
		<item name="plate armor" chance="2810"/>
		<item id="2229" chance="2810"/><!-- skull -->
		<item id="2231" chance="1950"/><!-- big bone -->
		<item name="bone club" chance="1520"/>
		<item name="bone shield" chance="1520"/>
		<item name="health potion" chance="870"/>
		<item name="green mushroom" chance="650"/>
		<item name="hardened bone" chance="650"/>```

2020-04-26 15:05 UTC, dudantas commented on data/monster/skeletons/dreadbeast.xml
> +		<attack script="monster/dreadbeast skill reducer.lua" interval="3000" chance="15" target="1" range="1">
You can use: ```<attack name="dreadbeast skill reducer" interval="3000" chance="15" target="1" range="1">```

2020-04-27 03:06 UTC, FearLucien commented
fixed requested changes :D

2020-04-27 05:03 UTC, dudantas approved these changes

2020-04-27 12:23 UTC, dudantas commented on data/monster/skeletons/dreadbeast.xml
> +		<item name="bone club" chance="1520"/>
@FearLucien The bone club item is duplicated in the items.xml, so giving error in the distro. It could change for me?
From: `<item id =" 28658 "article =" a "name =" bone club ">`
To: `<item id =" 28658 "article =" a "name =" glowing rubbish amulet ">`

So we took advantage of your PR for this.

2020-04-27 14:07 UTC, FearLucien commented on data/monster/skeletons/dreadbeast.xml
> +		<item name="bone club" chance="1520"/>
item id="2449" article="a" name="bone club"
item id="28658" article="a" name="glowing rubbish amulet"
That is what is currently in the distro items.xml file, I would change in items.xml for you but not seeing the duplicated item.

2020-04-27 14:22 UTC, dudantas commented on data/monster/skeletons/dreadbeast.xml
> +		<item name="bone club" chance="1520"/>
Sorry, it was my mistake.

2020-04-27 14:22 UTC, dudantas commented on data/monster/skeletons/dreadbeast.xml
> +		<item name="bone club" chance="1520"/>
Thanks.

2020-04-27 14:24 UTC, merged

2020-04-27 14:25 UTC, dudantas commented
Thanks for the contribution.