refactoring/fixing reward_common.lua's logic
opentibiabr/otservbr-global-archived pull request #1097
Opened 2020-04-29 20:16 UTC by alisonjf

- Stackable items with count > 1 now shows following message: _"You have found X PLURALNAME"._
- Checking if players has backpack to receive the reward
- Checking if player's backpacks have empty room to receive the item
- Message is now well formatted
- Item name was not beeing displayed before, the function **"getItemName"** was being called with wrong variable as parameter
- Method extraction and reuse
- **ItemType(itemid):getCharges()** was never false, because when item doesn't have charges, it returns 0, not false.
- Single items message now displays correct article, example: _an orange_ or _a dwarven shield_

2020-04-29 20:34 UTC, andersonfaaria commented
@alisonjf this code definetely works but you could achieve half of those changes by changing player:addItem to player:addItemEx and checking the return code

2020-04-29 20:48 UTC, alisonjf commented
> @alisonjf this code definetely works but you could achieve half of those changes by changing player:addItem to player:addItemEx and checking the return code

I know bro, I did some tests and when no room it returns 2 and no cap it returns 21, but I did it with addItem cuz I don't particularly like the way the function addItemEx works, but it sure would be cleaner, but in my opinion, not more readable

2020-04-29 21:21 UTC, gpedro requested changes

2020-04-29 21:21 UTC, gpedro commented on data/scripts/actions/quests/system/reward_common.lua
> +					if not (checkWeightAndBackpackRoom(player, getItemWeight(itemid), message)) then
unnecessary parenthesis

2020-04-29 21:21 UTC, gpedro commented on data/scripts/actions/quests/system/reward_common.lua
> +					if not (checkWeightAndBackpackRoom(player, getItemWeight(itemid)*count, message)) then
unnecessary parenthesis

2020-04-29 21:21 UTC, gpedro commented on data/scripts/actions/quests/system/reward_common.lua
> +					if not (checkWeightAndBackpackRoom(player, getItemWeight(itemid), message)) then
here we have a duplicated/similiar piece of code, we can merge it?

2020-04-29 21:21 UTC, gpedro commented on data/scripts/actions/quests/system/reward_common.lua
> +	elseif (player:getFreeCapacity() / 100) < (itemWeight) then
unnecessary parenthesis at itemWeight

2020-04-29 21:21 UTC, gpedro commented on data/scripts/actions/quests/system/reward_common.lua
> +	elseif (player:getFreeCapacity() / 100) < (itemWeight) then
unnecessary "elseif" above, cuz if this condition is valid, he will return and will not reach here

2020-04-30 00:54 UTC, alisonjf commented on data/scripts/actions/quests/system/reward_common.lua
> +	elseif (player:getFreeCapacity() / 100) < (itemWeight) then
> unnecessary "elseif" above, cuz if this condition is valid, he will return and will not reach here

Its a matter of style, the generated byte code is the same, anyway I'll change it

2020-05-01 13:25 UTC, ikaro1997 approved these changes

2020-05-02 00:18 UTC, dudantas commented on data/scripts/actions/quests/system/reward_common.lua
> +local function checkWeightAndBackpackRoom(player, itemWeight, message)
It looks great.
But, maybe we can move this function to 051-functions? So it can be called in other scripts. Who and says?

2020-05-02 22:26 UTC, dudantas approved these changes

2020-05-02 22:34 UTC, merged

2020-05-02 22:39 UTC, dudantas commented
Good work, thanks for you contribution.

2020-05-04 14:54 UTC, dudantas commented
Hello, sorry for the delay in replying. The issue was closed for being unconfirmed. I did the tests and couldn't reproduce.
Make sure that:
You are using the updated datapack, source and database.
Just in case, download everything from 0 and test again.

If you are still able to reproduce the problem. Explain exactly how to reproduce, step by step, what was done. Thus, we can investigate, the information you gave is vague and so you can't do much.