fix: #1054
opentibiabr/otservbr-global-archived pull request #1102
Opened 2020-04-30 00:14 UTC by gpedro

based on otland/forgottenserver#2953 by nekiro

2020-05-02 23:12 UTC, jlcvp approved these changes
LGTM

2020-06-20 15:58 UTC, oalbsilva requested changes

2020-06-20 15:58 UTC, lekzinn commented on src/player.cpp
> +	ret = g_moveEvents->onPlayerEquip(const_cast<Player*>(this), const_cast<Item*>(item), static_cast<slots_t>(index), true);
Was a error in this line:
ret is enum ReturnValue, and onPlayerEquip returns a int.

i Change to: 
`ret = ReturnValue(g_moveEvents->onPlayerEquip(const_cast<Player*>(this), const_cast<Item*>(item), static_cast<slots_t>(index), true));`

2020-06-20 16:00 UTC, lekzinn commented
It is working correctly!

2020-06-21 18:29 UTC, lekzinn commented on src/player.cpp
> +	ret = g_moveEvents->onPlayerEquip(const_cast<Player*>(this), const_cast<Item*>(item), static_cast<slots_t>(index), true);
The suggested change caused a problem, where players are no longer able to equip items.
Só i back to original code: 

```cpp
if (!g_moveEvents->onPlayerEquip(const_cast<Player*>(this), const_cast<Item*>(item), static_cast<slots_t>(index), true)) {
		return RETURNVALUE_CANNOTBEDRESSED;
}
```

Now its working!

2020-06-22 07:19 UTC, FakeShinoda approved these changes
LGTM

2020-06-22 14:32 UTC, nekiro commented
Hey, there was already another fix for that pr, because it introduced another bug.
If you want to merge this change then please take this pr: https://github.com/otland/forgottenserver/pull/3064

2020-06-22 15:08 UTC, lekzinn commented
> Hey, there was already another fix for that pr, because it introduced another bug.
> If you want to merge this change then please take this pr: [otland/forgottenserver#3064](https://github.com/otland/forgottenserver/pull/3064)


It is a very difficult scenario to simulate...
But I ran into this bug last night!

2020-06-30 02:35 UTC, dudantas commented
> Hey, there was already another fix for that pr, because it introduced another bug.
> If you want to merge this change then please take this pr: [otland/forgottenserver#3064](https://github.com/otland/forgottenserver/pull/3064)

Thanks for the feedback

2020-06-30 02:38 UTC, dudantas requested changes
According to the PR creator himself, this created another bug, which can be corrected by pulling the new PR from the link below:

https://github.com/otland/forgottenserver/pull/3064

2020-07-10 11:11 UTC, closed without merging