Print duplicate storages
opentibiabr/otservbr-global-archived pull request #1158
Opened 2020-05-07 05:17 UTC by andersonfaaria

This change has very low impact on startup and allow people to identify duplicate storages as long as all storages used in the game are inside this table.

2020-05-07 18:05 UTC, jlcvp commented on data/lib/core/storages.lua
> +        table.insert(ret, k)
I think it's better to use the table indexed by the value of the storage, that would require only 1 iteration on the array thus, O(n)

2020-05-07 18:05 UTC, jlcvp commented on data/lib/core/storages.lua
> +  print(string.format("Processado em %.4f(s)", os.clock() - benchmark))
I would recommend to use all the strings and comments in english

2020-05-07 18:05 UTC, jlcvp commented on data/lib/core/storages.lua
> +        table.insert(ret, k)
I also think that as this only runs once, there's no need for so much algorithmic analysis and this approach should fit well for most of the systems

2020-05-07 18:31 UTC, andersonfaaria commented on data/lib/core/storages.lua
> +        table.insert(ret, k)
I'm not sure if I've understood what you said, if you change the table Storage to be indexed by storage you won't have the possibility to referentiate the value in the scripts anymore.

As for the algorithmic analysis, is only to show that this code is ultra fast and can be left running every start up without any delays. it's actually O(log2(n) + 2n)

2020-05-26 04:42 UTC, lgrossi requested changes
Small suggestion on recursion improvement.
Looks good in general, quite useful.

2020-05-26 04:42 UTC, lgrossi commented on data/lib/core/storages.lua
> +local function extractValues(tab)
Como discutido, eu simplificaria essa recursão, mas tem que testar pq to com sono:
```
local function extractValues(tab, ret)
  if type(tab) == "number" then
    table.insert(ret, tab)
  else
    for _, v in pairs(tab) do
      extractValues(v, ret)
    end
  end
end

...

local extraction = {}
extractValues(Storage, extraction) 
```

edit: testado aqui, executando cada um 100x há uma melhoria de uns 35%

```
local benchmark = os.clock()
for i = 0, 100 do
	local extraction = {}
	extractValues(Storage, extraction)
end 
print(string.format("Processed in %.4f(s) (lucas)", os.clock() - benchmark))

local benchmark = os.clock()
for i = 0, 100 do
	local extraction = extractValues2(Storage)
end 
print(string.format("Processed in %.4f(s) (anderson)", os.clock() - benchmark))

...

Processed in 0.046968(s) (lucas)
Processed in 0.072279(s) (anderson)
```

2020-06-08 08:55 UTC, dudantas approved these changes
LGTM

2020-06-08 10:51 UTC, lgrossi approved these changes
Lgtm

2020-06-08 11:01 UTC, merged

2020-06-08 11:01 UTC, dudantas commented
Merged, thanks!