Update spells.xml
opentibiabr/otservbr-global-archived pull request #1208
Opened 2020-05-11 14:34 UTC by Lycanzito

adding coldoown for these spells atleast;

2020-05-11 14:35 UTC, Lycanzito commented
there is still missing the visual / action bar;

![image](https://user-images.githubusercontent.com/52710697/81573926-859ada00-937b-11ea-9659-60bc57b7bd1e.png)

2020-05-12 04:21 UTC, gpedro commented
Countdown - 40s (exaustion)
Group Countdown - 4s (group cd)

https://tibia.fandom.com/wiki/Eternal_Winter
https://tibia.fandom.com/wiki/Hell%27s_Core
https://tibia.fandom.com/wiki/Rage_of_the_Skies
https://tibia.fandom.com/wiki/Wrath_of_Nature

2020-05-12 04:23 UTC, gpedro requested changes

2020-05-12 04:23 UTC, gpedro commented on data/spells/spells.xml
> +	<instant group="special" spellid="118" name="Eternal Winter" words="exevo gran mas frigo" lvl="60" mana="1050" prem="1" selftarget="1" exhaustion="40000" groupcooldown="40000" needlearn="0" script="
40s for both?

2020-05-12 04:23 UTC, gpedro commented on data/spells/spells.xml
> +	<instant group="special" spellid="24" name="Hell's Core" words="exevo gran mas flam" lvl="60" mana="1100" prem="1" exhaustion="40000" groupcooldown="40000" selftarget="1" needlearn="0" script="attac
same here

2020-05-12 04:23 UTC, gpedro commented on data/spells/spells.xml
> +	<instant group="special" spellid="119" name="Rage of the Skies" words="exevo gran mas vis" lvl="55" mana="600" selftarget="1" prem="1" exhaustion="400000" groupcooldown="4000" needlearn="0" script="
400000? LOL

2020-05-12 04:23 UTC, gpedro commented on data/spells/spells.xml
> +	<instant group="special" spellid="56" name="Wrath of Nature" words="exevo gran mas tera" lvl="55" mana="700" prem="1" selftarget="1" exhaustion="40000" groupcooldown="40000" needlearn="0" script="at
40s for both?

2020-05-12 15:30 UTC, gerotib commented
You want to achieve "unified" cooldown for both spells? I have it done for each spell like this in src, without any changes in spells.xml, idk if thats best solution tho. Code im using: 
Below this line:
https://github.com/opentibiabr/otservbr-global/blob/658d04b6ea203f669af048011d6868bd916cdde8/src/spells.cpp#L812
add:
```
Condition* seccond_condition = 0;
				switch (spellId)
				{
					//Hell's Core and Rage of the Skies
				case 119:
					seccond_condition = Condition::createCondition(CONDITIONID_DEFAULT, CONDITION_SPELLCOOLDOWN, cooldown, 0, false, 24);
					player->addCondition(seccond_condition);
					break;
				case 24:
					seccond_condition = Condition::createCondition(CONDITIONID_DEFAULT, CONDITION_SPELLCOOLDOWN, cooldown, 0, false, 119);
					player->addCondition(seccond_condition);
					break;
					//Swift Foot and Sharpshooter
				case 134:
					seccond_condition = Condition::createCondition(CONDITIONID_DEFAULT, CONDITION_SPELLCOOLDOWN, cooldown, 0, false, 135);
					player->addCondition(seccond_condition);
					break;
				case 135:
					seccond_condition = Condition::createCondition(CONDITIONID_DEFAULT, CONDITION_SPELLCOOLDOWN, cooldown, 0, false, 134);
					player->addCondition(seccond_condition);
					break;
					//Ultimate Terra Strike and Ultimate Ice Strike
				case 156:
					seccond_condition = Condition::createCondition(CONDITIONID_DEFAULT, CONDITION_SPELLCOOLDOWN, cooldown, 0, false, 157);
					player->addCondition(seccond_condition);
					break;
				case 157:
					seccond_condition = Condition::createCondition(CONDITIONID_DEFAULT, CONDITION_SPELLCOOLDOWN, cooldown, 0, false, 156);
					player->addCondition(seccond_condition);
					break;
					//Ultimate Flame Strike and Ultimate Energy Strike
				case 155:
					seccond_condition = Condition::createCondition(CONDITIONID_DEFAULT, CONDITION_SPELLCOOLDOWN, cooldown, 0, false, 154);
					player->addCondition(seccond_condition);
					break;
				case 154:
					seccond_condition = Condition::createCondition(CONDITIONID_DEFAULT, CONDITION_SPELLCOOLDOWN, cooldown, 0, false, 155);
					player->addCondition(seccond_condition);
					break;
					//Blood Rage and Protector
				case 132:
					seccond_condition = Condition::createCondition(CONDITIONID_DEFAULT, CONDITION_SPELLCOOLDOWN, cooldown, 0, false, 133);
					player->addCondition(seccond_condition);
					break;
				case 133:
					seccond_condition = Condition::createCondition(CONDITIONID_DEFAULT, CONDITION_SPELLCOOLDOWN, cooldown, 0, false, 132);
					player->addCondition(seccond_condition);
					break;
					//Wrath of Nature and Eternal Winter
				case 118:
					seccond_condition = Condition::createCondition(CONDITIONID_DEFAULT, CONDITION_SPELLCOOLDOWN, cooldown, 0, false, 56);
					player->addCondition(seccond_condition);
					break;
				case 56:
					seccond_condition = Condition::createCondition(CONDITIONID_DEFAULT, CONDITION_SPELLCOOLDOWN, cooldown, 0, false, 118);
					player->addCondition(seccond_condition);
					break;
				}

```

2020-05-16 03:28 UTC, gabz182 commented
Funciona, mas se vc troca para " Special" e usa uma magia o cooldown não aparece na action bar para outra magia que usa "Special" tbm.. assim como ta na imagem.

2020-06-06 04:53 UTC, dudantas commented
Closing. This is not the correction, it is a gambiarra. The correct way is not to allow the player to have all the spells, only one of them at a time (and change them in the npcs)
But, thanks!

2020-06-06 04:53 UTC, closed without merging