Support for countMin in loot
opentibiabr/otservbr-global-archived pull request #1218
Opened 2020-05-13 05:07 UTC by andersonfaaria

This PR allows you to use countMin in the definition of a loot.

Now you can have countmin, countmax, both or neither.

2020-05-13 12:56 UTC, jlcvp requested changes
countmin is not declared on struct LootBlock on monsters.h

2020-05-13 12:56 UTC, jlcvp commented on src/monsters.cpp
> +		lootBlock.countmin = std::max<int32_t>(1, pugi::cast<int32_t>(attr.value()));
lootBlock isn't declared in monsters.h

2020-05-13 13:36 UTC, andersonfaaria commented on src/monsters.cpp
> +		lootBlock.countmin = std::max<int32_t>(1, pugi::cast<int32_t>(attr.value()));
you're right, must have missed this one. I'll add as soon as I leave the work

2020-05-13 20:39 UTC, jlcvp approved these changes
LGTM

2020-05-26 05:23 UTC, lgrossi approved these changes
lgtm

2020-06-11 12:53 UTC, merged