[WIP] feat: supply stash
opentibiabr/otservbr-global-archived pull request #1303
Opened 2020-06-05 06:45 UTC by vinioliveirasilva

Fix open stash
Fix add stackable item in stash

TODO:
Add multilayer stow (add a container)
Add withdraw

2020-06-05 09:29 UTC, marcosvf132 commented
Is there a way to convert item cid to item id? need this to add withdraw function.

2020-06-05 11:35 UTC, marcosvf132 commented
> Fix open stash
> Fix add stackable item in stash
> TODO:
> Add multilayer stow (add a container)
> Add withdraw
> Add migration

FIX 'add withdraw' with the following changes:

- On **\otservbr-global\src\game.cpp**
line 1078:
```lua
uint32_t flags = 0;
	int32_t index = toIndex;
	Item* toItem = nullptr;
	Cylinder* subCylinder = toCylinder->queryDestination(index, *item, &toItem, flags);
	if (subCylinder->getItem()->getID() == ITEM_SUPPLY_STASH) { //should be here?
		if (!(item->isStackable()) || 
			item->getID() == ITEM_GOLD_COIN ||
			item->getID() == ITEM_PLATINUM_COIN ||
			item->getID() == ITEM_CRYSTAL_COIN ) {
			return player->sendCancelMessage(RETURNVALUE_NOTPOSSIBLE);
		}
		std::ostringstream query;
		uint32_t itemCount = count;
		query << "SELECT * FROM `player_stash` WHERE `player_id` = ";
		query << player->getGUID() << " AND `item_id` = " << item->getClientID() << ";";
		DBResult_ptr hasItem = Database::getInstance().storeQuery(query.str());
		query.str("");
		if (!hasItem) {
			query << "INSERT INTO `player_stash` (`player_id`,`item_id`,`item_id2`, `item_count`) VALUES (";
			query << player->getGUID() << ", ";
			query << item->getClientID() << ", ";
			query << item->getID() << ", ";
			query << itemCount << " )";
		} else {
			int32_t qntInStash = hasItem->getNumber<int32_t>("item_count");
			query << "UPDATE `player_stash` SET `item_count` = ";
			query << itemCount + qntInStash;
			query << " WHERE `player_id` = " << player->getGUID();
			query << " AND `item_id2` = " << item->getID();
			query << " AND `item_id` = " << item->getClientID() << ";";
		}
		bool result = Database::getInstance().executeQuery(query.str());
		query.str("");
		if (result) {
			internalRemoveItem(item, itemCount);
			query << "Stowed " << itemCount << " object" << (itemCount > 1 ? "s." : ".");
			return player->sendCancelMessage(query.str());
		}
		return player->sendCancelMessage(RETURNVALUE_NOTPOSSIBLE);
	}
```
- On **\otservbr-global\data\globalevents\scripts\startup.lua**

```lua
...
installstashdb() -- At any place
...
-- At the end
function installstashdb()
	db.query([[CREATE TABLE IF NOT EXISTS `player_stash` (
  `player_id` INT(16) NOT NULL,
  `item_id` INT(32) NOT NULL,
  `item_id2` INT(32) NOT NULL,
  `item_count` INT(32) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;
   ]])
end
```
- On **\otservbr-global\data\modules\scripts\supplystash\supplystash.lua**

```lua
...
	elseif action == 3 then -- Withdraw from stash window
		local testando = msg:getU16()
		local itemCount = msg:getU32()
		print('withdraw')		
	local boid = db.storeQuery("SELECT `item_id2` FROM `player_stash` WHERE `player_id` = " .. player:getGuid() .. " AND `item_id` = " .. testando)
    local boidstamp = result.getStream(boid, "item_id2")
    result.free(boid)
		player:addItem(math.floor(boidstamp),itemCount)
	local boname = db.storeQuery("SELECT `item_count` FROM `player_stash` WHERE `player_id` = " .. player:getGuid() .. " AND `item_id` = " .. testando)
    local bonamestammp = result.getStream(boname, "item_count")
    result.free(boname)
	local ficouQT = math.floor(bonamestammp - itemCount)
		if ficouQT  == 0 then
		db.asyncQuery('DELETE FROM `player_stash` WHERE `item_id` = ' .. testando)
		else
		db.asyncQuery('UPDATE `player_stash` SET `item_count` = ' .. ficouQT .. ' WHERE `item_id` = '.. testando ..' AND `player_id` = ' .. player:getGuid())
		end
	end
end
-- End of archive
```
With this you already can withdraw items from the stash, but the problem is that when you withdraw, you need to close and open again the stashwindow to refresh the item count, if you dont do so, the item will get negative value and will bug your player_stash database, then you will need to delete the player_stash label on your database.

**Need to find a way to force a refresh.**

TODO: 
Add refresh stash counter
Add multilayer stow (add a container)
Add migration (?)

2020-06-05 22:18 UTC, vinioliveirasilva commented
> FIXED `Is there a way to convert item cid to item id? need this to add withdraw function. `
> Also, is crashing server when moving items to the floor/depot chest.

Yeh, using Game namespace: like this

(Game.getItemIdByClientId(ItemClientId)):getId() and we get item id

2020-06-06 05:12 UTC, marcosvf132 commented
> FIXED Is there a way to convert item cid to item id? need this to add withdraw function. 
> Also, is crashing server when moving items to the floor/depot chest.
> 
> Yeh, using Game namespace: like this
> (Game.getItemIdByClientId(ItemClientId)):getId() and we get item id

Is there a way to do the oposite? itemID to ClientID? i need that to make stow container work.

2020-06-06 06:01 UTC, FakeShinoda commented
This system can be easily wrote all in c++, we have alot of systems in modules that need to be rewrite in source.
Btw, good initiative !

2020-06-06 10:19 UTC, marcosvf132 commented
Hello again, i have done a script that you can 'stow' your main container. But it only work when you try to stow you main backpack when you select 'Stow container's contant' on the main backpack menu.

Other problem is that when you try to stow you main backpack, it dont stow all you items at once, on my tests, i tryed to stow 6k items, but when i click on it, it only stow almost half of the items at once, so you need to click on the menu more than once.  need to test it more because sometimes you lose some items on the process. in my example when i stow 6k items, i lost 100 items at the end.

I will post it here because maybe you can figure out how to fix it. 
**i'm not a pro, just trying to contribute with you guys.**

-  On \otservbr-global\data\modules\scripts\supplystash\supplystash.lua
```lua
...



	elseif action == 1 then
		local test11 = msg:getByte() -- 255 (?)
		local test12 = msg:getByte() -- 255 (?)
		local test13 = msg:getByte() -- SLOT ID when stow from main backpack, maybe it is the container position ?
		local myItem = player:getSlotItem(test13) -- Main backpack position (when try to stow from main backpack)
        searchitemsStash(myItem, player)
		print('stow container')	
	elseif action == 2 then
...
...
function searchitemsStash(test, JOGADOR)
	if test then
		for i = 0, test:getSize() do
				local item = test:getItem(i)
			if item then
					if item:isContainer() then
						print('container')	
						searchitemsStash(item, JOGADOR)
					end
				if (item:getCount() > 1) and not(item:getId() == 2160) and not(item:getId() == 2152) and not(item:getId() == 2148) and not(item:isContainer()) then
						local zero = 0
						local clientType = ItemType(item:getId())
						db.query("INSERT INTO `player_stash` (`player_id`, `item_id`, `item_count`) VALUES (" .. JOGADOR:getGuid() .. ", " .. clientType:getClientId() .. ", " .. zero .. ");")
						local items2 = loadStash(JOGADOR, clientType:getClientId(), 1000000)
					if items2[itemId] ~= nill then
					else
							local resulttestId = db.storeQuery("SELECT `item_count` FROM `player_stash` WHERE `player_id` = " .. JOGADOR:getGuid() .. " AND `item_id` = " .. clientType:getClientId())
						if resulttestId ~= false then
							local testando12 = result.getDataInt(resulttestId , "item_count")
							result.free(resulttestId)
							local TOTAL = math.floor(testando12 + item:getCount())
							db.asyncQuery('UPDATE `player_stash` SET `item_count` = ' .. TOTAL .. ' WHERE `item_id` = '.. clientType:getClientId() ..' AND `player_id` = ' .. JOGADOR:getGuid())
							item:remove(item:getCount())		
						end		
					end
				end	
			end
		end	
	end
end
```
As i said, i'm not a pro on programing, so it need several changes to make it perfect. But i only posted it here so maybe i can help someone to find a way to implement the 'stow' option in game.

2020-06-06 11:24 UTC, lgrossi reviewed
Looks good Im general. However, we should stop handling messages in lua. Messages operations should be centered in cpp, for many reasons: consistency, maintenance, security, etc. Lua is able to do exatcly the same thing via a callback that receive the parsed attributes of the message, not the message itself.

2020-06-06 11:24 UTC, lgrossi commented on data/modules/scripts/supplystash/supplystash.lua
>  function onRecvbyte(player, msg, byte)
That should be in cpp, protocolgame should control the network traffic and then call the necessary callback in lua.

2020-06-06 11:24 UTC, lgrossi commented on data/modules/scripts/supplystash/supplystash.lua
> +	local msg = NetworkMessage()
Same here.

2020-06-06 11:24 UTC, lgrossi commented on data/modules/scripts/supplystash/supplystash.lua
> +		local items = loadStash(player, itemId, itemCount)
Those messages operations should also be in cpp

2020-06-06 12:04 UTC, marcosvf132 commented
STOW CONTAINER: This script below can stow your main backpack, but **only works** if you click on 'stow container's content' on your main backpack menu.

- **On \otservbr-global\data\modules\scripts\supplystash\supplystash.lua**
```lua
...
	elseif action == 1 then
		local test11 = msg:getByte() -- 255 (?)
		local test12 = msg:getByte() -- 255 (?)
		local test13 = msg:getByte() -- SLOT ID when stow from main backpack, maybe it is the container position ?
		local myItem = player:getSlotItem(test13) -- Main backpack position (when try to stow from main backpack)
        searchitemsStash(myItem, player)
		print('stow container')	
	elseif action == 2 then
...
...

function searchitemsStash(test, JOGADOR)
	if test then
		for i = 0, test:getSize() do
				local item = test:getItem(i)
			if item then
					if item:isContainer() then
						searchitemsStash(item, JOGADOR)
					end
				if (item:getCount() > 1) and not(item:getId() == 2160) and not(item:getId() == 2152) and not(item:getId() == 2148) and not(item:isContainer()) then
				local clientType = ItemType(item:getId())
				local resulttestId = db.storeQuery("SELECT `item_count` FROM `player_stash` WHERE `player_id` = " .. JOGADOR:getGuid() .. " AND `item_id` = " .. clientType:getClientId())
				result.free(resulttestId)
				if resulttestId == false then
				local zero = 0
				db.query("INSERT INTO `player_stash` (`player_id`, `item_id`, `item_count`) VALUES (" .. JOGADOR:getGuid() .. ", " .. clientType:getClientId() .. ", " .. zero .. ");")
				end
					local itemCountPlayer = JOGADOR:getItemCount(item:getId())
					local resulttestId = db.storeQuery("SELECT `item_count` FROM `player_stash` WHERE `player_id` = " .. JOGADOR:getGuid() .. " AND `item_id` = " .. clientType:getClientId())
					local testando12 = result.getDataInt(resulttestId , "item_count")
					result.free(resulttestId)
					local TOTAL = math.floor(testando12 + itemCountPlayer)
					db.asyncQuery('UPDATE `player_stash` SET `item_count` = ' .. TOTAL .. ' WHERE `item_id` = '.. clientType:getClientId() ..' AND `player_id` = ' .. JOGADOR:getGuid())
					JOGADOR:removeItem(item:getId(), itemCountPlayer)
				end	
			end
		end	
	end
end
-- end of archive
```
As i said, only works if you stow you main backpack through the menu.
I know my scripts are bad, but i'm posting them here hoping that it can help someone.
The base script i got from 'quick loot' script!!

2020-06-07 20:04 UTC, vinioliveirasilva commented
If someone could test it too, i will be thankful.

2020-06-08 06:25 UTC, marcosvf132 commented
> If someone could test it too, i will be thankful.

Is working fine here,
I have done a script to implement some minor features:
-stow specific item.
-stow main container.
-stow all items of same type.
Need to do:
-Make checks if have available depot slots on supply stash.
-stow specific container.
**-Most important: optimize the script.**

- On \otservbr-global\data\modules\scripts\supplystash\supplystash.lua

```lua

SupplyStash = {
	Size = 1000
}

SupplyStash.Credits = {
	Developer = "DudZ, Ticardo (Rick), gpedro, vinioliveirasilva",
	Version = "1.0",
	lastUpdate = "17/04/2020 - 12:00",
	todo = {"Missing create a custom stash depot", "Stow"}
}

SupplyStash.S_Packets= { OpenWindow = 0x29 }
SupplyStash.C_Packets = { Withdraw = 0x28 }

function onRecvbyte(player, msg, byte)
    if (byte == SupplyStash.C_Packets.Withdraw) then
		SupplyStash.parseStash(player, msg)
	else
		print("byte desconhecido - " ..byte)
    end
end

function loadStash(player, idToExcludeIfZeroCount, count)
	local items = {}
	local resultId = db.storeQuery("SELECT * FROM `player_stash` WHERE `player_id` = " .. player:getGuid())
	if resultId ~= false then
	    repeat
	    	itemId = result.getDataInt(resultId , "item_id")
	    	itemCount = result.getDataInt(resultId , "item_count")
	    	if (itemId ~= idToExcludeIfZeroCount) then 
    			items[itemId] = itemCount
			elseif (itemCount > count) then
				items[itemId] = itemCount - count
	    	end
		until not result.next(resultId)
	end	
	result.free(resultId)
	return items
end

function sendOpenWindowMessage(player, items)
	local count = 0
	local depotSlots = 1
	for _, itemCount in pairs(items) do
		depotSlots = depotSlots + math.ceil(math.max(itemCount / 100, 1))
		count = count + 1
	end
	local msg = NetworkMessage()
	msg:addByte(SupplyStash.S_Packets.OpenWindow);
	msg:addU16(count)
	for id, count in pairs(items) do
		msg:addU16(id)
		msg:addU32(count)
	end
	msg:addU16(SupplyStash.Size - depotSlots)
	msg:sendToPlayer(player)
	return true
end

SupplyStash.sendOpenWindow = function(player)
	local items = loadStash(player, 0, 0)
	return sendOpenWindowMessage(player, items)
end

SupplyStash.parseStash = function(player, msg)
	local action = msg:getByte()
	if action == 0 then -- STOW SPECIFIC ITEM
		local from1 = msg:getPosition() -- Item position.
		local itemCIDSTOW = msg:getU16() -- Item client id to be stow.
		local empty1 = msg:getByte() -- Unknown
		local itemCountSTOW = msg:getByte() -- Item count to be stow.
		if itemCIDSTOW and itemCountSTOW then if from1 then if from1.x == CONTAINER_POSITION then
		local container = player:getContainerById(from1.y - 64)
		if container then
		local item = container:getItem(from1.z)
		stowItemofThis(player, (Game.getItemIdByClientId(itemCIDSTOW)):getId(), itemCountSTOW)
		item:remove(itemCountSTOW)
		end	end	end	end
	elseif action == 1 then -- STOW CONTAINER
		local from = msg:getPosition() -- Picked container to stow.
		local test11 = msg:getByte() -- Unknown
		local test12 = msg:getByte() -- Unknown
		local test13 = msg:getByte() -- SLOT ID when stow from main backpack
		-- if from then
		-- if from.x == CONTAINER_POSITION then
			-- local container1 = player:getContainerById(from.y - 64)
			-- if container1 then
		-- local item2 = container1:getItem(from.z)
--			if item2:isContainer then
--			-- Add function to check on this container.
--			end
			-- end
		-- end		
		-- end
        searchitemsStash(player:getSlotItem(test13), player, true)		
	elseif action == 2 then -- STOW ALL ITEMS OF SAME TYPE
		local from = msg:getPosition() -- ??
		local itemClientId = msg:getU16() -- ??
		if itemClientId then
		local itemCount = player:getItemCount((Game.getItemIdByClientId(itemClientId)):getId())
		stowItemofThis(player, (Game.getItemIdByClientId(itemClientId)):getId(), itemCount)
		player:removeItem((Game.getItemIdByClientId(itemClientId)):getId(), itemCount)
		end
	elseif action == 3 then -- WITHDRAW ITEM
		local itemId = msg:getU16()
		local itemCount = msg:getU32()
		local items = loadStash(player, itemId, itemCount)
		if items[itemId] ~= nill then
			db.asyncQuery('UPDATE `player_stash` SET `item_count` = ' .. items[itemId] .. ' WHERE `item_id` = '.. itemId ..' AND `player_id` = ' .. player:getGuid())
		else
			db.asyncQuery('DELETE FROM `player_stash` WHERE `item_id` = ' .. itemId)
		end
		player:addItem((Game.getItemIdByClientId(itemId)):getId(), itemCount)
		return sendOpenWindowMessage(player, items)
	end
end
function searchitemsStash(test, JOGADOR, ALL)
	if test then
		for i = 0, test:getSize() do
				local item = test:getItem(i)
			if item then
				if (item:getCount() > 1) and not(item:getId() == 2160) and not(item:getId() == 2152) and not(item:getId() == 2148) and not(item:isContainer()) then
						local itemCountPlayer = JOGADOR:getItemCount(item:getId())
						if ALL then
						stowItemofThis(JOGADOR, item:getId(), itemCountPlayer)
						JOGADOR:removeItem(item:getId(), itemCountPlayer)
						else
						stowItemofThis(JOGADOR, item:getId(), item:getCount())
					    -- Remove only item count.
						end
				end	
					if item:isContainer() then
						searchitemsStash(item, JOGADOR, ALL)
					end
			end
		end
	else
	return false
	end
end

function stowItemofThis(JOGADOR1, ITEMID, COUNT)
  if ITEMID then
	local clientType = ItemType(ITEMID)
	local resulttestId = db.storeQuery("SELECT `item_count` FROM `player_stash` WHERE `player_id` = " .. JOGADOR1:getGuid() .. " AND `item_id` = " .. clientType:getClientId())
	result.free(resulttestId)
	  if resulttestId == false then
	   local zero = 0
	   db.query("INSERT INTO `player_stash` (`player_id`, `item_id`, `item_count`) VALUES (" .. JOGADOR1:getGuid() .. ", " .. clientType:getClientId() .. ", " .. zero .. ");")
	  end
	local resulttestId = db.storeQuery("SELECT `item_count` FROM `player_stash` WHERE `player_id` = " .. JOGADOR1:getGuid() .. " AND `item_id` = " .. clientType:getClientId())
	local testando12 = result.getDataInt(resulttestId , "item_count")
	result.free(resulttestId)
	db.asyncQuery('UPDATE `player_stash` SET `item_count` = ' .. (math.floor(testando12 + COUNT)) .. ' WHERE `item_id` = '.. clientType:getClientId() ..' AND `player_id` = ' .. JOGADOR1:getGuid())
	JOGADOR1:sendTextMessage(21, "Stowed " .. COUNT .. " objects.")
  end
end

```
Its possible to use the your 'loadstash(...)' function on the script to check if the player already have the item on his stash depot. maybe its a better way to make this script simple and short.

2020-06-13 12:30 UTC, gpedro commented on src/game.cpp
> +		return player->sendCancelMessage(ret);
use return statement after method invocation cuz this method is void

2020-06-13 12:30 UTC, gpedro commented on src/game.cpp
> +		return player->sendCancelMessage(query.str());
use return statement after method invocation cuz this method is void

2020-06-13 12:31 UTC, gpedro commented on src/game.cpp
> +			return player->sendCancelMessage(RETURNVALUE_NOTPOSSIBLE);
use return statement after method invocation cuz this method is void

2020-06-13 12:31 UTC, gpedro commented on src/game.cpp
> +			return player->sendCancelMessage(RETURNVALUE_NOTPOSSIBLE);
same here

2020-06-26 03:53 UTC, vinioliveirasilva commented
Move communication data to cpp.

2020-06-29 20:47 UTC, vinioliveirasilva commented on src/luascript.cpp
> +int LuaScriptInterface::luaPlayerSetDepotStash(lua_State* L)
Remove

2020-06-29 20:47 UTC, vinioliveirasilva commented on src/luascript.h
> +		static int luaPlayerSetDepotStash(lua_State* L);
Remove

2020-06-29 20:48 UTC, vinioliveirasilva commented on src/luascript.cpp
> +	registerMethod("Player", "setDepotStash", LuaScriptInterface::luaPlayerSetDepotStash);
Remove

2020-06-29 20:49 UTC, vinioliveirasilva commented on src/protocolgame.cpp
> +void ProtocolGame::sendDepotStash(const bool enable)
Remove

2020-06-29 20:50 UTC, vinioliveirasilva commented on src/protocolgame.h
> +		void sendDepotStash(bool enable);
Remove

2020-07-11 01:15 UTC, MajestyOTBR commented
@gpedro @lgrossi PR waiting for your review.

2020-07-15 01:17 UTC, lgrossi requested changes
a few comments about safeness and code standards, looks fine in general.

2020-07-15 01:17 UTC, lgrossi commented on src/actions.cpp
> +bool enterStash(Player* player, Item*, const Position&, Thing*, const Position&, bool)
Why keeping all those trash parameters if you only use player?
Please clean it up.

2020-07-15 01:17 UTC, lgrossi commented on src/actions.cpp
> +bool enterMarket(Player* player, Item*, const Position&, Thing*, const Position&, bool)
Why keeping all those trash parameters if you only use player?
Please clean it up.

2020-07-15 01:17 UTC, lgrossi commented on src/actions.cpp
> +	if (player->getLastDepotId() == -1) {
what if player is a nullptr? please make it safer.

2020-07-15 01:17 UTC, lgrossi commented on src/actions.cpp
>  	if (player->getLastDepotId() == -1) {
what if player is a nullptr? please make it safer.

2020-07-15 01:17 UTC, lgrossi commented on src/depotlocker.cpp
> +	Container(type, 4), depotId(0) {} // 4 so we have space for stash
why for? what is this number about? can it become more meaningful?

2020-07-15 01:17 UTC, lgrossi commented on src/game.cpp
> +		toCylinder->getItem()->getID() == ITEM_LOCKER1 &&
What if getItem() returns an empty pointer? please, make it safer.

2020-07-15 01:17 UTC, lgrossi commented on src/game.cpp
> +		player->stowContainer(item, count);
is player validated anywhere? what if player is nullptr?

2020-07-15 01:17 UTC, lgrossi commented on src/game.cpp
> +		 player->sendCancelMessage(ret);
can't see any validation for player, what if it's a nullptr?

2020-07-15 01:17 UTC, lgrossi commented on src/player.cpp
> +	if (item == NULL || !isItemStorable(item)) {
change null for nullptr.

2020-07-15 01:17 UTC, lgrossi commented on src/player.cpp
> +	auto isContainerAndHasSomethingInside = item->getContainer() != NULL && item->getContainer()->getItemList().size() > 0;
what if item is nullptr?

2020-07-15 01:17 UTC, lgrossi commented on src/player.cpp
> +	auto allITems = container->getContainer()->getItemList();
what if container is nullptr?

2020-07-15 01:17 UTC, lgrossi commented on src/protocolgame.cpp
> +    msg.addPosition(creature->getPosition());
what if creature is nullptr?

2020-07-22 03:12 UTC, Geekbuddy commented
Tested. Works fine. Only that is missing is function for steward(hireling) to open the stash.

2020-07-22 03:22 UTC, gpedro commented
> Tested. Works fine. Only that is missing is function for steward(hireling) to open the stash.
> 
> Image: https://geekbuddys.com/gallery/image/3-supply-stashpng/

i found one missing feature and two bugs but I'm working on it!
- withdraw is using clientid instead serverid [FIXED]
- enable stow menu context [ADDED]
- stow context menu is only working for container (Stow All) [WORKING]

2020-08-04 22:23 UTC, jlcvp commented on data/movements/scripts/others/tiles.lua
> +			player:setDepotStash(true)
This attribute is only set when stepping on depot tile, If the player logs-out on it and then log back in this flag is not set and we got inconsistent behaviour

2020-08-09 19:05 UTC, MajestyOTBR commented
@marcosvf132 did a new PR for Supply Stash. This can be closed.

2020-08-09 19:05 UTC, closed without merging