Fix memory leak, error on Ubuntu 20.04 build and update GHA checks
opentibiabr/otservbr-global-archived pull request #1330
Opened 2020-06-11 02:32 UTC by Costallat

- Fix Ubuntu 20.04 error on compilation
- Fix memory leak
- Change GHA file-changes-action to use master

2020-06-11 03:01 UTC, lgrossi approved these changes
Lgtm, nice one adding libraries and unifying the compilation

2020-06-11 12:49 UTC, Znote requested changes
Much better than before, but lots of (presumed user tests?) failed between 4-5%
And annoyingly, the build failed to link the CXX executable properly? (I'm using a slow VM so it takes me about an hour to compile :P )

![image](https://user-images.githubusercontent.com/1552144/84386858-5bdf0800-abf2-11ea-9d15-a928d368ed69.png)

**Edit:** Increased swap size on my VM and got a successful build. Trying to test it out now. 

![image](https://user-images.githubusercontent.com/1552144/84395110-1c1e1d80-abfe-11ea-94b3-32485766c38e.png)

<details>
  <summary>Click to show compile log:</summary>
  
```bash
stefsien@freeuse:~/otbr/github$ sh recompile.sh
Directory 'build' already exists, moving to it
Clean build directory
Configuring
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at cmake/FindCryptoPP.cmake:73 (SET):
  implicitly converting 'DOC' to 'STRING' type.
Call Stack (most recent call first):
  CMakeLists.txt:60 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found CryptoPP: /usr/include (found version "5.6.4")
-- Found PugiXML: /usr/include
-- MySQL Include dir: /usr/include/mysql  library dir: /usr/lib/x86_64-linux-gnu
-- MySQL client libraries: /usr/lib/x86_64-linux-gnu/libmysqlclient.so;-ldl
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.53.0") found components: system filesystem iostreams date_time
-- Found LuaJIT: /usr/lib/x86_64-linux-gnu/libluajit-5.1.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "2.1.0-beta3")
-- Git Found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/stefsien/otbr/github/build
Scanning dependencies of target check_git
[  1%] Checking the git repository for changes...
[  1%] Built target check_git
Scanning dependencies of target otbr_lib
[  2%] Building CXX object CMakeFiles/otbr_lib.dir/src/otpch.cpp.o
[  3%] Building CXX object CMakeFiles/otbr_lib.dir/src/account.cpp.o
[  4%] Building CXX object CMakeFiles/otbr_lib.dir/src/actions.cpp.o
In file included from /home/stefsien/otbr/github/src/otpch.h:59,
                 from /home/stefsien/otbr/github/src/actions.cpp:19:
/home/stefsien/otbr/github/src/actions.cpp: In member function ‘ReturnValue Actions::canUse(const Player*, const Position&)’:
/home/stefsien/otbr/github/src/actions.cpp:294:15: warning: format ‘%d’ expects argument of type ‘int’, but argument 6 has type ‘int_fast32_t’ {aka ‘long int’} [-Wformat=]
  294 |  DLOG_F(INFO, "Player[%d] canUse from position:x[%d], y[%d], z[%d]?",
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  295 |      player == nullptr ? 0 : player->getID(),
  296 |      pos.getX(), pos.getY(), pos.getZ());
      |      ~~~~~~~~~~
      |              |
      |              int_fast32_t {aka long int}
/home/stefsien/otbr/github/src/actions.cpp:294:51: note: format string is defined here
  294 |  DLOG_F(INFO, "Player[%d] canUse from position:x[%d], y[%d], z[%d]?",
      |                                                  ~^
      |                                                   |
      |                                                   int
      |                                                  %ld
In file included from /home/stefsien/otbr/github/src/otpch.h:59,
                 from /home/stefsien/otbr/github/src/actions.cpp:19:
/home/stefsien/otbr/github/src/actions.cpp:294:15: warning: format ‘%d’ expects argument of type ‘int’, but argument 7 has type ‘int_fast32_t’ {aka ‘long int’} [-Wformat=]
  294 |  DLOG_F(INFO, "Player[%d] canUse from position:x[%d], y[%d], z[%d]?",
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  295 |      player == nullptr ? 0 : player->getID(),
  296 |      pos.getX(), pos.getY(), pos.getZ());
      |                  ~~~~~~~~~~
      |                          |
      |                          int_fast32_t {aka long int}
/home/stefsien/otbr/github/src/actions.cpp:294:58: note: format string is defined here
  294 |  DLOG_F(INFO, "Player[%d] canUse from position:x[%d], y[%d], z[%d]?",
      |                                                         ~^
      |                                                          |
      |                                                          int
      |                                                         %ld
In file included from /home/stefsien/otbr/github/src/otpch.h:59,
                 from /home/stefsien/otbr/github/src/actions.cpp:19:
/home/stefsien/otbr/github/src/actions.cpp:294:15: warning: format ‘%d’ expects argument of type ‘int’, but argument 8 has type ‘int_fast16_t’ {aka ‘long int’} [-Wformat=]
  294 |  DLOG_F(INFO, "Player[%d] canUse from position:x[%d], y[%d], z[%d]?",
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  295 |      player == nullptr ? 0 : player->getID(),
  296 |      pos.getX(), pos.getY(), pos.getZ());
      |                              ~~~~~~~~~~
      |                                      |
      |                                      int_fast16_t {aka long int}
/home/stefsien/otbr/github/src/actions.cpp:294:65: note: format string is defined here
  294 |  DLOG_F(INFO, "Player[%d] canUse from position:x[%d], y[%d], z[%d]?",
      |                                                                ~^
      |                                                                 |
      |                                                                 int
      |                                                                %ld
In file included from /home/stefsien/otbr/github/src/otpch.h:59,
                 from /home/stefsien/otbr/github/src/actions.cpp:19:
/home/stefsien/otbr/github/src/actions.cpp: In member function ‘ReturnValue Actions::canUse(const Player*, const Position&, const Item*)’:
/home/stefsien/otbr/github/src/actions.cpp:320:15: warning: format ‘%d’ expects argument of type ‘int’, but argument 7 has type ‘int_fast32_t’ {aka ‘long int’} [-Wformat=]
  320 |  DLOG_F(INFO, "Player[%d] canUse cid[%d] from position:x[%d], y[%d], z[%d]?",
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  321 |    player == nullptr ? 0 : player->getID(), item == nullptr ?
  322 |    0 : item->getClientID(), pos.getX(), pos.getY(), pos.getZ());
      |                             ~~~~~~~~~~
      |                                     |
      |                                     int_fast32_t {aka long int}
/home/stefsien/otbr/github/src/actions.cpp:320:59: note: format string is defined here
  320 |  DLOG_F(INFO, "Player[%d] canUse cid[%d] from position:x[%d], y[%d], z[%d]?",
      |                                                          ~^
      |                                                           |
      |                                                           int
      |                                                          %ld
In file included from /home/stefsien/otbr/github/src/otpch.h:59,
                 from /home/stefsien/otbr/g [...]

2020-06-11 14:27 UTC, Costallat commented
@Znote That is the log that we are adding to the server, to print more information, and it's expect an integer but the variable is from another integer type, like 'unsigned  int', but I updated the code to remove that warning.

2020-06-11 17:14 UTC, Costallat commented
> Lgtm, nice one adding libraries and unifying the compilation

Thanks you for the tips

2020-06-12 00:23 UTC, majestyotbr approved these changes

2020-06-12 01:48 UTC, merged