Update GameStore [12.20]
opentibiabr/otservbr-global-archived pull request #1381
Opened 2020-06-22 07:17 UTC by FakeShinoda

- Only work with protocol 12.20+

**Anti-choro**: Pega fogo cabaré !

2020-06-22 22:47 UTC, luisbill1 commented
> * Only work with protocol 12.20+
> 
> **Anti-choro**: Pega fogo cabaré !

Fiz o teste aqui. 
Achei dois erros importantes.

1 - Ao abrir a aba Outfits da crash no client.
2 - Tudo que é feito em stack com o personagem não funciona 
      Exemplo: abrir um loot em stack, fechar a porta estando dentro dela, descer o bueiro estando 
      em stack com ele, abrir uma backpack ou dar use em qual seja qual for o item. (única coisa que 
      funciona em stack é subir uma escada em stack com ela).

2020-06-24 20:37 UTC, dex-89 commented
@FakeShinoda 
On line 350 from file `data/modules/scripts/gamestore/init.lua` before 
`return addPlayerEvent(sendStorePurchaseSuccessful, 650, playerId, message)`
you can add
`sendUpdateCoinBalance(playerId)`
then after success refresh coin balance in store. Tested at 12.20 -> work correct 👍 , but exp boost can i buy always for 30 TC more and more... no limit.

2020-06-24 22:31 UTC, joao-blip commented
when trying to buy npc hireling this offer is unavailable [1]
@jlcvp

2020-06-24 23:42 UTC, jlcvp requested changes
Some of the hireling logic was removed, this will break the hireling handling on the store

2020-06-24 23:42 UTC, jlcvp commented on data/modules/scripts/gamestore/init.lua
> -	OFFER_TYPE_HIRELING = 17,
All the hireling offer types were removed here, this will break the hireling related stuff

2020-06-24 23:42 UTC, jlcvp commented on data/modules/scripts/gamestore/init.lua
> +			local pounch = self:getItemById(26377, true)
I would consider using a constant `GOLD_POUCH` instead of Id

2020-06-24 23:43 UTC, jlcvp commented
> when trying to buy npc hireling this offer is unavailable [1]
> @jlcvp

The hireling offer types and a bunch of validations related to them were removed.

2020-06-24 23:49 UTC, FakeShinoda commented
> 
> 
> > when trying to buy npc hireling this offer is unavailable [1]
> > @jlcvp
> 
> The hireling offer types and a bunch of validations related to them were removed.

When i finish *Hireling Offer Type* the rest will be added.

2020-06-25 13:21 UTC, gerotib commented on data/modules/scripts/gamestore/init.lua
> +				kit:setActionId(offerId)
This line should not be changed unless you want to change whole wrap system to actionid again. It was introduced in #921 (with pr on this state items are unable to unwrap)

2020-07-13 21:15 UTC, FakeShinoda commented
Closed to redirect efforts in store only via C++
Thanks Every1 !

2020-07-13 21:15 UTC, closed without merging