fix backpack imbuement
opentibiabr/otservbr-global-archived pull request #1398
Opened 2020-06-25 04:58 UTC by lekzinn

fix #582

2020-06-25 13:39 UTC, joao-blip commented
be the player is taking and placing the item your cap will accumulate.

2020-06-26 17:08 UTC, marcosvf132 commented
The bonus is permanent and is stacking.

2020-07-06 13:02 UTC, jlcvp requested changes
you need to implement onDeEquipImbueItem to remove the extra capacity added

2020-07-08 04:01 UTC, lekzinn commented
@dudantas  can you put the Labels "to review" and "need test"?

2020-07-08 05:33 UTC, gpedro commented on src/player.h
> +				return std::max<int32_t>(0, capacity + bonusCapacity - inventoryWeight);
can we use `getCapacity()` instead `capacity + bonusCapacity`

2020-07-08 05:35 UTC, joao-blip commented
from what I tested now is working the bug that was occurring before is fixed

2020-07-08 22:41 UTC, lekzinn commented on src/player.h
> +				return std::max<int32_t>(0, capacity + bonusCapacity - inventoryWeight);
resolved in e18bc5f

2020-07-11 00:48 UTC, majestyotbr approved these changes

2020-07-11 00:49 UTC, merged