Fixed Grizzly Adams not buying anything from the player.
opentibiabr/otservbr-global-archived pull request #1420
Opened 2020-07-02 16:19 UTC by nickolasdeluca

Grizzly wasn't buying anything the player tried to sell and was throwing an error.
I was able to fix this issue but this script probably needs a remake, It's messy and probably outdated, I am currently not skilled enough to do it but this at least makes him able to trade again.

2020-07-13 23:39 UTC, gpedro requested changes

2020-07-13 23:39 UTC, gpedro commented on data/npc/scripts/grizzly_adams.lua
> +		player:removeMoneyNpc(amount * items[item].buy)
you need to check if the money is removed

2020-07-13 23:39 UTC, gpedro commented on data/npc/scripts/grizzly_adams.lua
> +		player:removeItem(items[item].id, amount)
you need to check if the item is removed before addMoney

2020-07-15 06:11 UTC, lekzinn commented
have another problem in this NPC:
If you said trade X times to NPC, it is duplicated items on trade window. 

Need check npcHandler.topic[cid] on msgcontains('trade', msg)

2020-07-15 12:38 UTC, nickolasdeluca commented
> have another problem in this NPC:
> If you said trade X times to NPC, it is duplicated items on trade window.
> 
> Need check npcHandler.topic[cid] on msgcontains('trade', msg)

Yep, that's why I said this npc needs a complete rework, fixing these issues, I was merely getting it back to work. I tried to fix some issues with his dialogues but I couldn't, I'm still learning lua and how npc dialogue works.

I'll fix the issues gpedro specified but I believe someone more experienced should recreate Grizzly's lua entirely.

2020-07-15 12:43 UTC, lekzinn commented
> > have another problem in this NPC:
> > If you said trade X times to NPC, it is duplicated items on trade window.
> > Need check npcHandler.topic[cid] on msgcontains('trade', msg)
> 
> Yep, that's why I said this npc needs a complete rework, fixing these issues, I was merely getting it back to work. I tried to fix some issues with his dialogues but I couldn't, I'm still learning lua and how npc dialogue works.
> 
> I'll fix the issues gpedro specified but I believe someone more experienced should recreate Grizzly's lua entirely.

I don't think need recreate entirely...
just put a condition check if player already said trade to NPC. Something like this:

```lua
...
if msgcontains('trade', msg) then
    if npcHandler.topic[cid] == 4 then
        return false;
    end
    npcHandler.topic[cid] = 4
...
```

2020-07-15 12:46 UTC, nickolasdeluca commented
> I don't think need recreate entirely...
> just put a condition check if player already said trade to NPC. Something like this:
> 
> ```lua
> ...
> if msgcontains('trade', msg) then
>     if npcHandler.topic[cid] == 4 then
>         return false;
>     end
>     npcHandler.topic[cid] = 4
> ...
> ```

k, I'll give it a go, thanks for the code.

2020-07-16 01:13 UTC, nickolasdeluca commented on data/npc/scripts/grizzly_adams.lua
> +		player:removeMoneyNpc(amount * items[item].buy)
Added the required validations.

2020-07-16 01:13 UTC, nickolasdeluca commented on data/npc/scripts/grizzly_adams.lua
> +		player:removeItem(items[item].id, amount)
Added the required validations.

2020-07-16 01:15 UTC, nickolasdeluca commented
> 
> I don't think need recreate entirely...
> just put a condition check if player already said trade to NPC. Something like this:
> 
> ```lua
> ...
> if msgcontains('trade', msg) then
>     if npcHandler.topic[cid] == 4 then
>         return false;
>     end
>     npcHandler.topic[cid] = 4
> ...
> ```

Turns out the issue wasn't in the dialogue but rather on the joinTables function.

2020-07-18 16:39 UTC, dudantas reviewed
It looks ok, only the warnings need to be resolved.

2020-07-18 17:25 UTC, nickolasdeluca commented
> It looks ok, only the warnings need to be resolved.

Well, that's the best I can do, If I fix the lines bigger than 120 characters then luacheck complains that the line has trailing white spaces. Dunno what it want's me to do. I could create a local var to store the messages but that feels unnecessary.

2020-07-19 19:23 UTC, nickolasdeluca commented
> It looks ok, only the warnings need to be resolved.

Done, fixed all the warnings.

2020-07-19 20:37 UTC, dudantas approved these changes

2020-07-20 00:41 UTC, merged