Fix bestiary point count
opentibiabr/otservbr-global-archived pull request #1528
Opened 2020-07-21 04:21 UTC by lekzinn

Before: The bestiary point only go to most damage player.
After: points for everyone who did damage

2020-07-21 05:49 UTC, dudztroyer commented
Bestiary only goes to the player who killed, in global. Not whole party... AFAIK

2020-07-21 13:42 UTC, aurelion5670 commented
On real tibia it works to every player that does damage to the monster

2020-07-21 13:43 UTC, aurelion5670 approved these changes

2020-07-21 18:41 UTC, FakeShinoda requested changes

2020-07-21 18:41 UTC, FakeShinoda commented on data/creaturescripts/scripts/others/bestiary_kill.lua
> +	for playerid, damage in pairs(creature:getDamageMap()) do
Why 2 loop? you can do all you need in the damageMap loop

2020-07-21 18:46 UTC, gpedro commented on data/creaturescripts/scripts/others/bestiary_kill.lua
> +	for playerid, damage in pairs(creature:getDamageMap()) do
this can be replaced by
```lua
for player, damage in pairs(creature:getDamageMap()) do
  local player = Player(id)
  if player and player:isPlayer() then
    player:addBestiaryKill(creature:getName())
  end
end
```

2020-07-21 20:01 UTC, Attack787 commented
Working perfectly like tibia  global. thanks for job :D

2020-07-21 20:03 UTC, lekzinn commented on data/creaturescripts/scripts/others/bestiary_kill.lua
> +	for playerid, damage in pairs(creature:getDamageMap()) do
creature:getDamageMap can return duplicate ids players.
this occurs for players who can deal different types of damage to a creature

So, two loops to ensure that we don't have duplicate players

2020-07-21 20:22 UTC, gpedro commented on data/creaturescripts/scripts/others/bestiary_kill.lua
> +	for playerid, damage in pairs(creature:getDamageMap()) do
are you sure?
https://github.com/opentibiabr/otservbr-global/blob/develop/src/creature.cpp#L1001-L1021

2020-07-21 20:34 UTC, lekzinn commented on data/creaturescripts/scripts/others/bestiary_kill.lua
> +	for playerid, damage in pairs(creature:getDamageMap()) do
> are you sure?
> https://github.com/opentibiabr/otservbr-global/blob/develop/src/creature.cpp#L1001-L1021

:dancers: 
I will check, because when i put only one loop the points is duplicated :-1:

2020-07-21 21:36 UTC, lekzinn commented on data/creaturescripts/scripts/others/bestiary_kill.lua
> +	for playerid, damage in pairs(creature:getDamageMap()) do
resolved https://github.com/opentibiabr/otservbr-global/pull/1528/commits/51ffa6c583b2221f56683d4ae2151553a75e68fc

2020-07-25 00:37 UTC, MajestyOTBR commented on data/creaturescripts/scripts/others/bestiary_kill.lua
> +		local player = Player(cid)
Check warning on line 7 in data/creaturescripts/scripts/others/bestiary_kill.lua


GitHub Actions
/ reviewers

data/creaturescripts/scripts/others/bestiary_kill.lua#L7
[luacheck] reported by reviewdog 🐶
shadowing definition of argument 'player' on line 1

Raw Output:
data/creaturescripts/scripts/others/bestiary_kill.lua:7:9: shadowing definition of argument 'player' on line 1

2020-07-28 21:57 UTC, majestyotbr approved these changes

2020-07-28 21:57 UTC, merged