Quest Tracker Feature
opentibiabr/otservbr-global-archived pull request #1614
Opened 2020-08-03 00:07 UTC by joseluis2g

Adding quest tracker features, mostly all credits go to saiyansking, I  just updated this to work with Lua.
Also added a new value to quest.lua, missionId, this value should be unique and every mission needs one.
Added a new player event called onResetTrackedQuests, name tells you pretty much everything what it does.

2020-08-03 03:13 UTC, gpedro requested changes
LGTM, minor changes

2020-08-03 03:13 UTC, gpedro commented on data/lib/core/quests.lua
> +						[9] = "You received Rahkem\'s prayer: &quot;Let there be power and compassion&quot;. \z
why needs to escape the apostrophe?

2020-08-03 03:13 UTC, gpedro commented on data/lib/core/quests.lua
> +			msg:addString(Quests[questId].name .. ""..(self:questIsCompleted(questId) and " (completed)" or ""))
doesn't need two concat

2020-08-03 03:13 UTC, gpedro commented on data/lib/core/quests.lua
> +	msg:addByte(count)
you can use directly
```lua
msg:addByte(#missions)
```

2020-08-03 03:13 UTC, gpedro commented on data/lib/core/quests.lua
> +	for i = 1, count do
you can use loop-pairs instead

2020-08-03 16:43 UTC, joseluis2g commented on data/lib/core/quests.lua
> +						[9] = "You received Rahkem\'s prayer: &quot;Let there be power and compassion&quot;. \z
there was an error with the script I did to add mission ids and escape characters so I just did a check for all escape characters to add this "\"

2020-08-03 16:45 UTC, joseluis2g commented on data/lib/core/quests.lua
> +			msg:addString(Quests[questId].name .. ""..(self:questIsCompleted(questId) and " (completed)" or ""))
my bad

2020-08-03 16:45 UTC, joseluis2g commented on data/lib/core/quests.lua
> +	msg:addByte(count)
thats a fact

2020-08-03 17:04 UTC, joseluis2g commented
Remove events call, now it uses modules to read the message.
Fix @gpedro conflicts.

2020-08-03 17:18 UTC, marcosvf132 commented on src/protocolgame.h
> +
Empty commit

2020-08-03 17:20 UTC, joseluis2g commented on src/protocolgame.h
> +
Thanks

2020-08-04 04:14 UTC, gpedro commented on data/modules/scripts/questtrack/questtrack.lua
> +	if (byte == 0xD0) then
unnecessary parenthesis :D

2020-08-04 04:15 UTC, gpedro approved these changes

2020-08-05 01:42 UTC, MajestyOTBR commented
Tested, working. Thanks for your contribution.

2020-08-05 01:43 UTC, merged