Dawnport correções
opentibiabr/otservbr-global-archived pull request #167
Opened 2019-06-17 22:57 UTC by fabiobillz

2019-06-17 23:48 UTC, gpedro commented on data/actions/scripts/dawnport.lua
> +		items = {},
esta variável de items não está sendo utilizada?

2019-06-17 23:49 UTC, gpedro commented on data/actions/scripts/dawnport.lua
> +	local targetVocation = config[voc]
necessário verificar se essa vocação existe como chave config.

2019-06-17 23:50 UTC, gpedro commented on data/actions/scripts/dawnport.lua
> +			--return true
por que isso está comentado?

2019-06-17 23:50 UTC, gpedro commented on data/actions/scripts/dawnport.lua
> +		player:setStorageValue(Storage.Dawnport.Items, 1)
faltou uma identação neste bloco

2019-06-17 23:51 UTC, gpedro commented on data/creaturescripts/scripts/others/firstitems.lua
> +	local backpack = player:getVocation():getId() == 0 and player:addItem(1988) or player:addItem(1988)
isso está correto?

2019-06-17 23:55 UTC, gpedro commented on data/movements/scripts/walkback.lua
> +		if position == fromPosition then
identação demais.

2019-06-17 23:56 UTC, gpedro commented on data/movements/scripts/walkback.lua
> +local SPECIAL_QUESTS = {2215, 2216, 10544, 12374, 12513, 26300, 27300, 28300}
essas actionIds são de qual quest?

2019-06-17 23:56 UTC, gpedro requested changes
apontei algumas melhorias. favor analisar xD

2019-06-18 11:35 UTC, eduardodantas95 commented on data/actions/actions.xml
> +	<action uniqueid="50466" script="dawnport.lua"/>
Aqui dá para você deixar fromuid="50463" touid=50466, não é necessário utilizar 4 linhas

2019-06-26 00:17 UTC, closed without merging