Fix: Hotkey equip on cpp + fixes
opentibiabr/otservbr-global-archived pull request #1707
Opened 2020-08-30 01:03 UTC by marcosvf132

Resolves #1039
Resolves some parts of #836 (Are the other part really bug?)

- [x] Hotkey equip/dequip changed to CPP.
- [x] No delay on equip/dequip item (As global tibia do).
- [x] Restack ammo if pressed hotkey item is the same as slot.
- [x] Diamond arrow/spectral bolt can be stacked only if there are equal. (Preventing reset decay time)
- [x] Ammo are sent to the ammo quickloot backpack, if not possible , to the main backpack. (As global tibia do)

Thank to @dracoalv for guiding me how it should be working.

2020-08-30 17:42 UTC, dracoalv commented
A hotkey equip ficou perfeita para arrow e bolts no geral com excecão das Diamonds Arrows e Spectral Bolts cujo não completam o inventário em caso de faltas, nada grave.

2020-09-01 00:32 UTC, FakeShinoda requested changes

2020-09-01 00:32 UTC, FakeShinoda commented on src/protocolgame.cpp
> +		case 0x77: onPressHotkeyEquip(msg); break;
Can you make this a **parsePressHotkeyEquip** and create a function just for parse?

2020-09-01 00:32 UTC, FakeShinoda commented on src/protocolgame.cpp
> +void ProtocolGame::onPressHotkeyEquip(NetworkMessage& msg)
With the parse function.. You can create a game.cpp function to handle this code, use protocolgame.cpp just for communications

2020-09-01 00:32 UTC, FakeShinoda commented on src/protocolgame.cpp
> +	if (item == nullptr) {
you can also try !item

2020-09-01 02:06 UTC, FakeShinoda commented on src/protocolgame.cpp
> +	g_game.onPressHotkeyEquip(player, spriteid);
Better use **addGameTask(&Game::onPressHotkeyEquip, player, spriteid);**

2020-09-01 03:46 UTC, FakeShinoda approved these changes

2020-09-01 09:18 UTC, dudantas approved these changes

2020-09-03 00:55 UTC, MajestyOTBR approved these changes

2020-09-03 00:56 UTC, merged