adicionado os mapas custom por worldchanges
opentibiabr/otservbr-global-archived pull request #171
Opened 2019-06-19 03:41 UTC by eduardodantas95

trainers, event room and npc shop added by worldchanges

2019-06-19 04:41 UTC, gpedro requested changes

2019-06-19 04:41 UTC, gpedro commented on data/movements/movements.xml
> +    <movevent event="StepIn" actionid="14877" script="custom/trainerTPRemove.lua"/>
missing identation

2019-06-19 04:41 UTC, gpedro commented on data/globalevents/globalevents.xml
> +	<globalevent name="Additional" type="startup" script="custom/worldchanges/additionals/trainers_eventRoom.lua"/>
you can rename for custom/additionalsMapLoading.lua, what's your think?

2019-06-19 04:41 UTC, gpedro commented on data/movements/scripts/custom/trainerTPRemove.lua
> +
trailing spaces

2019-06-19 04:41 UTC, gpedro commented on data/movements/scripts/custom/trainertp.lua
> +
trailing spaces

2019-06-19 15:23 UTC, eduardodantas95 commented on data/globalevents/globalevents.xml
> +	<globalevent name="Additional" type="startup" script="custom/worldchanges/additionals/trainers_eventRoom.lua"/>
Yes

2019-06-19 15:30 UTC, gpedro approved these changes
LGTM

2019-06-19 15:32 UTC, merged

2019-07-06 01:09 UTC, Sacres97 commented
I don't know why it load map with trainers but doesn't load spawn file.