Convert final actions to revscriptsys
opentibiabr/otservbr-global-archived pull request #1822
Opened 2020-10-05 09:35 UTC by dudantas

Resolves #1821

Functions moved to Lua:
Open imbuement shrine
Open stash
Open market

2020-10-05 11:09 UTC, yatozin commented
market isnt working

2020-10-05 15:20 UTC, dudantas commented
> market isnt working player:sendOpenMarket() to player:openMarket() ?

Fixed, thanks

2020-10-05 17:31 UTC, lgrossi requested changes
Nice one, movign actions to revscripts is a big one. Left a few comments related to giving lua better feedbacks and some moving some logic to the correct domains, but it's good in general.

2020-10-05 17:31 UTC, lgrossi commented on src/luascript.cpp
> +	player->sendMarketEnter(player->getLastDepotId());
Does sendMarketEnter always succeed?
If that's not the case, would be nice if it returns a value (true/false or error_type/non_error) so that we can return it to lua and properly handle it.

2020-10-05 17:31 UTC, lgrossi commented on src/luascript.cpp
>  	return 1;
Would be nice to give lua some feedbacks here (push false if no player or sendOpenStash fails, push true if it executes properly).

2020-10-05 17:31 UTC, lgrossi commented on src/protocolgame.cpp
> +
As discussed, those validations should live in player.cpp, ideally.

2020-10-05 17:31 UTC, lgrossi commented on src/protocolgame.cpp
> -	if (!itemHasImbue && imbuements.empty()) {
Isn't this if needed anymore?

2020-10-05 17:31 UTC, lgrossi commented on src/protocolgame.cpp
> +
I'd move it to player::sendOpenStash as well, since it is player logic, nothing to do with protocol.

2020-11-19 20:38 UTC, dudantas commented on src/protocolgame.cpp
> +
Fix on https://github.com/opentibiabr/otservbr-global/pull/1822/commits/d866087947625b1da76d3987315b9078694e0628

2020-11-19 20:41 UTC, dudantas commented on src/protocolgame.cpp
> -	if (!itemHasImbue && imbuements.empty()) {
Do not needed.

2020-11-19 22:34 UTC, lgrossi commented on src/player.cpp
> +		return;
maybe some text message here? what does it mean if last depoit id is -1? Nothing that the player should be aware of?

2020-11-19 22:37 UTC, lgrossi commented on src/player.h
>  			}
Not a big deal, but I'd simplify:

```
void sendOpenStash()
  {
      if (!client || getLastDepotId() == -1) {
            return;
      }
      client->sendOpenStash();
}
```
Just because it remove some nesting and is easier to read.

2020-11-19 22:40 UTC, lgrossi approved these changes
LGTM, I added some suggestions. The return ifs are nice when you have complex functions, when you have simple ones I'd just go straightforward.

2020-11-19 23:21 UTC, dudantas commented on src/player.cpp
> +		return;
Thanks.

2020-11-19 23:23 UTC, dudantas commented on src/player.h
>  			}
Thanks.

2020-11-19 23:32 UTC, dudantas commented
> LGTM, I added some suggestions. The return ifs are nice when you have complex functions, when you have simple ones I'd just go straightforward.

Thanks, great tips, I followed as you said.

2020-11-19 23:44 UTC, merged