Monster's Reflect System
opentibiabr/otservbr-global-archived pull request #1876
Opened 2020-10-13 21:45 UTC by morenao97

+ Added Reflect monster system, with all monsters already registered.
+ All percentages based on the tibia.wikia, for check: https://tibia.fandom.com/wiki/Damage_Reflection
* Need to check if all monsters have the correct resistence for yours reflected elements.
* Leiden is listed, but already have a system for him, need to check the others bosses.
* The reflect% not listed on the tibia.wikia (like Faceless Bane and Bragrumol) was taken from tibiawiki.com.br
* On global, all damages are converted for heal, the possibility for choose on this script is for custom monsters.

2020-10-13 22:51 UTC, lekzinn requested changes

2020-10-13 22:51 UTC, lekzinn commented on data/events/scripts/creature.lua
> +	if target and target:isMonster() then
it is not necessary to check the target, because in line 59 it is being used and this ends up guaranteeing that the target will not be null.

2020-10-13 22:51 UTC, lekzinn commented on data/scripts/creaturescripts/monster/MonstersReflectSystem.lua
> +local ReflectSystem = CreatureEvent("ReflectSystem")
lowercase file name

2020-10-13 22:51 UTC, lekzinn commented on data/scripts/creaturescripts/monster/MonstersReflectSystem.lua
> +local reflect = {
change variable name to monstersList

2020-10-13 22:51 UTC, lekzinn commented on data/scripts/creaturescripts/monster/MonstersReflectSystem.lua
> +	if monster[1] == "all" or isInArray(monster[1], primaryType) then
only primaryType damage is reflected?

2020-10-13 22:51 UTC, lekzinn commented on data/scripts/creaturescripts/monster/MonstersReflectSystem.lua
> +	if monster[1] == "all" or isInArray(monster[1], primaryType) then
I don't like to use "all" here. What if a new type is created that this monster does not reflect?

2020-10-13 22:51 UTC, lekzinn commented on data/scripts/creaturescripts/monster/MonstersReflectSystem.lua
> +function ReflectSystem.onHealthChange(creature, attacker, primaryDamage, primaryType, secondaryDamage, secondaryType, origin)
Check the damage order applied. There are monsters that reflect ice damage that are strong against the same type.

2020-10-13 22:53 UTC, MajestyOTBR commented on data/scripts/creaturescripts/monster/MonstersReflectSystem.lua
> +local ReflectSystem = CreatureEvent("ReflectSystem")
monsters_reflect_system

2020-10-14 05:09 UTC, morenao97 commented on data/events/scripts/creature.lua
> +	if target and target:isMonster() then
Check.

2020-10-14 05:18 UTC, morenao97 commented
Refiz o script seguindo os pedidos de voces;
Corrigi a falha em que o secondaryDamage nao era checado;
Corrigi o fato de que todos os monstros estavam curando;
Mantive o "all", não me faz sentido escrever os 8 tipos de dmg pra caso aparecer um novo em que o monstro nao é imune;
O valor do reflect, foi mantido tal como foi conversado no discord, usando os dados do tibia wikia, que não sabemos se está ou não 100% corretos.
***O healthchange é checado após as reduções!

2020-10-14 20:22 UTC, MajestyOTBR commented on data/scripts/creaturescripts/monster/MonstersReflectSystem.lua
> +local ReflectSystem = CreatureEvent("monsters_reflect_system")
lowercase file name -> monsters_reflect_system.lua

2020-10-14 20:23 UTC, MajestyOTBR commented on data/scripts/creaturescripts/monster/MonstersReflectSystem.lua
> +local ReflectSystem = CreatureEvent("monsters_reflect_system")
lowercase file name -> data/scripts/creaturescripts/monster/monsters_reflect_system.lua

2020-11-13 21:51 UTC, debone commented on data/scripts/creaturescripts/monster/monsters_reflect_system.lua
> +				primaryType = COMBAT_HEALING
Can you clarify why the change of primaryType? Why after causing the negative/healing?

2020-11-29 18:02 UTC, debone commented
I'm closing this one just as it got staled, feel free to re-open it if you want to update it.

2020-11-29 18:02 UTC, closed without merging