Lion Rod & Wand fix
opentibiabr/otservbr-global-archived pull request #1904
Opened 2020-10-22 23:55 UTC by yatozin

2020-10-23 11:18 UTC, MajestyOTBR commented on data/lib/core/imbuements.lua
> +	["special_wand"] = {35234, 38986},
lion wand id 38987 in special_wand

2020-10-23 11:18 UTC, MajestyOTBR commented on data/lib/core/imbuements.lua
> +	["special_rod"] = {35235, 38987},
lion rod id 38986 in special_rod

2020-10-23 11:21 UTC, MajestyOTBR commented on data/lib/core/imbuements.lua
> +	["special_wand"] = {35234, 38986},
is it correct?

2020-10-23 11:21 UTC, MajestyOTBR commented on data/lib/core/imbuements.lua
> +	["special_rod"] = {35235, 38987},
is it correct?

2020-10-23 16:00 UTC, yatozin commented on data/lib/core/imbuements.lua
> +	["special_rod"] = {35235, 38987},
lion rod is the same as cobra wand
lion wand is same as cobra rod

2020-10-25 19:32 UTC, FakeShinoda requested changes

2020-10-25 19:32 UTC, FakeShinoda commented on data/lib/core/imbuements.lua
> +	["special_strike"] = {32417, 32416, 30693, 30692, 32523, 32522, 34063, 38925, 38926}, --ok
Please move "38925" to cri_wandrod and "38926" to life_wandrod

2020-10-25 20:29 UTC, yatozin commented on data/lib/core/imbuements.lua
> +	["special_strike"] = {32417, 32416, 30693, 30692, 32523, 32522, 34063, 38925, 38926}, --ok
the soul items can be imbue with all they don't have same restriction

2020-11-03 14:46 UTC, HeberPcL commented
@yatozin How is the progress of this PR?

2020-11-03 20:50 UTC, yatozin commented
> @yatozin How is the progress of this PR?

its complete the requested changes are incorrect, Soultainter and Soulhexer dont have the restrictions of other crit and life wand/rods, they can have all imbues for wands

2020-11-05 03:48 UTC, FakeShinoda approved these changes

2020-11-05 15:37 UTC, merged