Fix #1905
opentibiabr/otservbr-global-archived pull request #1923
Opened 2020-11-01 19:28 UTC by HeberPcL

Action AID changed

2020-11-01 21:36 UTC, debone requested changes

2020-11-01 21:36 UTC, debone commented on data/lib/core/functions.lua
> +function doComparePositions(position, positionEx)
Maybe reuse https://github.com/opentibiabr/otservbr-global/blob/develop/data/lib/core/position.lua ?

2020-11-01 21:36 UTC, debone commented on data/events/scripts/player.lua
>  function Player:onMoveItem(item, count, fromPosition, toPosition, fromCylinder, toCylinder)
While I agree to use a different API to check the parchment, I don't think moving it out of its own file to the player.lua is a good move. We cannot keep such specific functionality for a quest mixed with the player stuff.

2020-11-01 22:04 UTC, HeberPcL commented on data/events/scripts/player.lua
>  function Player:onMoveItem(item, count, fromPosition, toPosition, fromCylinder, toCylinder)
I don't like it either, do you have any suggestions?

2020-11-03 14:54 UTC, HeberPcL commented on data/lib/core/functions.lua
> +function doComparePositions(position, positionEx)
Yes, I change now.

2020-11-19 22:45 UTC, dudantas commented
In reality, onRemoveItem bugged this PR: https://github.com/opentibiabr/otservbr-global/pull/1779/files

The solution is only for onAddItem. But, thanks.

2020-11-19 22:45 UTC, closed without merging