Clean performance fix
opentibiabr/otservbr-global-archived pull request #1930
Opened 2020-11-03 00:00 UTC by HeberPcL

**Old PR:** 
Optimized Clean with optional Protection Zone Clean [#1800](https://github.com/opentibiabr/otservbr-global/pull/1800)

A bug was detected and the code was removed. I'm bringing a **_TFS_** fix made by **@TheSumm**

@yatozin Can test it ?

2020-11-03 00:47 UTC, SaiyansKing commented on src/game.h
> +		std::unordered_set<Tile*> getTilesToClean() const {
It should return a reference " std::unordered_set<Tile*>& " because it'll keep making unnecessary copies every time getTilesToClean() gets called.

2020-11-03 01:01 UTC, HeberPcL commented on src/game.h
> +		std::unordered_set<Tile*> getTilesToClean() const {
humm..

2020-11-15 22:10 UTC, dex-89 requested changes
Check conflicts

2020-11-21 12:19 UTC, dex-89 commented
I tested it. Works, but sometimes crash server `Memory protection violation`. I try fix it in other PR

2020-11-21 12:19 UTC, closed without merging