config.lua houseOwnedByAccount
opentibiabr/otservbr-global-archived pull request #1936
Opened 2020-11-03 05:56 UTC by HeberPcL

config: houseOwnedByAccount 

This enables or disables the possibility that characters from the same account automatically become "owners" and have full access to the house.

From TFS by @MillhioreBT

2020-11-13 18:52 UTC, dex-89 approved these changes
Works perfectly :) I tested as false and true in config.lua. Great work 👍

2020-11-13 21:26 UTC, debone requested changes

2020-11-13 21:26 UTC, debone commented on src/iologindata.cpp
> +	query << "SELECT `account_id` FROM `players` WHERE `name` = " << db.escapeString(playerName);
Can't we look for player by their id? I'm scratching my head wondering if any crazy name wouldn't send this to space and it feels so much better to simply use the id?

2020-11-15 10:09 UTC, dex-89 approved these changes
I have tested and the test is passed.

2020-11-15 14:03 UTC, merged