Market Fee - fix
opentibiabr/otservbr-global-archived pull request #1937
Opened 2020-11-03 06:56 UTC by HeberPcL

https://www.tibiawiki.com.br/wiki/Mercado
"É cobrada uma taxa para cada oferta que você mandar: 1% do preço total, mas com o mínimo de 20 gps e máximo de 100 000 gps (100k)."

2020-11-03 15:42 UTC, debone requested changes
Reconsider the code. Maybe try to use std::min/max

2020-11-03 22:49 UTC, debone commented on src/game.cpp
> +	uint32_t calcFee = (price / 100.) * amount;
I think we need 64bits here... what happens if you try to sell a full BP of mana potions for 1kk each?

2020-11-03 23:11 UTC, HeberPcL commented on src/game.cpp
> +	uint32_t calcFee = (price / 100.) * amount;
True, I changed

2020-11-05 20:30 UTC, debone approved these changes

2020-11-05 20:41 UTC, merged