Stop server boot prompt
opentibiabr/otservbr-global-archived pull request #1944
Opened 2020-11-07 23:28 UTC by IgorCFG

## Description (eng)
If the initialization of a bug the `system("pause")` will make the prompt wait for a key to close.
For me is useful, because I didn’t know what was causing the prompt to close as there wasn’t even time to see what was on it.

## Descrição (ptBr)
Se a inicialização do servidor tiver algum bug, o `system("pause")` irá fazer com que o prompt espere uma tecla para ser finalizado.
Pra mim é útil, porque eu não sabia o que estava causando o fechamento dele na inicialização, já que nem dava tempo de ler.

2020-11-08 14:58 UTC, debone commented
Thanks for your contribution @IgorCFG :) I can see how the idea of not exiting immediately after an error could benefit the users with less experience in debugging. It's common for these users to report issues and be helpless as "the window close too fast to know".

I didn't know about system calls and I did a short research on it. It seems that [system pause is Windows specific and not recommended practice](https://stackoverflow.com/questions/1107705/systempause-why-is-it-wrong). On the answers there are some suggestions to use the stdin to emulate such pause and wait for a enter press. I think it would be a nice way to introduce it instead of the system pause. 

Also, can you include a message before to let the user now that the server is going to terminate after enter press, due an unhandled error?

2020-11-08 14:59 UTC, debone requested changes
(I have added a comment earlier)

2020-11-08 22:12 UTC, IgorCFG commented
> I didn't know about system calls and I did a short research on it.

Nice research!
I had done it with `getchar` but I think I ended up putting it in the wrong place (since it didn't work).
I read the comments and I found it interesting the part where you say that the `system("pause")` ends up being dependent on a file called "pause" and can also cause problems if for some reason you have a file with that name. 
Interesting, I'll make the adjustments.

Thanks!

2020-11-09 00:07 UTC, IgorCFG commented
@debone look the last commit there b8bb0f5

And also added color in the error message on `startupErrorMessage` method. 😎

**Print**
![image](https://user-images.githubusercontent.com/35529239/98488184-71d71000-2206-11eb-83eb-08d589d2b9b7.png)

2020-11-09 16:28 UTC, debone commented on src/otserv.cpp
> +  std::cout << ">> The program WILL CLOSE after receiving a key..." << "\033[0m" << std::endl;
Maybe?
```suggestion
  std::cout << ">> Due an error, the program will close after pressing the enter key..." << "\033[0m" << std::endl;
```

2020-11-09 17:02 UTC, IgorCFG commented on src/otserv.cpp
> +  std::cout << ">> The program WILL CLOSE after receiving a key..." << "\033[0m" << std::endl;
In some cases more than one error message already appears.
I don’t need that many "there was an error", it ends up being redundant. 🤔

But the `receiveing a` for `pressing the enter` I liked it!
I thought it would close after any key's pressed 🤔

2020-11-09 17:08 UTC, debone commented on src/otserv.cpp
> +  std::cout << ">> The program WILL CLOSE after receiving a key..." << "\033[0m" << std::endl;
Will it repeat with the addition of `exit(-1)` ?

2020-11-09 17:12 UTC, debone approved these changes
Looks good now :) Keep in mind that your first commit looks like it was made with a work email. If you are ok with that, LGTM.

2020-11-09 18:24 UTC, merged