Fix exit Nightmare Isle
opentibiabr/otservbr-global-archived pull request #1987
Opened 2020-11-17 17:33 UTC by dex-89

**Exit tp doesn't work. I fixed it. Now works correctly**

2020-11-17 18:44 UTC, yatozin commented
Tested working perfectly

2020-11-18 17:11 UTC, dudantas requested changes

2020-11-18 17:11 UTC, dudantas commented on data/scripts/movements/quests/nightmare_isles/teleport.lua
> +function teleportexit.onStepIn(creature, item, position, fromPosition)
You duplicated the script, being able to just add the functions within what already exists. It can be like this:

```lua
local setting = {
	{storage = 210001, teleportPosition = Position(33032, 32400, 7)}, -- entrance teleport Darashia Northwest
	{storage = 210002, teleportPosition = Position(33215, 32273, 7)}, -- entrance teleport Darashia North
	{storage = 210016, teleportPosition = Position(33255, 32678, 7)} -- {x = 33255, y = 32678, z = 7}
}

local teleports = {
	[64001] = 210001, -- northwest Darashia
	[64002] = 210002, -- north Darashia
	[64003] = 210016  -- north Ankrahmun
}

local teleport = MoveEvent()

function teleport.onStepIn(creature, item, position, fromPosition)
	local player = creature:getPlayer()
	if not player then
		return
	end

	for i = 1, #setting do
		local table = setting[i]
		local backStorage = table.storage

		if player:getStorageValue(backStorage) >= 1 then
			player:teleportTo(table.teleportPosition)
			fromPosition:sendMagicEffect(CONST_ME_TELEPORT)
			player:setStorageValue(backStorage, 0)
			break
		end

		local posStorage = table.teleportPosition
		if player:getStorageValue(backStorage) == 1 then
			backStor = backStorage
			backPos = posStorage
		end
	end

	if backPos then
		player:teleportTo(backPos)
		fromPosition:sendMagicEffect(CONST_ME_TELEPORT)
		player:setStorageValue(backStor, -1)
	end

	local storagePortal = teleports[item.uid]
	if storagePortal then
		local entracePosition = Position(33497, 32616, 8)
		player:teleportTo(entracePosition)
		fromPosition:sendMagicEffect(CONST_ME_TELEPORT)
		player:setStorageValue(storagePortal, 1)
	end

	return true
end

teleport:type("stepin")

for index, value in pairs(teleports) do
	teleport:uid(index)
end

teleport:position({x= 33498, y = 32613, z = 8})
teleport:register()
```

2020-11-19 15:45 UTC, dex-89 commented on data/scripts/movements/quests/nightmare_isles/teleport.lua
> +function teleportexit.onStepIn(creature, item, position, fromPosition)
@dudantas 
after changing to your script:

![image](https://user-images.githubusercontent.com/67392692/99688569-41a13400-2a86-11eb-9610-8de0c7ffaa66.png)
![image](https://user-images.githubusercontent.com/67392692/99688688-60072f80-2a86-11eb-879b-e436467d8529.png)

i think that must be declaration for example: `teleportexit:aid(9725)`

2020-11-26 21:58 UTC, dudantas commented
Closing, solved this in the pr #2012
Thank you

2020-11-26 21:58 UTC, closed without merging