Rework login.lua and added other features
opentibiabr/otservbr-global-archived pull request #2025
Opened 2020-11-28 12:50 UTC by dex-89

- [X] **Fixed login message**
- - [X] Welcome message added
- - [X] Outfit selection added on first login
- [X] **Adventurers blessings added**
- [X] **Premium account fixed**
- - [X] Display of days of Premium Account on the console
- - [X] Premium Account ends: Teleport to Temple, change addon (citizen) houseless
- [X] **Recruiter system**
How it's working? You need to change the "recruiter" in the database...
The administrator decides what causes the update of this value
- [X] **Moved sendTibiaTime to cpp**
- [X] **Kick other players from account: only one player per account**
if set `onePlayerOnlinePerAccount` as `true`

2020-11-28 17:30 UTC, dudantas commented on data/scripts/creaturescripts/others/login.lua
> +local function antipz(p)
I think we can rename this function to make it more readable.
Example:
antiProtectionZone
kickFromPz or kickFromProtectionZone

It's up to you

2020-11-28 17:38 UTC, dudantas commented on data/scripts/creaturescripts/others/login.lua
> +		loginStr = loginStr .. " Please choose your outfit."
This part of the login is incorrect. The server was adapted to start at dawnport and does not start with this option.

2020-11-28 17:40 UTC, dudantas requested changes
I made two observations, if you can analyze...

2020-11-28 17:44 UTC, dex-89 commented
> I made two observations, if you can analyze...

Fixed all 👍

2020-11-29 09:04 UTC, MajestyOTBR commented
@dudantas PR waiting for your review.

2020-11-30 00:58 UTC, debone commented on data/scripts/creaturescripts/others/login.lua
> +		player:setStorageValue(998899,1)
What is this number `998899` ?

2020-11-30 00:58 UTC, debone commented on data/scripts/creaturescripts/others/login.lua
> +	-- Recruiter system
What is "Recruiter system"?

2020-11-30 00:58 UTC, debone commented on src/protocolgame.cpp
> +	writeToOutputBuffer(msg);
What does this package do?

2020-11-30 00:58 UTC, debone commented on data/scripts/creaturescripts/others/login.lua
> +	-- kick other players from account
Don't we block players from logging in if anyone on the account is online? That's how it works on global.

2020-11-30 00:58 UTC, debone commented on data/scripts/creaturescripts/others/login.lua
> +        end
Tabs got messy from on here

2020-11-30 00:58 UTC, debone commented on data/scripts/creaturescripts/others/login.lua
> +local function ProtectionZoneCheck(p)
Maybe give this function another name? Why not call doRemoveCreature directly?

2020-11-30 00:58 UTC, debone commented on data/scripts/creaturescripts/others/login.lua
> +        if home ~= nil and not isPremium(player) then
Is premium time deducted by players? I mean, if it depends on the player to login to kick them out of the house, what happens if they pay the rent, lose the premium and don't login?

2020-11-30 15:18 UTC, dex-89 commented on data/scripts/creaturescripts/others/login.lua
> +		player:setStorageValue(998899,1)
his is the storage to check whether the player has a premium account or not. If not - moved to temple (other function: - Premium Ends Teleport to Temple, change addon (citizen) houseless)

2020-11-30 15:18 UTC, dex-89 commented on data/scripts/creaturescripts/others/login.lua
> +	-- Recruiter system
https://tibia.fandom.com/wiki/Recruiter_Outfits

2020-11-30 15:21 UTC, dex-89 commented on src/protocolgame.cpp
> +	writeToOutputBuffer(msg);
https://github.com/opentibiabr/otservbr-global/blob/develop/data/scripts/creaturescripts/others/login.lua

```
function Player.sendTibiaTime(self, hours, minutes)
	-- TODO: Migrate to protocolgame.cpp
	local msg = NetworkMessage()
	msg:addByte(0xEF)
	msg:addByte(hours)
	msg:addByte(minutes)
	msg:sendToPlayer(self)
	msg:delete()
	return true
end
```
so i moved it to protocolgame.cpp

2020-11-30 15:23 UTC, dex-89 commented on data/scripts/creaturescripts/others/login.lua
> +	-- kick other players from account
If you have another idea - let's go! :) That system works correctly but without it you can login with multiclient without errors

2020-11-30 15:28 UTC, dex-89 commented on data/scripts/creaturescripts/others/login.lua
> +        if home ~= nil and not isPremium(player) then
You have an example to do a check :)

2020-11-30 16:37 UTC, dudantas approved these changes

2020-11-30 17:19 UTC, dudantas commented
> Fixed all 👍

Ok, thanks

2020-11-30 18:08 UTC, debone commented on src/protocolgame.cpp
> +	writeToOutputBuffer(msg);
Sure, but now every light tick we send an update to every player which I'm not sure if it's required

2020-11-30 18:08 UTC, debone commented on src/protocolgame.cpp
> +	writeToOutputBuffer(msg);
And we cannot move things without understanding why and what for.

2020-11-30 18:10 UTC, debone commented on data/scripts/creaturescripts/others/login.lua
> +	-- Recruiter system
TIL

Haha my arm got tired just from seeing that outfit's arm holding the flag a meter from the body

2020-11-30 18:12 UTC, debone commented on data/scripts/creaturescripts/others/login.lua
> +		player:setStorageValue(998899,1)
Are there no "isPremium" functions? If surprisingly not, can we declare this number in some centralized file?

2020-11-30 18:13 UTC, merged

2020-11-30 18:15 UTC, dex-89 commented on data/scripts/creaturescripts/others/login.lua
> +		player:setStorageValue(998899,1)
That's corrected. this is moved to storage.lua

2020-11-30 18:25 UTC, debone commented on data/scripts/creaturescripts/others/login.lua
> +		player:setStorageValue(998899,1)
Still, I think it's not necessary.