Move players to their temple
opentibiabr/otservbr-global-archived pull request #2051
Opened 2020-12-07 19:25 UTC by dex-89

**After the major update, move players to their temples**

save `data/update.lua` as `updated=true` to transfer all players to your temple after saving the server

2020-12-08 08:55 UTC, TheAncientDragon commented
> **After the major update, move players to their temples**
> 
> save `data/update.lua` as `updated=true` to transfer all players to your temple after saving the server

Hi, bit curious about this part.
If I put the server to save/clean floor/shutdown and restart every night it means that every night players will be sent to temple?

2020-12-08 10:35 UTC, dex-89 commented
> > **After the major update, move players to their temples**
> > save `data/update.lua` as `updated=true` to transfer all players to your temple after saving the server
> 
> Hi, bit curious about this part.
> If I put the server to save/clean floor/shutdown and restart every night it means that every night players will be sent to temple?

No. Players will be sent to temple only if `update.lua` is set as `updated=true`

2020-12-08 14:37 UTC, gpedro commented on data/scripts/globalevents/update.lua
> +		db.query("UPDATE `players` SET `posz` = 0;")
```
UPDATE `players` SET `posx` = 0, `posy` = 0, `posz` = 0;
```

2020-12-08 14:38 UTC, gpedro requested changes

2020-12-08 14:38 UTC, gpedro commented on data/scripts/globalevents/update.lua
> +		local updateFile = io.open('update.lua','r')
we can use migration instead globalevent, uhm? he already has this part to run once.

2020-12-08 14:39 UTC, gpedro commented on data/scripts/globalevents/update.lua
> +		local updateFile = io.open('update.lua','r')
example 
https://github.com/opentibiabr/otservbr-global/blob/develop/data/migrations/7.lua

2020-12-08 15:46 UTC, dex-89 commented on data/scripts/globalevents/update.lua
> +		db.query("UPDATE `players` SET `posz` = 0;")
I saw it yesterday, but I was sleepy and didn't have the strength to make changes

2020-12-08 15:48 UTC, dex-89 commented on data/scripts/globalevents/update.lua
> +		local updateFile = io.open('update.lua','r')
Yes, and then another, and another after each change to the server. Instead of changing one value `false` to `true`

2020-12-19 23:02 UTC, TheAncientDragon approved these changes
No errors, player sent to its temple after running the server with option set to true.

Suggestion.: make script set update=false after starting. To make sure none will forget to return the value back to false and having the system sending all players once again to the temple.

2020-12-20 07:00 UTC, dex-89 commented
> No errors, player sent to its temple after running the server with option set to true.
> 
> Suggestion.: make script set update=false after starting. To make sure none will forget to return the value back to false and having the system sending all players once again to the temple.

It turns `false` automatically

https://github.com/opentibiabr/otservbr-global/pull/2051/files#diff-c2540414a7eff07c8b49da81e1c7d053ef6b53572dfc78db16ccdb3ae503fa5fR11-R18

2020-12-20 09:40 UTC, TheAncientDragon commented
> > No errors, player sent to its temple after running the server with option set to true.
> > Suggestion.: make script set update=false after starting. To make sure none will forget to return the value back to false and having the system sending all players once again to the temple.
> 
> It turns `false` automatically
> 
> https://github.com/opentibiabr/otservbr-global/pull/2051/files#diff-c2540414a7eff07c8b49da81e1c7d053ef6b53572dfc78db16ccdb3ae503fa5fR11-R18

Hi, mine didnt. did restart server many times and it still set as true.
I had to set it to false manually.
Even know did another test run, 3 times.
Did change update=true and even after 3x restarting the server it was just like i left, =true.

2020-12-20 10:01 UTC, dex-89 commented
> > > No errors, player sent to its temple after running the server with option set to true.
> > > Suggestion.: make script set update=false after starting. To make sure none will forget to return the value back to false and having the system sending all players once again to the temple.
> > 
> > 
> > It turns `false` automatically
> > https://github.com/opentibiabr/otservbr-global/pull/2051/files#diff-c2540414a7eff07c8b49da81e1c7d053ef6b53572dfc78db16ccdb3ae503fa5fR11-R18
> 
> Hi, mine didnt. did restart server many times and it still set as true.
> I had to set it to false manually.
> Even know did another test run, 3 times.
> Did change update=true and even after 3x restarting the server it was just like i left, =true.

I need check it and make fix. Thank you for your contribution

2020-12-20 12:58 UTC, dex-89 commented
@TheAncientDragon, now it will be works. I tested

2020-12-20 15:24 UTC, TheAncientDragon reviewed
After the change it stopped working.
Player wont be sent to his/er temple also update=true isnt changing to false.

2020-12-20 15:24 UTC, TheAncientDragon commented on data/scripts/globalevents/update.lua
>  	end
there's a mising end here

2020-12-20 15:42 UTC, dex-89 commented on data/scripts/globalevents/update.lua
>  	end
For me works without problem.

2020-12-20 19:44 UTC, dex-89 commented on data/scripts/globalevents/update.lua
>  	end
![image](https://user-images.githubusercontent.com/67392692/102722813-fa67c680-4303-11eb-98ab-3f7a671670de.png)
![image](https://user-images.githubusercontent.com/67392692/102722831-1703fe80-4304-11eb-9359-9e9561169630.png)

2020-12-20 20:14 UTC, MajestyOTBR commented
Tested on WIndows - Worked.

2020-12-20 20:14 UTC, MajestyOTBR commented
Tested on Windows - Worked.

2020-12-29 00:53 UTC, MajestyOTBR approved these changes

2020-12-29 07:42 UTC, oualid6496 commented
Is the extra file ( data/update.lua ) really necessary?
Can't it just be configured in data/scripts/globalevents/update.lua

2020-12-29 07:45 UTC, dex-89 commented
> Is the extra file ( data/update.lua ) really necessary?
> Can't it just be configured in data/scripts/globalevents/update.lua

I can try move this to config.lua

2021-01-06 19:25 UTC, merged