Changable npc currency
opentibiabr/otservbr-global-archived pull request #2130
Opened 2020-12-23 00:06 UTC by dex-89

![image](https://user-images.githubusercontent.com/67392692/102944305-a8b56c80-44ba-11eb-85eb-9426188ad7a5.png)

#2117 **In global tibia Cledwyn work: hi -> token(s) -> silver -> trade window and sell for silver tokens**

Thanks for @FakeShinoda

2020-12-29 01:24 UTC, FakeShinoda commented on data/npc/scripts/cledwyn.lua
> +			return player:sendTextMessage(MESSAGE_INFO_DESCR, "You don't have enough "..currencyName..".")
You do not need to specify whether or not you have the currency, the purchase option will only be available if you have the currency in stock.

2020-12-29 01:25 UTC, FakeShinoda commented on data/npc/scripts/cledwyn.lua
> +				npcHandler:say("Sorry, friend, but one good turn deserves another. Bring enough tokens and it's a deal.", cid)
Same as above

2020-12-29 01:28 UTC, FakeShinoda requested changes

2020-12-29 01:28 UTC, FakeShinoda commented on src/npc.cpp
> +		currencyServerId = it.id;
Fix indentation

2020-12-29 01:28 UTC, FakeShinoda commented on src/npc.cpp
> +		currencyServerId = it.id;
Fix indentation

2020-12-29 07:52 UTC, dex-89 commented on data/npc/scripts/cledwyn.lua
> +			return player:sendTextMessage(MESSAGE_INFO_DESCR, "You don't have enough "..currencyName..".")
if amount > 1 then
     currencyName = ItemType(Npc():getCurrency()):getPluralName():lower()
else
     currencyName = ItemType(Npc():getCurrency()):getName():lower()
 end

plural name... 1 silver token, 2,3,... silver token**s**

2020-12-29 07:54 UTC, dex-89 commented on data/npc/scripts/cledwyn.lua
> +				npcHandler:say("Sorry, friend, but one good turn deserves another. Bring enough tokens and it's a deal.", cid)
I only fixed the indentation here

2020-12-29 21:31 UTC, FakeShinoda approved these changes

2021-01-02 18:46 UTC, MajestyOTBR approved these changes

2021-01-02 18:49 UTC, MajestyOTBR approved these changes

2021-01-03 23:31 UTC, MajestyOTBR approved these changes

2021-01-04 00:01 UTC, MajestyOTBR commented
Tested again, i found a small issue when i say `trade`, the npcs answer is: `Sorry, I'm not offering anything.`

Cledwyn should not answer anything for `trade.`
Yana should answer: `I have creature products for the imbuements strike, vampirism and void. Make your choice, please!`

2021-01-04 19:29 UTC, dex-89 commented
> Tested again, i found a small issue when i say `trade`, the npcs answer is: `Sorry, I'm not offering anything.`
> 
> Cledwyn should not answer anything for `trade.`
> Yana should answer: `I have creature products for the imbuements strike, vampirism and void. Make your choice, please!`

It was after merge PR #2231. Fixed

2021-01-04 19:44 UTC, MajestyOTBR approved these changes

2021-01-04 20:08 UTC, hyresu approved these changes

2021-01-04 20:44 UTC, merged

2021-01-05 15:35 UTC, dex-89 commented
> I found a bug
> 
> Missing to update "Stock" when buy/sell
> 
> https://prnt.sc/wgd5ju

Thank you for your information. I'll check it today and try fix mistake.