Couple HoD fixes and the right gem names when using gems on the wrong shrines
opentibiabr/otservbr-global-archived pull request #2240
Opened 2021-01-04 22:53 UTC by oualid6496

2021-01-05 03:50 UTC, gpedro requested changes

2021-01-05 03:50 UTC, gpedro commented on data/scripts/movements/quests/heart_of_destruction/vortex_crackler.lua
> +				storePlayers[#storePlayers + 1] = playerTile
why removed the condition? and if is a summon or monster?

2021-01-05 05:43 UTC, oualid6496 commented on data/scripts/movements/quests/heart_of_destruction/vortex_crackler.lua
> +				storePlayers[#storePlayers + 1] = playerTile
removed it because it already checks if it's a player on line 32~36

	local player = creature:getPlayer()
	if not player then
		return true
	end

2021-01-06 16:11 UTC, hyresu commented on data/scripts/movements/quests/heart_of_destruction/vortex_crackler.lua
> +				storePlayers[#storePlayers + 1] = playerTile
But the only creature checked is the player who step's in, if there's a monster on the other positions they'll be counted as players on that loop with that removal, are you sure that's how it works?

2021-01-08 15:04 UTC, oualid6496 commented on data/scripts/movements/quests/heart_of_destruction/vortex_crackler.lua
> +				storePlayers[#storePlayers + 1] = playerTile
@hyresu gonna test that out later today, but it shouldn't be counted since it's only being added when a creature is stepping in it right? Which shouldn't be happening anyway because of the first player check. Anyway im going to test this later today and revert it if it's indeed true

2021-01-08 20:58 UTC, oualid6496 commented on data/scripts/movements/quests/heart_of_destruction/vortex_crackler.lua
> +				storePlayers[#storePlayers + 1] = playerTile
@hyresu @gpedro Tested it out and monsters/npcs aren't being registered as it should. So the monsters aren't counted when they're on the other positions.

2021-01-12 00:54 UTC, marcosvf132 commented on data/scripts/movements/quests/heart_of_destruction/vortex_crackler.lua
> +				storePlayers[#storePlayers + 1] = playerTile
Some summons like the familiars can generate some problems in some cases, On my opinion i think it's better to have some extras safety checks if the playerTile really exist and if it is a player. You (and the old script) are using three external calls without any checks: positions2[i], Tile(positions2[i]) and Tile(positions2[i]):getTopCreature().

2021-01-13 22:26 UTC, dudantas requested changes

2021-01-13 22:26 UTC, dudantas commented on data/scripts/creaturescripts/quests/heart_of_destruction/charger_spawn.lua
> +local chargerSpawns = CreatureEvent("ChargerSpawn")
This change is not necessary, they are just variables
It also applies to the "cracklerTransforms"

2021-01-16 18:46 UTC, MajestyOTBR approved these changes

2021-01-17 10:40 UTC, dudantas approved these changes

2021-01-17 10:56 UTC, oualid6496 reviewed
By reverting this the Cracklers stop changing into Depolarized Cracklers

2021-01-17 10:56 UTC, oualid6496 commented on data/scripts/movements/quests/heart_of_destruction/vortex_crackler.lua
> +				storePlayers[#storePlayers + 1] = playerTile
reverted it in new commit

2021-01-17 10:56 UTC, oualid6496 commented on data/scripts/creaturescripts/quests/heart_of_destruction/charger_spawn.lua
> +local chargerSpawns = CreatureEvent("ChargerSpawn")
Well actually, I was testing the quest out and it was bugging the script until I changed them

2021-01-18 03:09 UTC, dudantas commented on data/scripts/creaturescripts/quests/heart_of_destruction/charger_spawn.lua
> +local chargerSpawns = CreatureEvent("ChargerSpawn")
> Well actually, I was testing the quest out and it was bugging the script until I changed them

I understood the error. I think there is something wrong with the code, and it is not changing the name of the global variable that this will solve, it just transfers the problem to another location.

2021-01-18 11:35 UTC, MajestyOTBR commented
So, add the fixes on #2292. Remember, when create a pull request you should use a branch based on develop and let develop untouched, to avoid conflicts.

2021-01-18 11:35 UTC, closed without merging