Several fixes for quests, npcs, items
opentibiabr/otservbr-global-archived pull request #2292
Opened 2021-01-17 16:09 UTC by oualid6496

- Added missing plurrals and loottypes for some items (mostly the 12.40 update items)

**Couple fixes and typo's for Heart of Destruction, Ferumbras Ascension, Cults of Tibia and Forgotten Knowledge quest.**
- Added some missing storages
- Fixed Rift Fragment not being convinceable
- Fixed some wrong creatureevent names
- Fixed wrong uid being used
- Fixed some wrong spawns

**Updated npcs**
- Added some of the new items to npcs Grizzly Adams, Yasir & Ruprecht.
- Added watermelon tourmalines & lion figurine to Briasol, Chantalle, Edmund, Gail, Hanna, Ishina, Iwan, Jessica, Odemara, Oiriz, Talila, Tesha, Tezila, Valindara, Yonan.
- Added quivers to Asnarus, Brengus, Cedrik, Dario, Edoch, Eliyas, Galuna, Gnomerrow, Irea, Maun, Mugruu, Perca, Robert, Rock in a Hard Place, Pompan, Silas, Taegen, Uzgod, Vincent, Willard, Xed.

2021-01-18 06:58 UTC, riesjuh666 approved these changes

2021-01-18 19:49 UTC, oualid6496 commented on data/scripts/creaturescripts/quests/heart_of_destruction/crackler_transform.lua
>  	if not creature or not creature:isMonster() then
@dudantas going further since other PR got closed. The thing is that it's interfering with the other "cracklerTransform" within the script. The script is not bugged, the name is just being used multiple times for other things.

2021-01-18 20:59 UTC, dudantas commented on data/scripts/creaturescripts/quests/heart_of_destruction/crackler_transform.lua
>  	if not creature or not creature:isMonster() then
> @dudantas going further since other PR got closed. The thing is that it's interfering with the other "cracklerTransform" within the script. The script is not bugged, the name is just being used multiple times for other things.

No ... I reviewed it and you didn't fix it. The name of the script variable does not interfere with anything. You have to change what is bugging and not the global variable of the script ...

2021-01-18 21:26 UTC, dudantas requested changes

2021-01-18 21:26 UTC, dudantas commented on data/monster/quests/ferumbras_ascendant/bosses/zamulosh3.lua
> +monster.description = "zamulosh"
It is capitalized, because it is a own name...

2021-01-18 21:26 UTC, dudantas commented on data/monster/quests/ferumbras_ascendant/bosses/zamulosh3.lua
>  monster.loot = {
You can remove all the structure of monster.loot (Since it is not used)

2021-01-18 21:26 UTC, dudantas commented on data/monster/quests/ferumbras_ascendant/bosses/zamulosh2.lua
>  monster.loot = {
You can remove all the structure of monster.loot (Since it is not used)

2021-01-18 21:26 UTC, dudantas commented on data/monster/quests/ferumbras_ascendant/summons/rift_fragment.lua
> +	convinceable = true,
You need set the "monster.manaCost = 50"
https://github.com/opentibiabr/otservbr-global/blob/31a603c303f87a091bdbcb1d660a9ef9195d5570/data/monster/quests/ferumbras_ascendant/summons/rift_fragment.lua#L15

2021-01-18 21:26 UTC, dudantas commented on data/scripts/actions/quests/ferumbras_ascendant/mazoran_lever.lua
> +		Game.setStorageValue(Storage.FerumbrasAscension.MazoranTimer, 1)
The previous changes are correct, this is not. It's the same question as the other pull request where you changed the variable... Here, you need to move the storage "MazoranTimer" into "GlobalStorage.FerumbrasAscendant" and not the other way around. All "Game.setStorage" storage is GlobalStorage

2021-01-18 21:26 UTC, dudantas commented on data/scripts/actions/quests/ferumbras_ascendant/mazoran_lever.lua
> +		addEvent(clearForgotten, 30 * 60 * 1000, Position(33572, 32679, 14), Position(33599, 32701, 14), Position(33319, 32318, 13), Storage.FerumbrasAscension.MazoranTimer)
Same as above.

2021-01-18 21:26 UTC, dudantas commented on data/scripts/actions/quests/ferumbras_ascendant/plagirath_lever.lua
> +		Game.setStorageValue(Storage.FerumbrasAscension.PlagirathTimer, 1)
Same as above.

2021-01-18 21:26 UTC, dudantas commented on data/scripts/actions/quests/ferumbras_ascendant/ragiaz_lever.lua
> +		Game.setStorageValue(Storage.FerumbrasAscension.RagiazTimer, 1)
Same as above.

2021-01-18 21:26 UTC, dudantas commented on data/scripts/actions/quests/ferumbras_ascendant/shulgrax_lever.lua
> +		Game.setStorageValue(Storage.FerumbrasAscension.ShulgraxTimer, 1)
Same as above.

2021-01-18 21:26 UTC, dudantas commented on data/scripts/actions/quests/ferumbras_ascendant/zamulosh_lever.lua
> +		Game.setStorageValue(Storage.FerumbrasAscension.ZamuloshTimer, 1)
Same as above.

2021-01-18 21:26 UTC, dudantas commented on data/scripts/creaturescripts/quests/ferumbras_ascendant/the_shatterer_kill.lua
> +	Game.setStorageValue(Storage.FerumbrasAscension.TheShattererTimer, 0)
Same as above.

2021-01-18 21:26 UTC, dudantas commented on data/scripts/creaturescripts/quests/heart_of_destruction/crackler_transform.lua
> +local cracklerTransforms = CreatureEvent("CracklerTransform")
Let me explain... You need to change this: https://github.com/opentibiabr/otservbr-global/blob/31a603c303f87a091bdbcb1d660a9ef9195d5570/data/scripts/creaturescripts/quests/heart_of_destruction/crackler_transform.lua#L7
If you change the main variable of the script, you are just "transferring the error" to another location. It is also good to check where this "cracklerTransform == true" function comes from. Well, I didn't find where it is defined in the script outline.

2021-01-18 21:26 UTC, dudantas commented on data/scripts/movements/quests/cults_of_tibia/ice.lua
> +function sendConditionCultsIce(playerid, info, fromPos, toPos, fromPos2, toPos2, time)
Here is basically the same thing as the previous one. You changing the name unnecessarily. Just put "local function" to become a local function (so it cannot be pulled in another script), it is good to also change the tar script to local function.

https://github.com/opentibiabr/otservbr-global/blob/31a603c303f87a091bdbcb1d660a9ef9195d5570/data/scripts/movements/quests/cults_of_tibia/tar.lua#L49

2021-01-18 21:26 UTC, dudantas commented on data/scripts/movements/quests/heart_of_destruction/teleport_heart.lua
> +teleportHeart:register()
Could you add the empty line at the end of the script?

2021-01-18 21:26 UTC, dudantas commented on data/spells/scripts/monster/outburst explode.lua
> -	transferBossPoints(from, monster:getId())
What is the reason for the removal?

2021-01-18 22:00 UTC, oualid6496 commented
@dudantas thx for the feedback gonna make the changes tomorrow that you've requested

2021-01-18 22:01 UTC, oualid6496 commented on data/spells/scripts/monster/outburst explode.lua
> -	transferBossPoints(from, monster:getId())
I added it also in the description of the commit that I couldn't find where this was defined, I assumed that this is an old function that was never removed? Correct me if I'm wrong.

2021-01-18 22:04 UTC, oualid6496 commented on data/monster/quests/ferumbras_ascendant/bosses/zamulosh3.lua
> +monster.description = "zamulosh"
My bad was pretty certain that didn't count for the description of the monsters, gonna change this tomorrow

2021-01-18 22:18 UTC, dudantas commented
> @dudantas thx for the feedback gonna make the changes tomorrow that you've requested

Ok. And congratulations, many useful changes. It is very welcome!

2021-01-19 23:07 UTC, oualid6496 commented on data/scripts/movements/quests/heart_of_destruction/teleport_heart.lua
> +teleportHeart:register()
commit a86c7d2180ef71a487f71aa71e60b43a62b7800a

2021-01-19 23:07 UTC, oualid6496 commented on data/monster/quests/ferumbras_ascendant/summons/rift_fragment.lua
> +	convinceable = true,
Fixed in commit a86c7d2180ef71a487f71aa71e60b43a62b7800a

2021-01-19 23:08 UTC, oualid6496 commented on data/monster/quests/ferumbras_ascendant/bosses/zamulosh2.lua
>  monster.loot = {
Fixed in commit a86c7d2180ef71a487f71aa71e60b43a62b7800a

2021-01-19 23:08 UTC, oualid6496 commented on data/monster/quests/ferumbras_ascendant/bosses/zamulosh3.lua
>  monster.loot = {
Fixed in commit a86c7d2180ef71a487f71aa71e60b43a62b7800a

2021-01-19 23:08 UTC, oualid6496 commented on data/monster/quests/ferumbras_ascendant/bosses/zamulosh3.lua
> +monster.description = "zamulosh"
Fixed in commit a86c7d2180ef71a487f71aa71e60b43a62b7800a

2021-01-19 23:08 UTC, oualid6496 commented on data/scripts/actions/quests/ferumbras_ascendant/mazoran_lever.lua
> +		Game.setStorageValue(Storage.FerumbrasAscension.MazoranTimer, 1)
Fixed in commit 2681ad18f80abfc4b76f2aadafb8c889d4b1ffa5

2021-01-19 23:09 UTC, oualid6496 commented on data/scripts/creaturescripts/quests/ferumbras_ascendant/the_shatterer_kill.lua
> +	Game.setStorageValue(Storage.FerumbrasAscension.TheShattererTimer, 0)
Fixed in commit 2681ad18f80abfc4b76f2aadafb8c889d4b1ffa5

2021-01-19 23:09 UTC, oualid6496 commented on data/scripts/actions/quests/ferumbras_ascendant/mazoran_lever.lua
> +		addEvent(clearForgotten, 30 * 60 * 1000, Position(33572, 32679, 14), Position(33599, 32701, 14), Position(33319, 32318, 13), Storage.FerumbrasAscension.MazoranTimer)
Fixed in commit 2681ad18f80abfc4b76f2aadafb8c889d4b1ffa5

2021-01-19 23:09 UTC, oualid6496 commented on data/scripts/actions/quests/ferumbras_ascendant/plagirath_lever.lua
> +		Game.setStorageValue(Storage.FerumbrasAscension.PlagirathTimer, 1)
Fixed in commit 2681ad18f80abfc4b76f2aadafb8c889d4b1ffa5

2021-01-19 23:09 UTC, oualid6496 commented on data/scripts/actions/quests/ferumbras_ascendant/ragiaz_lever.lua
> +		Game.setStorageValue(Storage.FerumbrasAscension.RagiazTimer, 1)
Fixed in commit 2681ad18f80abfc4b76f2aadafb8c889d4b1ffa5

2021-01-19 23:09 UTC, oualid6496 commented on data/scripts/actions/quests/ferumbras_ascendant/shulgrax_lever.lua
> +		Game.setStorageValue(Storage.FerumbrasAscension.ShulgraxTimer, 1)
Fixed in commit 2681ad18f80abfc4b76f2aadafb8c889d4b1ffa5

2021-01-19 23:09 UTC, oualid6496 commented on data/scripts/actions/quests/ferumbras_ascendant/zamulosh_lever.lua
> +		Game.setStorageValue(Storage.FerumbrasAscension.ZamuloshTimer, 1)
Fixed in commit 2681ad18f80abfc4b76f2aadafb8c889d4b1ffa5

2021-01-24 18:56 UTC, dex-89 commented
Thank you for your contribution. Some advice:

1. One PR - One quest -> it's better to check
2. Try **understand** script before make PR
3. Do nothing for the quantity but wisely - we need check this!

2021-01-24 18:56 UTC, closed without merging