Fix cobra bastion: exit scarlett -> teleport position
opentibiabr/otservbr-global-archived pull request #2295
Opened 2021-01-18 16:30 UTC by dex-89

Fix exit teleport position (Cobra bastion: Scarlet) to 33395, 32670, 6

2021-01-24 15:40 UTC, marduq approved these changes

2021-02-10 23:43 UTC, MajestyOTBR approved these changes

2021-02-11 03:07 UTC, dudantas requested changes

2021-02-11 03:07 UTC, dudantas commented on data/lib/core/storages.lua
> +		Mission05 = 56399,
56395?

2021-02-11 03:07 UTC, dudantas commented on data/scripts/actions/quests/the_thieves_guild/fish_napping_key.lua
> +			player:teleportTo(Position(32359, 32788, 6))
Add return true

2021-02-11 03:07 UTC, dudantas commented on data/scripts/actions/quests/the_thieves_guild/fish_napping_key.lua
>  	return true
Change to return false

2021-02-11 18:10 UTC, merged