Dawnport vocations extinction and other dawnport fixes
opentibiabr/otservbr-global-archived pull request #2297
Opened 2021-01-19 20:57 UTC by ElTeixe

Removed dawnport vocations
-
- Its only purpose its handle the stats (hp/mana/cap) gain/loss for vocations with level <= 8.
- Its handled on source with 2 simple 'if' and avoids the headache trying to handle them switching between dawnport and main vocations and vice versa, between other stuffs.
- It was removed or adjusted everything related to dawnport vocations.

Vocations trial
-
- Fixed only removing x2 of each previous trial equipments when switching vocation.
- Fixed error when trying move into backpack an equipped item when there is no backpack.
- Added magic level and skill level conversion between vocations.
- Added quiver to paladin trial, adding simple arrows inside.

Vocations door
-
- Reworked and corrected the items removed on pass through the door.
- Added missing message on pass through the door.

Vocations reward
-
- Corrected some reward items.
- Added missing Adventurers Guild parchment.
- Added check of enough capacity and enough slots before able to take the reward.
- Added quiver to paladin rewards.

Dawnport tiles
-
- Added missing cure poison MoveEvent for dawnport outpost entrances tiles.
- Fixed vocations chest room exits and added missing message.

NPCs
-
Oressa:
- Added magic level and skill level conversion between vocations on choose final vocation.
- Reworked and corrected the items removed on choose vocation.

Inigo:
- Added condition of level <= 9 to ask about to go Rookgaard.
- Added magic level and skill level conversion to none vocation on go to Rookgaard.

Captain Dreadnought:
- Added missing transcripts.
- Added default town travel.
- Corrected teleport to town boat positions instead of town temple positions.
- Added force to drop or donate the excess of 500 gold coins before to sail a town.
- Customizable just editing towns table.

Other
-
Dawnport skill limit:
- Added skill limit to dawnport residents. Notifies about and limit it when reached.
- By default only limits magic level like Official (Sorcerer/Druid 20, Paladin 9 and Knight 4). Can be customized to another skills.

New Lua scripting functions:
- player:setMagicLevel(level[, manaSpent])
- player:setSkillLevel(skillType, level[, tries])

And other small edits like removed variables not in use, moved variables/functions from global to local, etc, etc that Im not gonna name them all.

2021-01-20 03:21 UTC, marcosvf132 commented
Fix #2299

2021-01-22 15:44 UTC, dex-89 requested changes
It looks like everything is fine. If you could improve the review I would be very grateful: unnecessary spaces and line length.

Besides - great job

2021-01-22 16:44 UTC, ElTeixe commented
> It looks like everything is fine. If you could improve the review I would be very grateful: unnecessary spaces and line length.
> 
> Besides - great job

- About unnecessary spaces, you mean empty line jumps between 'ifs' and variables?
- About the lines length, I guessed that gonna be a complain, since I seen that practice at other scripts. I had that discussion many times at the job too, about how length must be.. 125 if I dont remember wrong its small IMHO, I dont like have half width screen empty hahah but I can adapt myself.

Confirm about, and I'll try correct it.

2021-01-22 16:48 UTC, dex-89 commented
> > It looks like everything is fine. If you could improve the review I would be very grateful: unnecessary spaces and line length.
> > Besides - great job
> 
> * About unnecessary spaces, you mean empty line jumps between 'ifs' and variables?
> * About the lines length, I guessed that gonna be a complain, since I seen that practice at other scripts. I had that discussion many times at the job too, about how length must be.. 125 if I dont remember wrong its small IMHO, I dont like have half width screen empty hahah but I can adapt myself.
> 
> Confirm about, and I'll try correct it.

All files to fix:
https://github.com/opentibiabr/otservbr-global/pull/2297/checks?check_run_id=1749599333

unnecessary spaces: `line contains only whitespace`
`data/events/scripts/player.lua:770:1: line contains only whitespace`

line lenght: `line is too long (140 > 120)`
`data/lib/others/dawnport_lib.lua:118:121: line is too long (122 > 120)`

2021-01-22 18:17 UTC, slawkens commented on src/luascript.cpp
> +  registerMethod("Player", "setMagicLevel", LuaScriptInterface::luaPlayerSetMagicLevel);
Use tabs instead of two spaces :P

2021-01-22 18:29 UTC, ElTeixe commented on src/luascript.cpp
> +  registerMethod("Player", "setMagicLevel", LuaScriptInterface::luaPlayerSetMagicLevel);
I got noticed after commit the code, in my VS it looks, right. I dont know why VS dont follow the same spacing/tabs defined on the file  instead used of another... I try correct that too.

2021-01-22 18:46 UTC, dex-89 commented on src/luascript.cpp
> +  registerMethod("Player", "setMagicLevel", LuaScriptInterface::luaPlayerSetMagicLevel);
Try to use Notepad++ to edit and add in it:
![image](https://user-images.githubusercontent.com/67392692/105532041-8cd7fd00-5cea-11eb-8a50-b7ddfc9700c8.png)

2021-01-23 13:43 UTC, dex-89 approved these changes

2021-01-23 13:48 UTC, MajestyOTBR approved these changes

2021-01-23 15:43 UTC, merged