Fix loadLuaMapBook function
opentibiabr/otservbr-global-archived pull request #2309
Opened 2021-01-23 05:53 UTC by ElTeixe

Fixes the loadLuaMapBook function not working properly. Is generating containers on the map when book item need to be generated at a map position and when the book item need to be in a container it isnt generated inside. Only works on existing already on map items.

- Fixed the issues, now generate new book items at map and inside containers, and still working on existing map items.
- Moved the loading console message inside the function.
- Merged the BookTable and DocumentTable. IMHO they are like the same, items that can be on map or inside a container that when are used they show a window with a readable text.
- Renamed function name and some changes on table variables.

NOTE: Although it said before there are 60 books and 2 documents, some books dont have position, so arent useable there are like 35, plus 2 documents. 37 now.

Now:
![1](https://user-images.githubusercontent.com/31188201/105569727-71014500-5d44-11eb-8afb-99059ef03052.png)
![2](https://user-images.githubusercontent.com/31188201/105569730-7494cc00-5d44-11eb-90a3-200335998267.png)

Fixed:
![3](https://user-images.githubusercontent.com/31188201/105569744-9c842f80-5d44-11eb-9441-549328ce617e.png)
![4](https://user-images.githubusercontent.com/31188201/105569745-a017b680-5d44-11eb-9281-94ea9df6945b.png)

2021-01-23 08:47 UTC, dex-89 requested changes

2021-01-23 08:47 UTC, dex-89 commented on data/startup/others/functions.lua
> +			goto skip
Not better: (if position exist - read without skip and Github warnings: `luac: data/startup/others/functions.lua:95: '=' expected near 'skip'`)
```
if value.position then
			totals[1] = totals[1] + 1
			local tile = Tile(value.position)
			-- Check if is a valid tile
			if tile then
				local item
				-- Check if is a contained item
				if value.containerId then
					-- Try find the container on the map
					local container = tile:getItemById(value.containerId)
					if not container then
						print(string.format("> loadLuaMapBookDocument container not found! index: %d, containerId: %d", index, value.containerId))
					end
					-- Create the item inside the container
					item = container:addItem(value.itemId, 1, INDEX_WHEREEVER, FLAG_NOLIMIT)
				else
					-- Try first find the item on the map (in some cases the item is already on the map)
					item = tile:getItemById(value.itemId)
					-- Create the item at map position
					if not item then
						item = Game.createItem(value.itemId, 1, value.position)
					end
				end
				-- If the item exists, add the text
				if item then
					item:setAttribute(ITEM_ATTRIBUTE_TEXT, value.text)
					totals[2] = totals[2] + 1
				else
					print(string.format("> loadLuaMapBookDocument item not found or created! index: %d, itemId: %d", index, value.itemId))
				end
			else
				print(string.format("> loadLuaMapBookDocument tile not found! index: %d, position: x=%d y=%d z=%d", index, value.position.x, value.position.y, value.position.z))
			end
		end
```

2021-01-23 08:47 UTC, dex-89 commented on data/startup/others/functions.lua
> +					print(string.format("> loadLuaMapBookDocument container not found! index: %d, containerId: %d", index, value.containerId))
Here you have the counter. This value cannot exceed 120
`data/startup/others/functions.lua:107:121: line is too long (127 > 120)`
we break the line where possible
![image](https://user-images.githubusercontent.com/67392692/105573682-92bbf580-5d5f-11eb-902a-52ca1b45fb2d.png)

2021-01-23 13:19 UTC, ElTeixe commented on data/startup/others/functions.lua
> +			goto skip
I guessed that way to skip on the loop dont goes be accepted lol, I will fix it.

2021-01-23 13:33 UTC, ElTeixe commented on data/startup/others/functions.lua
> +					print(string.format("> loadLuaMapBookDocument container not found! index: %d, containerId: %d", index, value.containerId))
About that totally right, that line lengths gonna to kill me.. lol I dont really have the habit to use that lower ones. I'll fix them.

2021-01-23 13:37 UTC, dex-89 commented on data/startup/others/functions.lua
> +					print(string.format("> loadLuaMapBookDocument container not found! index: %d, containerId: %d", index, value.containerId))
It's not most important.

2021-01-23 13:38 UTC, ElTeixe commented on data/startup/others/functions.lua
> +			goto skip
BUMP! I edited the reply, I'll make a newer one next time or may be confusing.

2021-01-23 13:39 UTC, dex-89 commented on data/startup/others/functions.lua
> +			goto skip
I understand. I think that @dudantas should comment

2021-01-23 20:28 UTC, dex-89 approved these changes

2021-01-26 19:39 UTC, MajestyOTBR approved these changes

2021-01-26 19:44 UTC, merged