Order of the Lion
opentibiabr/otservbr-global-archived pull request #2334
Opened 2021-01-30 12:40 UTC by hyresu

This contains the base for the order of the lion boss fights
We need TESTING and FEEDBACK for this, as its just a base right now, it may need some more adjustments, so feel free to tell me the bugs and things to improve.

The fight is as rl, the usurpers fight lions, as well lions vs usurper all around bounac.

TODO:

- [ ] Add boat to bounac
- [ ] Add action ids for everything added (in the map)
- [ ] Add spawns to bounac

Maybe I should move the "targetPreferPlayer" to a strategy on itself.

2021-02-15 21:42 UTC, dex-89 commented
@hyresu Look this: https://otland.net/threads/12-40-new-lion-sanctum-werelions-werelioness-with-spawn.271855/

2021-03-27 01:49 UTC, adrianomengue commented
@hyresu  

I tested your pull request and I have some issues to report.

1. Drume's corpse id is wrong.
2. Kesar's speed attribute is now = 0, should change to 250 or something.
3. After killing drume, I have waited something about 15-30 minutes inside of the boss pit and I was kicked out.
4. I tried to logout inside the boss pit and I got it, I guess it couldn't be done.


Hope you can fix it. Thanks ;-)

2021-03-27 01:54 UTC, adrianomengue requested changes
I tested your pull request and I have some issues to report.

1. Drume's corpse id is wrong.
3. After killing drume, I have waited something about 15-30 minutes inside of the boss pit and I was kicked out.
4. I tried to logout inside the boss pit and I got it, I guess it couldn't be done.
5. Duplicate storage value 
![storage](https://user-images.githubusercontent.com/19974082/112720777-4d42b280-8edf-11eb-8b35-f8eb78eb89b1.PNG)
![duplicated](https://user-images.githubusercontent.com/19974082/112720778-4ddb4900-8edf-11eb-8236-80e6beffce89.PNG)
6. You can calk through Lion Knight
    **Possible fix method:** isPet attribute on Lion Knight is true, change it to false maybe.
7. Comparing the respawn location with global version, they are too separeted from each other, I guess it was supposed to have the whole 3 groups fighting at same time in the screen


Hope you can fix it. Thanks ;-)

2021-03-27 19:11 UTC, adrianomengue commented
> I tested your pull request and I have some issues to report.
> 
> 1. Drume's corpse id is wrong.
> 2. Kesar's speed attribute is now = 0, should change to 250 or something.
> 3. After killing drume, I have waited something about 15-30 minutes inside of the boss pit and I was kicked out.
> 4. I tried to logout inside the boss pit and I got it, I guess it couldn't be done.
> 5. Duplicate storage value
>    ![storage](https://user-images.githubusercontent.com/19974082/112720777-4d42b280-8edf-11eb-8b35-f8eb78eb89b1.PNG)
>    ![duplicated](https://user-images.githubusercontent.com/19974082/112720778-4ddb4900-8edf-11eb-8236-80e6beffce89.PNG)
> 6. You can calk through Lion Knight
>    **Possible fix method:** isPet attribute on Lion Knight is true, change it to false maybe.
> 7. Comparing the respawn location with global version, they are too separeted from each other, I guess it was supposed to have the whole 3 groups fighting at same time in the screen
> 
> Hope you can fix it. Thanks ;-)


### Fixes:
**2.** Change Speed attribute to 250.
**3. and 7.**  **_(data\scripts\quests\the_order_of_lion\drume.lua)_**
```lua
local config = {
	lionPosition = {
		Position(32444, 32512, 7),
		Position(32449, 32516, 7),
		Position(32444, 32520, 7),
	},
	usurperPosition = {
		Position(32450, 32520, 7),
		Position(32444, 32516, 7),
		Position(32448, 32512, 7)
	},
	firstPlayerPosition = Position(32457, 32508, 6),
    centerPosition = Position(32439, 32523, 7), -- Center Room  
	exitPosition = Position(32453, 32503, 7), -- Exit Position
	newPosition = Position(32453, 32510, 7),
	rangeX = 22,
	rangeY = 16,
	timeToKill = 5, -- time in minutes to remove the player	
}	

local function RoomIsOccupied(centerPosition, rangeX, rangeY)
	local spectators = Game.getSpectators(config.centerPosition, false, true, config.rangeX, config.rangeX, config.rangeY, config.rangeY)
	if #spectators ~= 0 then
		return true
	end

	return false
end


local function clearRoomDrume(centerPosition, rangeX, rangeY, resetGlobalStorage)
	local spectators,
	spectator = Game.getSpectators(centerPosition, false, false, rangeX, rangeX, rangeY, rangeY)
	for i = 1, #spectators do
		spectator = spectators[i]
		if spectator:isMonster() then
			spectator:remove()
		end
		if spectator:isPlayer() then
			spectator:teleportTo(config.exitPosition)
			spectator:sendTextMessage(MESSAGE_EVENT_ADVANCE, "Your time is over.")
		end
	end
	if Game.getStorageValue(resetGlobalStorage) == 1 then
		Game.setStorageValue(resetGlobalStorage, -1)
	end
end

local drumeAction = Action()
function drumeAction.onUse(player, item, fromPosition, target, toPosition, isHotkey)
	if player:getPosition() ~= config.firstPlayerPosition then return false end
	if RoomIsOccupied(config.centerPosition, config.rangeX, config.rangeY) then
		player:sendCancelMessage("There's someone already in the skirmish.")
		player:getPosition():sendMagicEffect(CONST_ME_POFF)
		return true
	end
	local tempPos, tempTile, tempCreature
	local players = {}
	for x = config.firstPlayerPosition.x, config.firstPlayerPosition.x + 4 do
		tempPos = Position(x, config.firstPlayerPosition.y, config.firstPlayerPosition.z)
		tempTile = Tile(tempPos)
		if tempTile then
			tempCreature = tempTile:getTopCreature()
			if tempCreature and tempCreature:isPlayer() then
				table.insert(players, tempCreature)
			end
		end
	end
	if #players == 0 then return false end
	for _, pi in pairs(players) do
		if pi:getStorageValue(Storage.TheOrderOfTheLion.Drume.Timer) > os.time() then
			player:sendCancelMessage("Someone of your team has already fought in the skirmish in the last 20h.")
			player:getPosition():sendMagicEffect(CONST_ME_POFF)
			return true
		end
	end
	local spectators = Game.getSpectators(config.centerPosition, false, false, config.rangeX, config.rangeX, config.rangeY, config.rangeY)
	for _, creature in pairs(spectators) do
		if creature:isMonster() then
			creature:remove()
		end
	end
	local totalLion = 0
	local totalUsurper = 0
	local tempMonster
	for _, pos in pairs(config.lionPosition) do
		tempMonster = Game.createMonster("Lion Commander", pos)
		if not tempMonster then
			player:sendCancelMessage("There was an error, contact an admin.")
			player:getPosition():sendMagicEffect(CONST_ME_POFF)
			return true
		end
		totalLion = totalLion + 1
	end
	for _, pos in pairs(config.usurperPosition) do
		tempMonster = Game.createMonster("Usurper Commander", pos)
		if not tempMonster then
			player:sendCancelMessage("There was an error, contact an admin.")
			player:getPosition():sendMagicEffect(CONST_ME_POFF)
			return true
		end
		totalUsurper = totalUsurper + 1
	end
	for _, pi in pairs(players) do
		pi:setStorageValue(Storage.TheOrderOfTheLion.Drume.Timer, os.time() + (20 * 60 * 60))
		pi:teleportTo(config.newPosition)
		addEvent(clearRoomDrume, config.timeToKill * 60 * 1000, config.centerPosition, config.rangeX, config.rangeY, resetGlobalStorage)
		pi:sendTextMessage(MESSAGE_EVENT_ADVANCE, "You have " ..config.timeToKill.." minutes to defeat Drume.")
		
	end
	config.newPosition:sendMagicEffect(CONST_ME_TELEPORT)
	toPosition:sendMagicEffect(CONST_ME_POFF)
	Game.setStorageValue(Storage.TheOrderOfTheLion.Drume.TotalLionCommanders, totalLion)
	Game.setStorageValue(Storage.TheOrderOfTheLion.Drume.TotalUsurperCommanders, totalUsurper)
	return true
end
drumeAction:aid(59600)
drumeAction:register()
```
that's the new drume.lua fixed.

**4.** Just go to RME and cover the whole area with No Logout tile.
**6.** I changed the isPet attribute to false it seems to work well.


### Missing fixes:
1. CorpseID should be the same as Lion Knight's corpse, but I don't know how to duplicate it.
5. I'm not sure if I should change it, seems like they're intentionally the same.

Credits for who helped me: 
@dudantas

2021-03-27 21:13 UTC, adrianomengue commented
Just another issue that I saw after:

Set all KESAR'S RESISTANCE to 100. He's immunity and set canWalkOnEnergy = false in Drume's config ;-)

2021-04-17 16:20 UTC, lgrossi commented on src/combat.cpp
> +			if (attacker->getFaction() != FACTION_DEFAULT && attacker->getFaction() != FACTION_PLAYER && !attacker->getMonster()->isEnemyFaction(target->getFaction())) {
attacker->getMonster() can be null

2021-04-17 16:22 UTC, lgrossi approved these changes

2021-04-18 14:43 UTC, Costallat commented on src/combat.cpp
>  		} else if (target->getMonster()) {
```suggestion
		} else if (target && target->getMonster()) {
```

2021-04-18 14:43 UTC, Costallat commented on src/combat.cpp
> +			if (attacker->getFaction() != FACTION_DEFAULT && attacker->getFaction() != FACTION_PLAYER && !attacker->getMonster()->isEnemyFaction(target->getFaction())) {
```suggestion
			if (attacker->getFaction() != FACTION_DEFAULT && attacker->getFaction() != FACTION_PLAYER && attacker->getMonster() && !attacker->getMonster()->isEnemyFaction(target->getFaction())) {
```

2021-04-18 14:43 UTC, Costallat commented on src/monster.cpp
> +	} else if (creature->getPlayer() && creature->getPlayer()->hasFlag(PlayerFlag_IgnoredByMonsters)) {
```suggestion
	} else if (creature->getPlayer() &&  creature->getPlayer() && creature->getPlayer()->hasFlag(PlayerFlag_IgnoredByMonsters)) {
```

2021-05-12 12:12 UTC, dudantas approved these changes

2021-05-12 13:22 UTC, MajestyOTBR approved these changes

2021-05-13 01:18 UTC, merged