Fix monster waves
opentibiabr/otservbr-global-archived pull request #2366
Opened 2021-02-05 20:32 UTC by gerotib

Fixes monsters that should use their specific lua spells - mainly wrong spell areas.

2021-02-05 20:35 UTC, dex-89 commented on data/spells/scripts/monster/arachnophobica waveenergy.lua
> +combat:setParameter(COMBAT_PARAM_TYPE, COMBAT_ENERGYDAMAGE)
#2365 duplication

2021-02-05 21:18 UTC, hyresu commented on data/monster/magicals/guzzlemaw.lua
> +	{name ="combat", interval = 2000, chance = 10, type = COMBAT_PHYSICALDAMAGE, minDamage = 0, maxDamage = -900, length = 8, spread = 3, effect = CONST_ME_EXPLOSIONAREA, target = true},
Shouldn't this spell be a wave, which is not targeted?

2021-02-05 23:43 UTC, dex-89 requested changes

2021-02-05 23:43 UTC, dex-89 commented on data/spells/scripts/monster/arachnophobica waveenergy.lua
> +combat:setParameter(COMBAT_PARAM_TYPE, COMBAT_ENERGYDAMAGE)
#2365 duplication

2021-02-06 08:54 UTC, dex-89 commented on data/monster/bosses/kraknaknork.lua
> +	{name ="kraknaknork explosion wave", interval = 2000, chance = 10, minDamage = -1, maxDamage = -12, target = false},
@ElTeixe: you are working on rookgaard. Can you validate?

2021-02-06 18:47 UTC, gerotib commented on data/monster/bosses/kraknaknork.lua
> +	{name ="kraknaknork explosion wave", interval = 2000, chance = 10, minDamage = -1, maxDamage = -12, target = false},
I assume that thumb up confirmed it's valid

2021-02-06 18:52 UTC, dex-89 commented on data/monster/bosses/kraknaknork.lua
> +	{name ="kraknaknork explosion wave", interval = 2000, chance = 10, minDamage = -1, maxDamage = -12, target = false},
No, he let me know that he had read and wrote to me that if he got to this boss, he would check it.

2021-02-07 02:13 UTC, ElTeixe approved these changes

2021-02-07 02:13 UTC, ElTeixe commented on data/monster/bosses/kraknaknork.lua
> +	{name ="kraknaknork explosion wave", interval = 2000, chance = 10, minDamage = -1, maxDamage = -12, target = false},
Changes are right except "kraknaknork explosion wave" minDamage should be 0. But I can correct it later, I have to edit other Kraknaknork things.

2021-02-07 17:39 UTC, MajestyOTBR approved these changes

2021-02-07 17:42 UTC, dex-89 approved these changes

2021-02-07 17:43 UTC, merged