fix: correct editorconfig
opentibiabr/otservbr-global-archived pull request #2372
Opened 2021-02-07 00:35 UTC by wizardlink

Adjusts the [editorconfig](https://editorconfig.org/) to reflect the actual indentation style of the project.

2021-02-07 09:07 UTC, dex-89 approved these changes

2021-02-07 17:50 UTC, dudantas requested changes

2021-02-07 17:50 UTC, dudantas commented on .editorconfig
> +indent_style = tab
The correct is space (although almost all indentation is as a tab), because the tab bugs the indentation on github

2021-02-07 18:49 UTC, wizardlink commented on .editorconfig
> +indent_style = tab
Since when?

2021-02-07 18:56 UTC, dudantas commented on .editorconfig
> +indent_style = tab
Since when, what?

2021-02-07 19:11 UTC, wizardlink commented on .editorconfig
> +indent_style = tab
Since when does it _breaks on GitHub_?

You might be mistaking the showcasing of mixed indentation, if you have a line with space indentation and another with a tab, their width will be completely different.

However, that has never been an issue and you have the same behaviour in GitLab and Azure. It is not a GitHub problem.

The only fix for that is having a single indentation, not mixed.

2021-02-07 19:21 UTC, dudantas commented on .editorconfig
> +indent_style = tab
I didn't say it breaks, I said it bugs (visually).

2021-02-07 19:30 UTC, dudantas commented on .editorconfig
> +indent_style = tab
I can give you an example ... Open my PR # 2325, go to game.cpp, open the diff, search for:
```if (player->getPathTo(item->getPosition(), listDir, 0, 1, true, false)) {
			g_dispatcher().addTask(std::bind(&Game::playerAutoWalk,
											 this, player->getID(), listDir));```
This is with TAB, check that when using space, the indentation is correct
Tthe "this" should be just below the "& Game :: playerAutoWalk,"

2021-02-07 19:31 UTC, wizardlink commented on .editorconfig
> +indent_style = tab
And that falls exactly on what I said, mixed indentation. If the indentation of both lines were space, or tab, then this _issue_ would not occur.

2021-02-07 21:34 UTC, dudantas commented on .editorconfig
> +indent_style = tab
No. All indentation is done with the tab. The problem is that 1 tab is identified by only 1 character (when in fact there are 4) and github does not identify it.

2021-02-07 22:58 UTC, wizardlink commented on .editorconfig
> +indent_style = tab
I see what you mean, but, that's still not a problem. As well as that answer being... Partly incorrect in this context. I took a look at what you meant now, since, you didn't provide a direct link to the line and I was eating lunch.

By default in any source control visualizer, you have a tab being represented by eight spaces. Due to legacy, it has been kept like that, it would take an unnecessary processing to determine the `tabstop` of your project. That is why GitHub (and other source control visualizers) have query options. In GitHub you can pass `?ts=x` to determine the tabstop you are seeing, but, you can also have a [`editorconfig`](https://editorconfig.org/) on the root of the project and GitHub will use that to determine the `tabstop`.

With that out of the way, here is where things get complicated: This project has the wrong configuration for it's `cpp` indentation. When you are telling GitHub that `cpp` files use spaces for indentation, it can't guess what's the `tabstop`.

An example of this in the work: https://github.com/Hydractify/otservbr-global/blob/develop/src/game.cpp

You will notice that in my repository, we have the correct configuration, thus, you can see the actual indentation of the file.

2021-02-08 13:42 UTC, Costallat commented on .editorconfig
> +indent_style = tab
We use editorconfig not to configure Github but to configure our local environment(BTW: I didn't know that Github also read that file), if you change that to tab, my editor will start to use tab in place of space, as we are trying to follow the google style, we need to use [space](https://google.github.io/styleguide/cppguide.html#Spaces_vs._Tabs) or we are going to start mixing several styles again, that why it is configured to be spaces in place of tab

2021-02-08 14:03 UTC, wizardlink commented on .editorconfig
> +indent_style = tab
I agree with you, it is meant as a local fix. GitHub isn't a problem like it was mentioned previously, just a nice to have.

However, I don't believe enforcing a style that isn't in pair with the project is a good idea. If you believe that space indentation is the way to go, I will gladly accept it, after all, I created this PR to hopefully achieve consistency in this project. That said, if you want to use spaces, then you must first change the project adequatily and not keep the mixed indentation as-is.

You can't try to create consistency by writing inconsistencies. A reminder that this project doesn't has a workflow that checks for the indentation, so the `.editorconfig` is for those contributors who are aware of it's existence.

2021-02-08 14:46 UTC, wizardlink commented on .editorconfig
> +indent_style = tab
I usually wait for a reply before rebutting, but, here is just hard proof of how `space` is actually bringing more inconsistency than consistency:
![image](https://user-images.githubusercontent.com/26727907/107234759-c014ce80-6a02-11eb-8634-9c1f8f497e59.png)

Even if you divide the tabs by two (considering they are a single character, while the 2 space indentation, are two) it still 200.000 more occurrences. That makes up for 11% of the code, if you don't divide, that is less than 6%.

2021-02-11 19:02 UTC, closed without merging

2021-02-11 19:16 UTC, dudantas commented
I'm starting major changes in the source, gradually changing the indentation to SPACE instead of TAB, until then, we will continue using TAB as the default.