Conversion of all "std::cout" to "spdlog::" and all "print()" to "Spdlog.method()"
opentibiabr/otservbr-global-archived pull request #2454
Opened 2021-02-26 01:35 UTC by dudantas

In this pull, Spdlog library is being added
All "std::cout" have also been converted to "spdlog::method"
The LuaScriptInterface library was released
Just as all "print()" were converted to "Spdlog.method()"

C++ methods:
spdlog::info(text)
spdlog::warn(text)
spdlog::error(text)
spdlog::debug(text)

Lua methods:
"Spdlog.info(text)"
"Spdlog.warn(text)"
"Spdlog.error(text)"
"Spdlog.debug(text)"

2021-02-26 07:19 UTC, gpedro requested changes

2021-02-26 07:19 UTC, gpedro commented on data/lib/compat/compat.lua
> +	Spdlog.warn("[setCombatCondition] - Function was renamed to addCombatCondition and will be removed in the future")
should be Combat.setCombatCondition

2021-02-26 07:19 UTC, gpedro commented on data/lib/core/functions.lua
> +			Spdlog.warn("[debug.sethook] - Possible infinite loop in file ".. debug.getinfo(2).source .." near line ".. line .."")
you can keep it using string.format

2021-02-26 07:19 UTC, gpedro commented on data/lib/compat/compat.lua
> +	Spdlog.info("Broadcasted message: \"" .. message .. "\"")
you can use string.format here. should be better.

2021-02-26 07:19 UTC, gpedro commented on data/lib/core/functions.lua
> +			Spdlog.warn("[indexToStr] - Invalid type to serialize: " .. tp .. ", index: " .. i)
you can use string.format here. should be better.

2021-02-26 07:19 UTC, gpedro commented on data/lib/core/imbuements.lua
> +		Spdlog.error("[Imbuement::canImbueItem] - Error on search imbuement '".. imbuement:getName() .. "'")
you can use string.format here. should be better.

2021-02-26 07:19 UTC, gpedro commented on data/lib/core/imbuements.lua
> +		Spdlog.error("[Imbuement::canImbueItem] - Error on search weapons imbuement '" .. imbuement:getName() .. "'")
you can use string.format here. should be better.

2021-02-26 07:19 UTC, gpedro commented on data/lib/core/imbuements.lua
> +		Spdlog.error("[Imbuement::canImbueItem] - Error on search storage imbuement '" .. imbuement:getName())
you can use string.format here. should be better.

2021-02-26 07:19 UTC, gpedro commented on data/lib/core/quests.lua
> +	Spdlog.warn("[sendPrint] - Quest id: ".. questId ..", mission: ".. index)
you can use string.format here. should be better.

2021-02-26 07:19 UTC, gpedro commented on data/lib/core/quests.lua
> +					Spdlog.warn("Wrong mission name found")
you can add a prefix like Quests.load or Quests.init or something like that. same for all logs below.

2021-02-26 07:19 UTC, gpedro commented on data/lib/core/storages.lua
> +			Spdlog.warn("Processed in ".. os.clock() - benchmark ..".4f(s)")
you can keep it using string.format

2021-02-26 07:19 UTC, gpedro commented on data/lib/others/daily_reward_lib.lua
> +	Spdlog.info("Player: ".. self:getName() ..", streak level: ".. streakLevel ..", active bonuses: ".. self:getActiveDailyRewardBonusesName())
you can use string.format, uncomment and add as debug  log and add prefix.

2021-02-26 07:19 UTC, gpedro commented on data/lib/tables/achievements_lib.lua
> +		return Spdlog.error("[isAchievementSecret] - Invalid achievement \"" .. ach .. "\".") and false
you can use string.format and split the code in tow lines. log and below just `return false`. same for all here.

2021-02-26 07:19 UTC, gpedro commented on data/modules/scripts/blessings/blessings.lua
> +		Spdlog.info("[Blessings] START BOOL - "..pre)
this should be debug, uhm?

2021-02-26 07:19 UTC, gpedro commented on data/scripts/actions/quests/lower_roshamuul/resonance_chamber.lua
> +				--Spdlog.debug(x[i])
you can remove it

2021-02-26 07:19 UTC, gpedro commented on data/npc/lib/npcsystem/modules.lua
> +					Spdlog.warn("[KeywordModule:parseKeywords] - " .. Npc():getName() .. "] NpcSystem: Parameter '" .. "keyword_reply" .. n .. "' missing. Skipping...")
string.format pls.

2021-02-26 07:19 UTC, gpedro commented on data/scripts/globalevents/others/spawns_npc_by_time.lua
> +		Spdlog.info("Starting " .. periods[period] .. "... Current light is " .. light .. " and it's ".. getFormattedWorldTime(time) .. " Tibian Time")
string.format pls. all here.

2021-02-26 07:19 UTC, gpedro commented on data/scripts/globalevents/quests/pits_of_inferno_bosses.lua
> +		Spdlog.error("[bossesPoi] - Failed to spawn ".. rand.bossName)
wrong prefix. you can use string.format too

2021-02-26 07:19 UTC, gpedro commented on data/scripts/globalevents/spawn/rashid.lua
> +		Spdlog.info("Rashid arrived at ".. config.city .."")
string.format pls

2021-02-26 07:19 UTC, gpedro commented on data/scripts/globalevents/update.lua
> +				Spdlog.debug("All players sent to temple. Check if 'data/update.lua' contains 'updated = false'.")
should be warn.

2021-02-26 07:19 UTC, gpedro commented on data/scripts/globalevents/worldchanges/fury_gates.lua
> +	Spdlog.info("Fury Gate will be active in " .. gates[gateId].city .. " today")
string.format pls. you can use worldchanges prefix if you want.

2021-02-26 07:19 UTC, gpedro commented on data/scripts/globalevents/worldchanges/nightmare_isle.lua
> +	Spdlog.info("Nightmare Isle will be active ".. select.displayName .." today")
string.format pls. you can use worldchanges prefix if you want.

2021-02-26 07:19 UTC, gpedro commented on data/scripts/globalevents/worldchanges/yasir.lua
> +			Spdlog.info("Yasir: ".. randTown.mapName .."")
string.format pls. you can use worldchanges prefix if you want.

2021-02-26 07:19 UTC, gpedro commented on data/scripts/lib/register_monster_type.lua
> +			Spdlog.warn("[registerMonsterType.flags] - Monster: ".. mtype:name() .. ". Deprecated flag 'respawnType', use instead table 'respawnType = { period = RespawnPeriod_t, underground = boolean}'")
string.format pls.

2021-02-26 07:19 UTC, gpedro commented on data/scripts/talkactions/god/add_outfit.lua
> +			Spdlog.info("[addOutfit.onSay] - Player: '".. player:getName() .."' has been added looktype: '".. lookType .. "' to the player: '".. target:getName() .."'")
string.format pls. should be warn, i guess.

2021-02-26 07:19 UTC, gpedro commented on data/scripts/talkactions/god/count_monsters.lua
> +		--Spdlog.debug(monster, count)
you can remove that

2021-02-26 07:19 UTC, gpedro commented on data/startup/others/functions.lua
> +					Spdlog.warn("Action id: ".. index ..", item id: ".. value.itemId .."")
string.format pls.

2021-02-26 07:19 UTC, gpedro commented on src/database.cpp
> -		databaseLock.unlock();
whoops!

2021-02-26 07:19 UTC, gpedro commented on src/database.cpp
> -		databaseLock.unlock();
whoops!

2021-02-26 07:19 UTC, gpedro commented on src/database.cpp
> +		spdlog::error("Message: {}", mysql_error(handle));
add prefix again or use as one call. same for others below

2021-02-26 07:19 UTC, gpedro commented on src/databasemanager.cpp
> +		++version;
why?

2021-02-26 07:19 UTC, gpedro commented on src/definitions.h
> +static constexpr auto STATUS_SERVER_DEVELOPERS = "OTServBR-Global Team and SaiyansKing";
please, do not remove mark & tfs credits.

2021-02-26 07:19 UTC, gpedro commented on src/events.cpp
> +                     (party->getLeader())->getName());
unnecessary ()

2021-02-26 07:19 UTC, gpedro commented on src/events.cpp
> +                     (party->getLeader())->getName());
unnecessary ()

2021-02-26 07:19 UTC, gpedro commented on src/game.cpp
>  		std::cout << "> ERROR: Failed to save account: " << name << "!"
missing spdlog here

2021-02-26 07:19 UTC, gpedro commented on src/game.cpp
> +						spdlog::warn("Failed to set account premium days, account name: {}", account.GetName(&name));
should be just name as parameter. the call `account.GetName` should be outside the log as old below code.

````cpp
if (save && !account.SaveAccountDB()) {
  std::string name;
  account.GetName(&name);
  std::cout << "> ERROR: Failed to save account: " << name << "!"  << std::endl;
````

2021-02-26 07:19 UTC, gpedro commented on src/globalevent.cpp
> +                "Duplicate registered globalevent with name: ", globalEvent->getName());
missing argument on string: `{}`

2021-02-26 07:19 UTC, gpedro commented on src/imbuements.cpp
> +							spdlog::warn("[Imbuements::loadFromXml] Missing effect value for imbuement name ", imb.name);
missing argument on string: `{}`

2021-02-26 07:19 UTC, gpedro commented on src/imbuements.cpp
> +							spdlog::warn("[Imbuements::loadFromXml] Unknow skill name '", tmpStrValue, "' in imbuement name ", imb.name);
missing argument on string: `{}`

2021-02-26 07:19 UTC, gpedro commented on src/imbuements.cpp
> +							spdlog::warn("[Imbuements::loadFromXml] Missing skill bonus for imbuement name ", imb.name);
missing argument on string: `{}`

2021-02-26 07:19 UTC, gpedro commented on src/imbuements.cpp
> +							spdlog::warn("[Imbuements::loadFromXml] Missing combat for imbuement name ", imb.name);
missing argument on string: `{}`

2021-02-26 07:19 UTC, gpedro commented on src/imbuements.cpp
> +							spdlog::warn("[Imbuements::loadFromXml] Unknown combat type for element", attr.as_string());
missing argument on string: `{}`

2021-02-26 07:19 UTC, gpedro commented on src/imbuements.cpp
> +							spdlog::warn("[Imbuements::loadFromXml] Missing damage reduction percentage for imbuement name ", imb.name);
missing argument on string: `{}`

2021-02-26 07:19 UTC, gpedro commented on src/imbuements.cpp
> +							spdlog::warn("[Imbuements::loadFromXml] Missing cap value for imbuement name ", imb.name);
missing argument on string: `{}`

2021-02-26 07:19 UTC, gpedro commented on src/imbuements.cpp
> +							spdlog::warn("[Imbuements::loadFromXml] Missing speed value for imbuement name ", imb.name);
missing argument on string: `{}`

2021-02-26 07:19 UTC, gpedro commented on src/imbuements.cpp
> +							spdlog::warn("[Imbuements::loadFromXml] Unknown combat type for element", attr.as_string());
missing argument on string: `{}`

2021-02-26 07:19 UTC, gpedro commented on src/imbuements.cpp
> +							spdlog::warn("[Imbuements::loadFromXml] Missing damage reduction percentage for imbuement name ", imb.name);
missing argument on string: `{}`

2021-02-26 07:19 UTC, gpedro commented on src/imbuements.cpp
> +							spdlog::warn("[Imbuements::loadFromXml] Missing combat for imbuement name ", imb.name);
missing argument on string: `{}`

2021-02-26 07:19 UTC, gpedro commented on src/iomapserialize.cpp
> +				spdlog::warn("[IOMapSerialize::loadItem] - "
missing argument on string: `{}`

2021-02-26 07:19 UTC, gpedro commented on src/iomapserialize.cpp
> +				spdlog::warn("[IOMapSerialize::loadItem] - "
missing argument on string: `{}`

2021-02-26 07:19 UTC, gpedro commented on src/luascript.cpp
> +	std::string errorLog;
i'm not sure about this composition. need be tested.

2021-02-26 07:19 UTC, gpedro commented on src/luascript.cpp
> +				spdlog::warn("[LuaScriptInterface::luaMonsterTypeAddAttack] - Monster: {}",
this can be just one call

2021-02-26 07:19 UTC, gpedro commented on src/luascript.cpp
> +				spdlog::warn("[LuaScriptInterface::luaMonsterTypeAddDefense] - Monster: {}",
this can be just one call

2021-02-26 07:19 UTC, gpedro commented on src/modules.cpp
> +                     "Call stack overflow. Too many lua script calls being nested",
missing argument on string: `{}`

2021-02-26 07:19 UTC, gpedro commented on src/monster.cpp
> +	// spdlog::info("[Monster::onCreatureEnter] - {}", creature->getName());
if isnt necessary, drop it or use as debug

2021-02-26 07:19 UTC, gpedro commented on src/monster.cpp
> +	// spdlog::info("[Monster::onCreatureLeave] - {}", creature->getName());
if isnt necessary, drop it or use as debug

2021-02-26 07:19 UTC, gpedro commented on src/player.cpp
> +		spdlog::warn("Got exception");
you can print `e.what()` and error. something like that
```cpp
spdlog::error("[Player:getDefense] {} got exception: {}",getName(), e.what());
```

2021-02-26 07:19 UTC, gpedro commented on src/protocolgame.cpp
> +			// spdlog::info("Player: {} sent an unknown packet header: x0{}", player->getName(), static_cast<uint16_t>(recvbyte));
uncomment and use debug

2021-02-26 07:19 UTC, gpedro commented on src/rsa.cpp
> +		spdlog::info("{}", e.what());
should be error

2021-02-26 07:19 UTC, gpedro commented on src/otserv.cpp
> +	spdlog::info("Loading config.lua {}", result);
this should be before, uhm? like old code and the same for all others below

2021-02-26 07:19 UTC, gpedro commented on src/otserv.cpp
> +		spdlog::error(str);
lol. you dont need use string builder. just use parameters.

2021-02-26 07:19 UTC, gpedro commented on src/scripts.cpp
> +
i'm not sure about this otimization

2021-02-26 07:19 UTC, gpedro commented on src/spawn.cpp
> +                     "fileName: ", _filename);
missing param

2021-02-26 07:19 UTC, gpedro commented on src/monsters.cpp
> +                            "Cant load spell. ", file);
missing param

2021-02-26 07:19 UTC, gpedro commented on src/monsters.cpp
> +                            "Cant load spell. ", file);
missing param

2021-02-26 07:19 UTC, gpedro commented on data/modules/scripts/gamestore/init.lua
> +		Spdlog.warn("[parseBuyStoreOffer] - Purchase failed due to an unhandled script error. Stacktrace: ".. pcallError)
string.format pls

2021-02-26 07:22 UTC, gpedro commented
review:
- missing some params `{}`
- you missed some stdout
- you have deleted some lines important lines on databasemaanger.cpp
- on lua usage, if you have more than 1 variable to concat, consider using string.format instead. 
- idk why you changed the order of loading messages. make nonsense to me.
- keep Mark & TFS credits. it's required by code license

2021-02-26 20:40 UTC, dudantas commented on data/lib/compat/compat.lua
> +	Spdlog.warn("[setCombatCondition] - Function was renamed to addCombatCondition and will be removed in the future")
No, it's like that
![image](https://user-images.githubusercontent.com/8551443/109352520-bcce6f00-7859-11eb-9ca7-ca183abdd54c.png)

2021-02-26 20:54 UTC, dudantas commented on src/database.cpp
> -		databaseLock.unlock();
Thanks

2021-02-26 20:55 UTC, dudantas commented on src/database.cpp
> -		databaseLock.unlock();
Thanks

2021-02-27 21:27 UTC, dudantas commented on src/scripts.cpp
> +
I just added the load of scripts directly to otserv.cpp and sent the remaining functions to scripts.cpp
Since there were two: scriptmanager.cpp was for the old XML system, script.cpp for revscriptsys

2021-03-01 18:41 UTC, lgrossi commented on src/game.cpp
> +						spdlog::warn("Failed to set account premium days, account name: {}", account.GetName(&name));
Shouldnt this oen be error instead of warn?

2021-03-01 18:46 UTC, lgrossi commented on src/luascript.cpp
> +                    "Thing uid already taken: {}",
shouldn't it be ::error?

2021-03-01 18:47 UTC, lgrossi commented on src/luascript.cpp
> +		spdlog::info("{}", info);
you can just use directly `spdlog::info(info);` since info is a string already.

2021-03-01 18:48 UTC, lgrossi commented on src/luascript.cpp
> +		spdlog::info("{}", info);
you can do directly:

```
	if (isString(L, 1)) {
		spdlog::info(getString(L, 1));
        }
```

Same for the other 3 below

2021-03-01 19:00 UTC, lgrossi commented on src/scripts.cpp
> +
Where is the other initializations? global.lua, spells, etc?

2021-03-01 19:10 UTC, dudantas commented on src/scripts.cpp
> +
> Where is the other initializations? global.lua, spells, etc?
Otserv.cpp

2021-03-01 19:15 UTC, lgrossi commented on src/otserv.cpp
> +	spdlog::info("Loading startup.lua {}", result);
I didn't understand this result = "success". I dont think you need it. The info is just to log that it started loading that, if it fails it logs an error message, if it succeed it logs the next loading message, meaning that the system moved on without erros. this else is not needed (applies to all the others).

2021-03-01 19:24 UTC, lgrossi commented on src/otserv.cpp
> -  std::cout << ">> The program will close after pressing the enter key..." << "\033[0m" << std::endl;
Where is this message now?

2021-03-01 19:41 UTC, lgrossi commented on src/otserv.cpp
> +	spdlog::info("Loading data/monsters {}", result);
You could simplify all those loading logs in one function:

```
void modulesLoadHelper(bool loaded, std::string moduleName) {
  spdlog::info("Loading {}", moduleName);
  if (!loaded) {
     spdlog::error("Cannot load: {}", moduleName);
     startupErrorMessage();	
  }
}
```

then you can replace all those codes with ifs to straight forward calls:

```
void initGlobalScopes() {
  g_scripts = new Scripts();
  ...
  g_modules = new Modules();
  g_spells = new Spells();
  g_events = new Events();
}

void loadModules() {
  modulesLoadHelper(g_config.load(),"config.lua");
  ...
  modulesLoadHelper(g_luaEnvironment.loadFile("data/startup/startup.lua") == -1,"data/startup/startup.lua");
  modulesLoadHelper(g_scripts->loadScripts("scripts/lib", true, false),"");
  modulesLoadHelper(g_vocations.loadFromXml(),"data/XML/vocations.xml");
  modulesLoadHelper(g_game.loadScheduleEventFromXml(),"data/XML/events.xml");
  modulesLoadHelper(Outfits::getInstance().loadFromXml(),"data/XML/outfits.xml");
  modulesLoadHelper(Familiars::getInstance().loadFromXml(), "data/XML/familiars.xml");
  modulesLoadHelper(g_imbuements->loadFromXml(), "data/XML/imbuements.xml");
  modulesLoadHelper(g_modules->loadFromXml(), "data/modules/modules.xml");
  modulesLoadHelper(g_spells->loadFromXml(), "data/spells/spells.xml");
  modulesLoadHelper(g_events->load(), "data/events/events.xml");
  modulesLoadHelper(g_scripts->loadScripts("scripts", false, false), "data/scripts");
  modulesLoadHelper(g_scripts->loadScripts("monster", false, false), "data/monster");
}
```

Then, you can remove all those loadings and initialization from mainLoader and replace it by:
```
  ...
  initGlobalScopes();
  loadModules();
  ...
```

2021-03-01 19:47 UTC, lgrossi commented on src/otserv.cpp
> +	spdlog::info("Loading data/monsters {}", result);
You can improve even more by simplifying the file loaders:
```
void loadFileHelper(std::string filePath) {
  modulesLoadHelper(g_luaEnvironment.loadFile(filePath) == -1, filePath);
}
```
then it will be simply:
```
  loadFileHelper("data/global.lua");
  loadFileHelper("data/stages.lua");
  loadFileHelper("data/startup/startup.lua");
```

2021-03-04 16:10 UTC, gpedro requested changes

2021-03-04 16:10 UTC, gpedro commented on src/definitions.h
> +static constexpr auto STATUS_SERVER_DEVELOPERS = "OTServBR-Global Team, Mark Samman and The Forgotten Server Developers"
missing semicolon

2021-04-07 18:54 UTC, dudantas commented
https://github.com/opentibiabr/otservbr-global/pull/2512

2021-04-07 18:54 UTC, closed without merging