Feaster of Souls
opentibiabr/otservbr-global-archived pull request #2462
Opened 2021-03-04 00:06 UTC by hyresu

Still needs the map editing

2021-03-04 20:40 UTC, joao-blip commented
```
 /data/scripts/quests/feaster_of_souls/the_pale_worm/boss_lever.lua
 ..pts/quests/feaster_of_souls/the_pale_worm/boss_lever.lua:42: attempt to index local 'condition' (a nil value)
```

and

`
data/scripts/quests/feaster_of_souls/the_pale_worm/lantern.lua
 ...cripts/quests/feaster_of_souls/the_pale_worm/lantern.lua:7: attempt to index local 'condition' (a nil value)
stack traceback:
  [C]: in function '__index'
   ...cripts/quests/feaster_of_souls/the_pale_worm/lantern.lua:7: in main chunk
`

2021-03-05 00:48 UTC, joao-blip commented
anything else from the src changes is bugging the character's healing

2021-03-20 17:49 UTC, Badeburu commented
data/scripts/quests/feaster_of_souls/the_pale_worm/lantern.lua ...cripts/quests/feaster_of_souls/the_pale_worm/lantern.lua:7: attempt to index local 'condition' (a nil value) stack traceback: [C]: in function '__index' ...cripts/quests/feaster_of_souls/the_pale_worm

How i do this?

2021-03-20 17:50 UTC, Badeburu commented
Where i found The spells of all monsters? Can u post?

2021-03-25 01:25 UTC, Juanzin420 commented
data/scripts/quests/feaster_of_souls/the_pale_worm/lantern.lua ...cripts/quests/feaster_of_souls/the_pale_worm/lantern.lua:7: attempt to index local 'condition' (a nil value) stack traceback: [C]: in function '__index' ...cripts/quests/feaster_of_souls/the_pale_worm/lantern.lua:7: in main chunk
 got the same error from above, fixed it by adding this to conditions.cpp 
		case CONDITION_HEX:
			return new ConditionRegeneration(id, type, ticks, buff, subId); 
			
			but hex isnt working

2021-03-27 23:22 UTC, Broodly commented
Do u have the spell for monsters?

2021-03-28 01:01 UTC, Broodly commented
Lua Script Error: [Scripts Interface]
C:\Users\leand\Desktop\Con lucas\otservbr-global-develop\data\scripts\quests\feaster_of_soul\the_pale_worm\boss_lever.lua
...ipts\quests\feaster_of_soul\the_pale_worm\boss_lever.lua:42: attempt to index local 'condition' (a nil value)
stack traceback:
        [C]: in function '__index'
        ...ipts\quests\feaster_of_soul\the_pale_worm\boss_lever.lua:42: in main chunk
> boss_lever.lua [error]
^

Lua Script Error: [Scripts Interface]
C:\Users\leand\Desktop\Con lucas\otservbr-global-develop\data\scripts\quests\feaster_of_soul\the_pale_worm\lantern.lua
...scripts\quests\feaster_of_soul\the_pale_worm\lantern.lua:7: attempt to index local 'condition' (a nil value)
stack traceback:
        [C]: in function '__index'
        ...scripts\quests\feaster_of_soul\the_pale_worm\lantern.lua:7: in main chunk
> lantern.lua [error]
^

2021-03-29 13:46 UTC, Badeburu commented
the "brother" will is dead before the pale worm... and need update the room with damage, dont has damage per second with have players at the second floor

2021-03-29 22:03 UTC, joao-blip requested changes
/data/scripts/quests/feaster_of_souls/the_pale_worm/boss_lever.lua
 ..pts/quests/feaster_of_souls/the_pale_worm/boss_lever.lua:42: attempt to index local 'condition' (a nil value)
and

data/scripts/quests/feaster_of_souls/the_pale_worm/lantern.lua ...cripts/quests/feaster_of_souls/the_pale_worm/lantern.lua:7: attempt to index local 'condition' (a nil value) stack traceback: [C]: in function '__index' ...cripts/quests/feaster_of_souls/the_pale_worm/lantern.lua:7: in main chunk


anything else from the src changes is bugging the character's healing

2021-04-28 15:35 UTC, potreco requested changes

2021-04-28 15:35 UTC, potreco commented on src/game.cpp
> +			damage.primary.value *= targetPlayer->getBuff(BUFF_HEALINGRECEIVED) / 100.;
This condition is breaking the healing system, no type of healing is working.

2021-04-29 23:38 UTC, gabrielscolt0 commented
> Where i found The spells of all monsters? Can u post?

i need the spells, so i can test dread maiden

2021-04-30 01:54 UTC, LIKEAHYENA commented
> > Where i found The spells of all monsters? Can u post?
> 
> i need the spells, so i can test dread maiden

Which spells do you need?

2021-04-30 01:59 UTC, gabrielscolt0 commented
summonsthedreadmaiden, summonsunwelcome, maidenring, deathring1x1. The other spells I think I can create

2021-04-30 02:00 UTC, gabrielscolt0 commented
> > > Where i found The spells of all monsters? Can u post?
> > 
> > 
> > i need the spells, so i can test dread maiden
> 
> Which spells do you need?

summonsthedreadmaiden, summonsunwelcome, maidenring, deathring1x1. The other spells I think I can create

2021-05-07 17:31 UTC, patrickjmeurer commented on data/scripts/quests/feaster_of_souls/entrances.lua
> +	[14531] = {position = Position({x = 33613, y = 31415, z = 8})},
This position is incorrect, please correct to `Position({x = 33649, y = 31445, z = 10})`

2021-05-08 20:08 UTC, oualid6496 commented
The following monster spells are missing
![image](https://user-images.githubusercontent.com/32771228/117552058-93944100-b049-11eb-836e-c0c50e94b6e4.png)

Also there seems to be a mixup between the teleports to The Pale Worm and The Fear Feaster

2021-05-18 12:32 UTC, MajestyOTBR commented
PR closed due to inactivity.

2021-05-18 12:32 UTC, closed without merging

2021-07-09 00:16 UTC, Broodly commented
Amigo porque dejo de funcionar algunos scripts de aqui?
....data\scripts\quests\feaster_of_soul\netheworld\mini_bosses.lua
[2021-08-07 21:12:11.837] [error] ...cripts\quests\feaster_of_soul\netheworld\mini_bosses.lua:3: attempt to index field 'Bosses' (a nil value)
stack traceback:
        [C]: in function '__index'
        ...cripts\quests\feaster_of_soul\netheworld\mini_bosses.lua:3: in main chunk

Me esta saliendo eso, antes me funcionaba un par de update atras.. ahora ya no si alguien puede ayudarme