Talkactions
opentibiabr/otservbr-global-archived pull request #2502
Opened 2021-03-31 02:12 UTC by daanyx

Algumas Talkactions simples porém úteis!

2021-03-31 15:03 UTC, adrianomengue approved these changes
Good job!

2021-04-03 01:16 UTC, LukeAtMyNose approved these changes
Good idea, thanks

2021-04-03 05:31 UTC, mattyx14 commented
Is for to otx jeje

2021-04-07 18:58 UTC, Costallat commented on data/scripts/talkactions/god/online.lua
> +    local playersOnline = #onlineList
```suggestion
    local playersOnlineList = #onlineList
```

2021-04-07 18:58 UTC, Costallat commented on data/scripts/talkactions/god/online.lua
> +    for i = 1, playersOnline, maxPlayersPerMessage do
```suggestion
    for i = 1, playersOnlineList, maxPlayersPerMessage do
```

2021-04-07 18:58 UTC, Costallat commented on data/scripts/talkactions/god/online.lua
> +        local j = math.min(i + maxPlayersPerMessage - 1, playersOnline)
```suggestion
        local j = math.min(i + maxPlayersPerMessage - 1, playersOnlineList)
```

2021-04-07 18:58 UTC, Costallat commented on data/scripts/talkactions/god/online.lua
> +    player:sendTextMessage(MESSAGE_ATTENTION, ("%d players online!"):format(playersOnline))
```suggestion
    player:sendTextMessage(MESSAGE_ATTENTION, ("%d players online!"):format(playersOnlineList))
```

2021-04-07 18:58 UTC, Costallat commented on data/scripts/talkactions/player/aol.lua
> +local aol = 2173
```suggestion
local aolID = 2173
```

2021-04-07 18:58 UTC, Costallat commented on data/scripts/talkactions/player/aol.lua
> +    doPlayerAddItem(cid, aol, 1)
```suggestion
    doPlayerAddItem(cid, aolID, 1)
```

2021-04-08 20:21 UTC, dudantas requested changes, later dismissed
You can convert to API 1.3: 
`
local aol = TalkAction("!aol")

function aol.onSay(creature, words, param)
local aolID = 2173
  if player:removeMoney(50000) == true then
    player:sendTextMessage(MESSAGE_EVENT_ADVANCE, "You have bought an ".. ItemType(aolID):getName().." for 50K!")
    player:addItem(aolID, 1)
    player:getPosition():sendMagicEffect(CONST_ME_MAGIC_BLUE)
  else
    player:sendCancelMesage("Sorry, You need 50K to buy an aol!")
  end
return true
end

aol:register()`

Please, test this.

2021-04-08 20:51 UTC, dudantas approved these changes

2021-04-08 21:53 UTC, LukeAtMyNose approved these changes
Much better, avoids overload in the future

2021-04-08 21:57 UTC, MajestyOTBR approved these changes

2021-04-08 23:33 UTC, merged