add npc that sells all imbuiment items
opentibiabr/otservbr-global-archived pull request #2544
Opened 2021-04-22 15:02 UTC by czbadaro

2021-04-25 06:19 UTC, dudantas approved these changes

2021-04-25 14:25 UTC, MajestyOTBR commented
Fix npc name and remove `script="testserver_assistant.lua"` because there is no lua script.

2021-04-25 14:49 UTC, MajestyOTBR commented
Fix npc name and set `script="testserver_assistant.lua"` to `script=default.lua"`.

2021-04-25 14:49 UTC, MajestyOTBR commented
Fix npc name and set `script="testserver_assistant.lua"` to `script="default.lua"`.

2021-04-25 15:17 UTC, dudantas requested changes

2021-04-25 15:17 UTC, dudantas commented on data/npc/imbuiment_assistent.xml
> +<npc name="Imbuiment Assistant" walkinterval="2000" floorchange="0" script="testserver_assistant.lua">
<npc name="Imbuement Assistant" walkinterval="2000" floorchange="0" script="default.lua">

2021-05-18 12:32 UTC, MajestyOTBR commented
PR closed due to inactivity.

2021-05-18 12:32 UTC, closed without merging