Update grand_master_oberon.lua
opentibiabr/otservbr-global-archived pull request #2672
Opened 2021-07-11 11:08 UTC by vtrolinux

baseado no script anterior
-adicionado mecânica idêntica ao do global
como não achei "Holybeam" mantive o mesmo ataque mas o certo é uma reta de san, gg ;)

2021-07-11 14:25 UTC, Deadsmelly commented on data/monster/quests/the_secret_library/bosses/grand_master_oberon.lua
>  	[2] = {msg = "The world will suffer for its iddle laziness!"},
Change "iddle" to "idle"
![image](https://user-images.githubusercontent.com/85965963/125199006-ec3eb080-e229-11eb-8c9c-5089a4317e3a.png)

2021-07-11 21:41 UTC, Schiffers approved these changes

2021-07-15 01:45 UTC, Glatharth requested changes

2021-07-15 01:45 UTC, Glatharth commented on data/monster/quests/the_secret_library/bosses/grand_master_oberon.lua
> +--[[ author vtrolinux(nox) ]]--
Would be very kind if you could remove this line.
Since you're not the author of the script and you just made a few alterations on it, it does look like you're claiming credits for the whole thing.
Thanks for your consideration!

2021-07-15 01:45 UTC, Glatharth commented on data/monster/quests/the_secret_library/bosses/grand_master_oberon.lua
> +local controleTempo = 0
I think it would be better if we stick to one language only, since everything else is in english, would make more sense.

2021-07-15 06:01 UTC, vtrolinux commented on data/monster/quests/the_secret_library/bosses/grand_master_oberon.lua
>  	[2] = {msg = "The world will suffer for its iddle laziness!"},
ok

2021-07-15 06:01 UTC, vtrolinux commented on data/monster/quests/the_secret_library/bosses/grand_master_oberon.lua
> +--[[ author vtrolinux(nox) ]]--
ok

2021-07-15 06:02 UTC, vtrolinux commented on data/monster/quests/the_secret_library/bosses/grand_master_oberon.lua
> +local controleTempo = 0
ok

2021-07-19 09:40 UTC, Glatharth approved these changes

2021-07-27 15:49 UTC, gabrielscolt0 commented
Testei aqui e comigo não funcionou, Oberon ficou com vidas infinitas

2021-08-01 19:06 UTC, MajestyOTBR commented
Need review and tests.

2021-09-26 09:55 UTC, dudantas commented
It will be fixed in the repository: https://github.com/opentibiabr/otservbr-global-datapack

2021-09-26 09:55 UTC, closed without merging