Fix decaying items crash in bosses #2709
opentibiabr/otservbr-global-archived pull request #2710
Opened 2021-08-27 07:05 UTC by gesior

# Description

Bosses drop decaying items. If you open 'reward container' in boss corpse, not pick decaying items and corpse disappear, it will crash server.

## Behaviour
### **Actual**

Server crash.

### **Expected**

Server does not crash.

## Fixes

#2709

## Type of change

  - Bug fix (non-breaking change which fixes an issue)
Operating System:

2021-08-27 07:17 UTC, mrhultin commented
I see the return, and unable to test, but wouldnt this make the reward container empty if the first item has decay or do I need more coffee here?

2021-08-27 08:13 UTC, gesior commented
@mrhultin 
Probably more coffee :)
`MonsterType.createLootItem(self, lootBlock, chance, lootTable)` is called for every loot item in boss:
https://github.com/opentibiabr/otservbr-global/blob/cb3e8408dbd2fa6c78a7d5ea3ba83649086ce80c/data/lib/others/reward_boss_lib.lua#L96

It should block only single bugged items.

2021-08-27 08:52 UTC, mrhultin commented
> @mrhultin 
> 
> Probably more coffee :)
> 
> `MonsterType.createLootItem(self, lootBlock, chance, lootTable)` is called for every loot item in boss:
> 
> https://github.com/opentibiabr/otservbr-global/blob/cb3e8408dbd2fa6c78a7d5ea3ba83649086ce80c/data/lib/others/reward_boss_lib.lua#L96
> 
> 
> 
> It should block only single bugged items.

Yeah you are correct, ofc. I like this fix, its elegant!

2021-08-27 10:43 UTC, ArturKnopik commented
I prefer check such things  during startup(check during adding loot to monste[boss] and change/remove decaying items), we don't perform any additional operation during normal gameplay #optymization_lover

2021-08-27 16:57 UTC, mattyx14 approved these changes

2021-08-27 22:50 UTC, Bipbop69 approved these changes

2021-08-27 23:08 UTC, dudantas commented on data/lib/others/reward_boss_lib.lua
> +			print("[Warning - MonsterType.createLootItem] Convert boss '" .. self:name() .. "' reward ID '" .. lootBlock.itemId .. "' to ID " .. transformDeEquipId .. ".")
You can changue here to 
```suggestion
			Spdlog.warn("[MonsterType.createLootItem] - Convert boss '" .. self:name() .. "' reward ID '" .. lootBlock.itemId .. "' to ID " .. transformDeEquipId .. ".")
```

2021-08-27 23:09 UTC, dudantas commented on data/lib/others/reward_boss_lib.lua
> +			print("[Error - MonsterType.createLootItem] Cannot add item " .. lootBlock.itemId .. " as boss " .. self:name() .. " reward. It has decay.")
```suggestion
			Spdlog.error("[MonsterType.createLootItem] Cannot add item " .. lootBlock.itemId .. " as boss " .. self:name() .. " reward. It has decay.")
```

2021-08-27 23:11 UTC, dudantas requested changes
Your pull is very important. Thanks for the contribution. I left two suggestions, as our source was changed logs to SPDLOG.

2021-09-01 00:37 UTC, dudantas approved these changes

2021-09-01 00:43 UTC, MajestyOTBR approved these changes

2021-09-01 01:00 UTC, merged