[impr] Improves schema.sql file
opentibiabr/otservbr-global-archived pull request #303
Opened 2019-07-24 21:50 UTC by Costallat

- Refactor file to keep all things related to a table together with it.
- Removes not used tables;
- Removes migration scripts.

2019-07-25 01:54 UTC, ghost requested changes

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +  `create_date` int(11) NOT NULL DEFAULT '0',
não é usada em nenhum lugar, todas as ocorrências dela

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +  `create_ip` int(11) NOT NULL DEFAULT '0',
não é usada em nenhum lugar, todas as ocorrências dela

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +  `create_ip` int(11) NOT NULL DEFAULT '0',
não é usada em nenhum lugar, todas as ocorrências dela

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +  `deleted` tinyint(1) NOT NULL DEFAULT '0',
não é usada em nenhum lugar, todas as ocorrências dela

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +  `description` varchar(255) NOT NULL DEFAULT '',
não é usada em nenhum lugar, todas as ocorrências dela

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +  `comment` text NOT NULL,
não é usada em nenhum lugar, todas as ocorrências dela

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +  `town_id` int(11) NOT NULL DEFAULT '0',
coloca town_id default 1

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +ALTER TABLE `accounts` AUTO_INCREMENT=3;
pode remover se fizer a mudança acima

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +  `hide_char` int(11) NOT NULL DEFAULT '0',
não é usada em nenhum lugar, todas as ocorrências dela

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +  `hide_skills` int(11) DEFAULT NULL,
não é usada em nenhum lugar, todas as ocorrências dela

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +  `hide_set` int(11) DEFAULT NULL,
não é usada em nenhum lugar, todas as ocorrências dela

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +  `former` varchar(255) NOT NULL DEFAULT '-',
não é usada em nenhum lugar, todas as ocorrências dela

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `player_former_names` (
pode excluir a tabela player_former_names, não é usada em nenhum lugar

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +  `signature` varchar(255) NOT NULL DEFAULT '',
não é usada em nenhum lugar, todas as ocorrências dela

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +  `loyalty_ranking` tinyint(1) NOT NULL DEFAULT '0',
não é usada em nenhum lugar

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +  `bonus_reroll` int(11) NOT NULL DEFAULT '0',
não é usada em nenhum lugar,

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +INSERT INTO `players` (`id`, `name`, `group_id`, `account_id`, `level`, `vocation`, `health`, `healthmax`, `experience`, `lookbody`, `lookfeet`, `lookhead`, `looklegs`, `looktype`, `lookaddons`, `mag
remover daqui as q foram tiradas acima

2019-07-25 01:54 UTC, ghost commented on schema.sql
>  ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +ALTER TABLE `players` AUTO_INCREMENT=7;
pode remover e colocar o autoincrement=7 la no 'id' acima

2019-07-25 01:54 UTC, ghost commented on schema.sql
>  ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;

2019-07-25 01:54 UTC, ghost commented on schema.sql
>  ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;

2019-07-25 01:54 UTC, ghost commented on schema.sql
>  ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `announcements` (
não usada em lugar algum

2019-07-25 01:54 UTC, ghost commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `blessings_history` (
tabela não usada, pode remover ela e colocar ela comentada no arquivo data\modules\scripts\blessings\blessings.lua

2019-07-25 01:54 UTC, ghost commented on schema.sql
>  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;

2019-07-25 01:54 UTC, ghost commented on schema.sql
>  ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;

2019-07-25 01:54 UTC, EPuncker commented on schema.sql
>    `create_ip` int(11) NOT NULL DEFAULT '0',
pode remover

2019-07-25 01:54 UTC, EPuncker commented on schema.sql
>  ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;

2019-07-25 01:54 UTC, EPuncker commented on schema.sql
>    `last_execute_points` int(11) NOT NULL DEFAULT '0',
pode remover

2019-07-25 01:54 UTC, EPuncker commented on schema.sql
> +  `logo_gfx_name` varchar(255) NOT NULL DEFAULT '',
pode remover

2019-07-25 01:54 UTC, EPuncker commented on schema.sql
> +) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;

2019-07-25 01:54 UTC, EPuncker commented on schema.sql
>  ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;

2019-07-25 01:54 UTC, EPuncker commented on schema.sql
>  ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;

2019-07-25 01:54 UTC, EPuncker commented on schema.sql
>  ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;

2019-07-25 01:54 UTC, EPuncker commented on schema.sql
> +ALTER TABLE `houses` AUTO_INCREMENT=2489;
ve se precisa disso mesmo, quase certeza que não kk

2019-07-25 01:54 UTC, EPuncker commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `newsticker` (
pode remover

2019-07-25 01:54 UTC, EPuncker commented on schema.sql
> +) ENGINE=MEMORY DEFAULT CHARSET=latin1;
ENGINE=MEMORY DEFAULT CHARACTER SET=utf8;

2019-07-25 01:54 UTC, EPuncker commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `sellchar` (
pode remover ela e td relacionado

2019-07-25 14:56 UTC, Costallat commented on schema.sql
> +ALTER TABLE `accounts` AUTO_INCREMENT=3;
Ah ele não deixa, precisa alterar depois

2019-07-26 01:31 UTC, EPuncker commented on schema.sql
>    `guild_logo` mediumblob,
pode remover

2019-07-31 01:05 UTC, gpedro commented on data/migrations/0.lua
> +]=========]
this is a not valid block comment.

2019-08-04 03:31 UTC, edilsonbim approved these changes

2019-08-08 17:00 UTC, majestyotbr approved these changes

2019-08-08 17:04 UTC, merged

2019-08-08 17:34 UTC, MajestyOTBR commented
With schema.sql, compatibility:
- [x] MyAAC (https://github.com/slawkens/myaac).
- [x] ZnoteAAC (https://github.com/Znote/ZnoteAAC).

2020-04-20 15:16 UTC, gpedro commented
confirmed.
dummies in houses can only be used by one player

2020-04-21 01:35 UTC, rtsrick2017 commented
@gpedro by the way, if I recall correctly, you can still push other players while they're training, which cancels their training.

2020-04-21 03:05 UTC, dudztroyer commented
that's true, you can push other players.