[WIP] [Rewrite] Imbuement System
opentibiabr/otservbr-global-archived pull request #314
Opened 2019-07-26 18:59 UTC by LucasCPrazeres

Créditos aos criadores em imbuements.cpp e imbuements.h
* Critical Damage pegando todos do combat
* Leechs pegando a media do dano dos monstros afetado

2019-07-26 19:04 UTC, westwol commented
This is huge, thanks for the contribution.

2019-07-26 19:54 UTC, joseluis2g commented
this was not done by cjaker...

2019-07-26 22:00 UTC, mattyx14 reviewed
Is more good it

2019-07-27 15:27 UTC, jlcvp commented on src/player.cpp
> +		imbuing->decrementReferenceCounter();
pootz, parabéns por cuidar dos ponteiros

2019-07-27 15:30 UTC, jlcvp approved these changes
LGTM

2019-07-28 18:57 UTC, westwol commented on data/lib/core/imbuements.lua
> +	if #imb_type == 0 then
`if #imb_type == 0 or imb_type == "" then`

I would do something like this.

2019-07-28 19:03 UTC, westwol requested changes

2019-07-28 19:03 UTC, westwol commented on data/lib/core/imbuements.lua
> +MESSAGEDIALOG_IMBUEMENT_ERROR = 1,
There's a typo in the lib, commas should be removed as they are not in a table.
`MESSAGEDIALOG_IMBUEMENT_ERROR = 1
MESSAGEDIALOG_IMBUEMENT_ROLL_FAILED = 2
MESSAGEDIALOG_IMBUING_STATION_NOT_FOUND = 3
MESSAGEDIALOG_CLEARING_CHARM_SUCCESS = 10
MESSAGEDIALOG_CLEARING_CHARM_ERROR = 11`

2019-07-28 19:13 UTC, westwol commented
I've ran some tests, capacity imbuement is not being applied.

2019-07-28 20:41 UTC, LucasCPrazeres commented on data/lib/core/imbuements.lua
> +MESSAGEDIALOG_IMBUEMENT_ERROR = 1,
thanks

2019-07-30 12:29 UTC, LucasCPrazeres commented
all right?

2019-07-30 14:07 UTC, gpedro commented on data/events/scripts/player.lua
> +					local hours = math.floor(duration / 3600)
isso não daria para ser substituido pelo [`string.diff`](https://github.com/opentibiabr/OTServBR-Global/blob/develop/data/lib/core/string.lua#L21-L42)

2019-07-30 14:15 UTC, gpedro commented on data/scripts/movements/registerimbues.lua
> +local mov = readFile("data/movements/movements.xml")
isso é realmente necessário?

2019-07-30 14:19 UTC, LucasCPrazeres commented on data/scripts/movements/registerimbues.lua
> +local mov = readFile("data/movements/movements.xml")
Sim, caso contrário, não registra o movimento ao equipar

2019-07-30 16:39 UTC, westwol approved these changes

2019-07-30 18:28 UTC, gpedro commented on data/scripts/movements/registerimbues.lua
> +local mov = readFile("data/movements/movements.xml")
sim, mas eu digo em relação da leitura do arquivo. não há alguma forma alternativa de fazer isso?

2019-07-30 18:29 UTC, westwol commented on data/scripts/movements/registerimbues.lua
> +local mov = readFile("data/movements/movements.xml")
I think it's better if we do this onStartUp.

2019-07-30 18:32 UTC, LucasCPrazeres commented on data/scripts/movements/registerimbues.lua
> +local mov = readFile("data/movements/movements.xml")
Hmmmm, posso criar uma função Game.hasMoveevent(itemid)

about startup, then it would have to restart whenever adding a new item in imbuement.

2019-07-30 18:34 UTC, westwol commented on data/scripts/movements/registerimbues.lua
> +local mov = readFile("data/movements/movements.xml")
This function basically register items that can be imbue'd that are not registered, am I wrong? I believe it is not safe to modify a file on production.

2019-07-30 18:38 UTC, LucasCPrazeres commented on data/scripts/movements/registerimbues.lua
> +local mov = readFile("data/movements/movements.xml")
I'll move to startup and use another way to check if moveevent is registered.

2019-07-30 22:13 UTC, LucasCPrazeres commented on data/events/scripts/player.lua
> +					local hours = math.floor(duration / 3600)
usando string.diff:
19:10 You see a falcon wand (magic level +3, protection fire +8%).
It can only be wielded properly by sorcerers of level 300 or higher.
Imbuements: (Powerful Vampirism 19 hours, 59 minutes and 50 seconds, Empty Slot).

Usando getTime:
19:12 You see a falcon wand (magic level +3, protection fire +8%).
It can only be wielded properly by sorcerers of level 300 or higher.
Imbuements: (Powerful Vampirism 19:57h, Empty Slot).

2019-07-30 23:51 UTC, Flyckks commented
Approved.

2019-07-31 00:48 UTC, gpedro commented on data/events/scripts/player.lua
> +					local hours = math.floor(duration / 3600)
é, melhor não xD

2019-07-31 00:52 UTC, merged

2019-07-31 01:08 UTC, gpedro commented
hey,
i found some warnings on build.

```
c:\projects\otservbr-global\src\otserv.cpp(256): warning C4242: 'argument': conversion from 'int32_t' to 'uint16_t', possible loss of data [C:\projects\otservbr-global\vc14\theforgottenserver.vcxproj]
c:\projects\otservbr-global\src\protocol.cpp(137): warning C4242: 'argument': conversion from 'int' to 'NetworkMessage::MsgSize_t', possible loss of data [C:\projects\otservbr-global\vc14\theforgottenserver.vcxproj]
c:\projects\otservbr-global\src\item.h(814): warning C4242: 'return': conversion from 'int32_t' to 'uint8_t', possible loss of data (compiling source file ..\src\protocollogin.cpp) [C:\projects\otservbr-global\vc14\theforgottenserver.vcxproj]
```

2019-09-21 18:28 UTC, MasterMacavelli commented
So it just ignore weapons element and consider only imbuements?
Really smart.