fix: dreammer challenge (by Worthdavi
opentibiabr/otservbr-global-archived pull request #385
Opened 2019-08-10 14:32 UTC by eduardodantas95

Thanks @worthdavi 

Co-Authored-By: worthdavi <worthdavi@users.noreply.github.com>

2019-08-13 22:52 UTC, ghost requested changes
muda os storages pra tabela de storages igual as outras quests q fica belezinha

2019-08-13 22:52 UTC, EPuncker commented on data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua
> +			if diamondItem and player:getStorageValue(641311) < 1 then
troca 641311 pelo valor na tabela de storages, igual foi feito na parte de cima

2019-08-13 22:52 UTC, EPuncker commented on data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua
> +				player:setStorageValue(641311, 1)
troca 641311 pelo valor na tabela de storages, adiciona la caso necessario

2019-08-13 22:52 UTC, EPuncker commented on data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua
> +			if diamondItem and player:getStorageValue(641312) < 1 then
mesmo comentario da anterior

2019-08-13 22:52 UTC, EPuncker commented on data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua
> +				player:setStorageValue(641312, 1)
mesmo comentario da anterior

2019-08-13 22:52 UTC, EPuncker commented on data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua
> +			if diamondItem and player:getStorageValue(641313) < 1 then
mesmo comentario da anterior

2019-08-13 22:52 UTC, EPuncker commented on data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua
> +				player:setStorageValue(641313, 1)
mesmo comentario da anterior

2019-08-13 22:52 UTC, EPuncker commented on data/actions/scripts/quests/dreamer challenge/lever_nightmare.lua
> +			if diamondItem and player:getStorageValue(641311) < 1 then
mesmo comentario da anterior

2019-08-13 22:52 UTC, EPuncker commented on data/actions/scripts/quests/dreamer challenge/lever_nightmare.lua
> +				player:setStorageValue(641311, 1)
mesmo comentario da anterior

2019-08-13 22:52 UTC, EPuncker commented on data/actions/scripts/quests/dreamer challenge/lever_nightmare.lua
> +			if diamondItem and player:getStorageValue(641312) < 1 then
mesmo comentario da anterior

2019-08-13 22:52 UTC, EPuncker commented on data/actions/scripts/quests/dreamer challenge/lever_nightmare.lua
> +				player:setStorageValue(641312, 1)
mesmo comentario da anterior

2019-08-13 22:52 UTC, EPuncker commented on data/actions/scripts/quests/dreamer challenge/lever_nightmare.lua
> +			elseif not diamondItem and player:getStorageValue(641312) < 1 then
mesmo comentario da anterior

2019-08-13 22:52 UTC, EPuncker commented on data/actions/scripts/quests/dreamer challenge/lever_nightmare.lua
> +			if diamondItem and player:getStorageValue(641313) < 1 then
mesmo comentario da anterior

2019-08-13 22:52 UTC, EPuncker commented on data/actions/scripts/quests/dreamer challenge/lever_nightmare.lua
> +				player:setStorageValue(641313, 1)
mesmo comentario da anterior

2019-08-13 23:21 UTC, worthdavi commented
a quest ja tava assim kkk podem colocar se quiser. número alto assim eu nem
faço mt questão de registrar no 051

Em ter, 13 de ago de 2019 19:52, Evil Puncker <notifications@github.com>
escreveu:

> *@EPuncker* requested changes on this pull request.
>
> muda os storages pra tabela de storages igual as outras quests q fica
> belezinha
> ------------------------------
>
> In data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua
> <https://github.com/opentibiabr/OTServBR-Global/pull/385#discussion_r313644254>
> :
>
> > +
> +local function revertLever(position)
> +	local leverItem = Tile(position):getItemById(1946)
> +	if leverItem then
> +		leverItem:transform(1945)
> +	end
> +end
> +
> +function onUse(player, item, fromPosition, target, toPosition, isHotkey)
> +	if item.itemid ~= 1945 then
> +		return true
> +	end
> +	if item.uid == config[1].uid then
> +		local diamondItem = Tile(config[1].position):getItemById(2145)
> +		if player:getStorageValue(Storage.OutfitQuest.BrotherhoodOutfit) >= config[1].storageOutfit then
> +			if diamondItem and player:getStorageValue(641311) < 1 then
>
> troca 641311 pelo valor na tabela de storages, igual foi feito na parte de
> cima
> ------------------------------
>
> In data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua
> <https://github.com/opentibiabr/OTServBR-Global/pull/385#discussion_r313644355>
> :
>
> > +	local leverItem = Tile(position):getItemById(1946)
> +	if leverItem then
> +		leverItem:transform(1945)
> +	end
> +end
> +
> +function onUse(player, item, fromPosition, target, toPosition, isHotkey)
> +	if item.itemid ~= 1945 then
> +		return true
> +	end
> +	if item.uid == config[1].uid then
> +		local diamondItem = Tile(config[1].position):getItemById(2145)
> +		if player:getStorageValue(Storage.OutfitQuest.BrotherhoodOutfit) >= config[1].storageOutfit then
> +			if diamondItem and player:getStorageValue(641311) < 1 then
> +				diamondItem:remove(1)
> +				player:setStorageValue(641311, 1)
>
> troca 641311 pelo valor na tabela de storages, adiciona la caso necessario
> ------------------------------
>
> In data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua
> <https://github.com/opentibiabr/OTServBR-Global/pull/385#discussion_r313644664>
> :
>
> > +				config[1].position:sendMagicEffect(CONST_ME_TELEPORT)
> +				Game.createItem(config[1].itemId, 1, config[1].position)
> +				item:transform(1946)
> +				addEvent(revertLever, 4 * 1000, toPosition)
> +			elseif not diamondItem and player:getStorageValue(641311) < 1 then
> +				player:sendCancelMessage('You need to offer a small diamond.')
> +			else
> +				player:sendCancelMessage('You have already used this lever!')
> +			end
> +		else
> +			player:sendCancelMessage('You still don\'t have permission.')
> +		end
> +	elseif item.uid == config[2].uid then
> +		if player:getStorageValue(Storage.OutfitQuest.BrotherhoodOutfit) >= config[2].storageOutfit then
> +			local diamondItem = Tile(config[2].position):getItemById(2145)
> +			if diamondItem and player:getStorageValue(641312) < 1 then
>
> mesmo comentario da anterior
> ------------------------------
>
> In data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua
> <https://github.com/opentibiabr/OTServBR-Global/pull/385#discussion_r313644707>
> :
>
> > +				item:transform(1946)
> +				addEvent(revertLever, 4 * 1000, toPosition)
> +			elseif not diamondItem and player:getStorageValue(641311) < 1 then
> +				player:sendCancelMessage('You need to offer a small diamond.')
> +			else
> +				player:sendCancelMessage('You have already used this lever!')
> +			end
> +		else
> +			player:sendCancelMessage('You still don\'t have permission.')
> +		end
> +	elseif item.uid == config[2].uid then
> +		if player:getStorageValue(Storage.OutfitQuest.BrotherhoodOutfit) >= config[2].storageOutfit then
> +			local diamondItem = Tile(config[2].position):getItemById(2145)
> +			if diamondItem and player:getStorageValue(641312) < 1 then
> +				diamondItem:remove(1)
> +				player:setStorageValue(641312, 1)
>
> mesmo comentario da anterior
> ------------------------------
>
> In data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua
> <https://github.com/opentibiabr/OTServBR-Global/pull/385#discussion_r313644752>
> :
>
> > +				config[2].position:sendMagicEffect(CONST_ME_TELEPORT)
> +				Game.createItem(config[2].itemId, 1, config[2].position)
> +				item:transform(1946)
> +				addEvent(revertLever, 4 * 1000, toPosition)
> +			elseif not diamondItem and player:getStorageValue(641312) < 1 then
> +				player:sendCancelMessage('You need to offer a small diamond.')
> +			else
> +				player:sendCancelMessage('You have already used this lever!')
> +			end
> +		else
> +			player:sendCancelMessage('You still don\'t have permission.')
> +		end
> +	elseif item.uid == config[3].uid then
> +		if player:getStorageValue(Storage.OutfitQuest.BrotherhoodOutfit) >= config[3].storageOutfit then
> +			local diamondItem = Tile(config[3].position):getItemById(2145)
> +			if diamondItem and player:getStorageValue(641313) < 1 then
>
> mesmo comentario da anterior
> ------------------------------
>
> In data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua
> <https://github.com/opentibiabr/OTServBR-Global/pull/385#discussion_r313644776>
> :
>
> > +				item:transform(1946)
> +				addEvent(revertLever, 4 * 1000, toPosition)
> +			elseif not diamondItem and player:getStorageValue(641312) < 1 then
> +				player:sendCancelMessage('You need to offer a small diamond.')
> +			else
> +				player:sendCancelMessage('You have already used this lever!')
> +			end
> +		else
> +			player:sendCancelMessage('You still don\'t have permission.')
> +		end
> +	elseif item.uid == config[3].uid then
> +		if player:getStorageValue(Storage.OutfitQuest.BrotherhoodOutfit) >= config[3].storageOutfit then
> +			local diamondItem = Tile(config[3].position):getItemById(2145)
> +			if diamondItem and player:getStorageValue(641313) < 1 then
> +				diamondItem:remove(1)
> +				player:setStorageValue(641313, 1)
>
> mesmo comentario da anterior
> ------------------------------
>
> In data/actions/scripts/quests/dreamer challenge/lever_nightmare.lua
> <https://github.com/opentibiabr/OTServBR-Global/pull/385#discussion_r313644833>
> :
>
> > +
> +local function revertLever(position)
> +	local leverItem = Tile(position):getItemById(1946)
> +	if leverItem then
> +		leverItem:transform(1945)
> +	end
> +end
> +
> +function onUse(player, item, fromPosition, target, toPosition, isHotkey)
> +	if item.itemid ~= 1945 then
> +		return true
> +	end
> +	if item.uid == config[1].uid then
> +		local diamondItem = Tile(config[1].position):getItemById(2145)
> +		if player:getStorageValue(Storage.OutfitQuest.BrotherhoodOutfit) >= config[1].storageOutfit then
> +			if diamondItem and player:getStorageValue(641311) < 1 then
>
> mesmo comentario da anterior
> ------------------------------
>
> In data/actions/scripts/quests/dreamer challenge/lever_nightmare.lua
> <https://github.com/opentibiabr/OTServBR-Global/pull/385#discussion_r313644871>
> :
>
> > +	local leverItem = Tile(position):getItemById(1946)
> +	if leverItem then
> +		leverItem:transform(1945)
> +	end
> +end
> +
> +function onUse(player, item, fromPosition, target, toPosition, isHotkey)
> +	if item.itemid ~= 1945 then
> +		return true
> +	end
> +	if item.uid == config[1].uid then
> +		local diamondItem = Tile(config[1].position):getItemById(2145)
> +		if player:getStorageValue(Storage.OutfitQuest.BrotherhoodOutfit) >= config[1].storageOutfit then
> +			if diamondItem and player:getStorageValue(641311) < 1 then
> +				diamondItem:remove(1)
> +				player:setStorageValue(641311, 1)
>
> mesmo comentario da anterior
> ------------------------------
>
> In data/actions/scripts/quests/dreamer challenge/lever_nightmare.lua
> <https://github.com/opentibiabr/OTServBR-Global/pull/385#discussion_r313644911>
> :
>
> > +				config[1].position:sendMagicEffect(CONST_ME_TELEPORT)
> +		 [...]

2019-08-16 14:54 UTC, eduardodantas95 commented on data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua
> +			if diamondItem and player:getStorageValue(641312) < 1 then
> a quest ja tava assim kkk podem colocar se quiser. número alto assim eu nem faço mt questão de registrar no 051 Em ter, 13 de ago de 2019 19:52, Evil Puncker <notifications@github.com> escreveu:
> […](#)
> *@EPuncker* requested changes on this pull request. muda os storages pra tabela de storages igual as outras quests q fica belezinha ------------------------------ In data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua <[#385 (comment)](https://github.com/opentibiabr/OTServBR-Global/pull/385#discussion_r313644254)> : > + +local function revertLever(position) +	local leverItem = Tile(position):getItemById(1946) +	if leverItem then +	leverItem:transform(1945) +	end +end + +function onUse(player, item, fromPosition, target, toPosition, isHotkey) +	if item.itemid ~= 1945 then +	return true +	end +	if item.uid == config[1].uid then +	local diamondItem = Tile(config[1].position):getItemById(2145) +	if player:getStorageValue(Storage.OutfitQuest.BrotherhoodOutfit) >= config[1].storageOutfit then +	if diamondItem and player:getStorageValue(641311) < 1 then troca 641311 pelo valor na tabela de storages, igual foi feito na parte de cima ------------------------------ In data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua <[#385 (comment)](https://github.com/opentibiabr/OTServBR-Global/pull/385#discussion_r313644355)> : > +	local leverItem = Tile(position):getItemById(1946) +	if leverItem then +	leverItem:transform(1945) +	end +end + +function onUse(player, item, fromPosition, target, toPosition, isHotkey) +	if item.itemid ~= 1945 then +	return true +	end +	if item.uid == config[1].uid then +	local diamondItem = Tile(config[1].position):getItemById(2145) +	if player:getStorageValue(Storage.OutfitQuest.BrotherhoodOutfit) >= config[1].storageOutfit then +	if diamondItem and player:getStorageValue(641311) < 1 then +	diamondItem:remove(1) +	player:setStorageValue(641311, 1) troca 641311 pelo valor na tabela de storages, adiciona la caso necessario ------------------------------ In data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua <[#385 (comment)](https://github.com/opentibiabr/OTServBR-Global/pull/385#discussion_r313644664)> : > +	config[1].position:sendMagicEffect(CONST_ME_TELEPORT) +	Game.createItem(config[1].itemId, 1, config[1].position) +	item:transform(1946) +	addEvent(revertLever, 4 * 1000, toPosition) +	elseif not diamondItem and player:getStorageValue(641311) < 1 then +	player:sendCancelMessage('You need to offer a small diamond.') +	else +	player:sendCancelMessage('You have already used this lever!') +	end +	else +	player:sendCancelMessage('You still don\'t have permission.') +	end +	elseif item.uid == config[2].uid then +	if player:getStorageValue(Storage.OutfitQuest.BrotherhoodOutfit) >= config[2].storageOutfit then +	local diamondItem = Tile(config[2].position):getItemById(2145) +	if diamondItem and player:getStorageValue(641312) < 1 then mesmo comentario da anterior ------------------------------ In data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua <[#385 (comment)](https://github.com/opentibiabr/OTServBR-Global/pull/385#discussion_r313644707)> : > +	item:transform(1946) +	addEvent(revertLever, 4 * 1000, toPosition) +	elseif not diamondItem and player:getStorageValue(641311) < 1 then +	player:sendCancelMessage('You need to offer a small diamond.') +	else +	player:sendCancelMessage('You have already used this lever!') +	end +	else +	player:sendCancelMessage('You still don\'t have permission.') +	end +	elseif item.uid == config[2].uid then +	if player:getStorageValue(Storage.OutfitQuest.BrotherhoodOutfit) >= config[2].storageOutfit then +	local diamondItem = Tile(config[2].position):getItemById(2145) +	if diamondItem and player:getStorageValue(641312) < 1 then +	diamondItem:remove(1) +	player:setStorageValue(641312, 1) mesmo comentario da anterior ------------------------------ In data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua <[#385 (comment)](https://github.com/opentibiabr/OTServBR-Global/pull/385#discussion_r313644752)> : > +	config[2].position:sendMagicEffect(CONST_ME_TELEPORT) +	Game.createItem(config[2].itemId, 1, config[2].position) +	item:transform(1946) +	addEvent(revertLever, 4 * 1000, toPosition) +	elseif not diamondItem and player:getStorageValue(641312) < 1 then +	player:sendCancelMessage('You need to offer a small diamond.') +	else +	player:sendCancelMessage('You have already used this lever!') +	end +	else +	player:sendCancelMessage('You still don\'t have permission.') +	end +	elseif item.uid == config[3].uid then +	if player:getStorageValue(Storage.OutfitQuest.BrotherhoodOutfit) >= config[3].storageOutfit then +	local diamondItem = Tile(config[3].position):getItemById(2145) +	if diamondItem and player:getStorageValue(641313) < 1 then mesmo comentario da anterior ------------------------------ In data/actions/scripts/quests/dreamer challenge/lever_brotherhood.lua <[#385 (comment)](https://github.com/opentibiabr/OTServBR-Global/pull/385#discussion_r313644776)> : > +	item:transform(1946) +	addEvent(revertLever, 4 * 1000, toPosition) +	elseif not diamondItem and player:getStorageValue(641312) < 1 then +	player:sendCancelMessage('You need to offer a small diamond.') +	else +	player:sendCancelMessage('You have already used this lever!') +	end +	else +	player:sendCancelMessage('You still don\'t have permission.') +	end +	elseif item.uid == config[3].uid then +	if player:getStorageValue(Storage.OutfitQuest.BrotherhoodOutfit) >= config[3].storageOutfit then +	local diamondItem = Tile(config[3].position):getItemById(2145) +	if diamondItem and player:getStorageValue(641313) < 1 then +	diamondItem:remove(1) +	player:setStorageValue(641313, 1) mesmo comentario da anterior ------------------------------ In data/actions/scripts/quests/dreamer challenge/lever_nightmare.lua <[#385 (comment)](https://github.com/opentibiabr/OTServBR-Global/pull/385#discussion_r313644833)> : > + +local function revertLever(position) +	local leverItem = Tile(position):getItemById(1946) +	if leverItem then +	leverItem:transform(1945) +	end +end + +function onUse(player, item, fromPosition, target, toPosition, isHotkey) +	if item.itemid ~= 1945 then +	return true +	end +	if item.uid == config[1].uid then +	local diamondItem = Tile(config[1].position):getItemById(2145) +	if player:getStorageValue(Storage.OutfitQuest.BrotherhoodOutfit) >= config[1].storageOutfit then +	if diamondItem and player:getStorageValue(641311) < 1 then mesmo comentario da anterior ------------------------------ In data/actions/scripts/quests/dreamer challenge/lever_nightmare.lua <[#385 (comment)](https://github.com/opentibiabr/OTServBR-Global/pull/385#discussion_r313644871)> : > +	local leverItem = Tile(position):getItemById(1946) +	if leverItem then +	leverItem:transform(1945) +	end +end + +function onUse(player, item, fromPosition, target, toPosition, isHotkey) +	if item.itemid ~= 1945 then +	return true +	end +	if item.uid == config[1].uid then +	local diamondItem = Tile(config[1].position):getItemById(2145) +	if player:getStorageValue(Storage.OutfitQuest.BrotherhoodOutfit) >= config[1].storageOutfit then +	if diamondItem and player:getStorageValue(641311) < 1 then +	diamondItem:remove(1) +	player:setStorageValue(641311, 1) mesmo comentario da anterior ------------------------------ In data/actions/scripts/quests/dreamer challenge/lever_nightmare.lua <[#385 (comment)](https://github.com/opentibiabr/OTServBR-Global/pull/385#discussion_r313644911)> : > +	config[1].position:sendMagicEffect(CONST_ME_TELEPORT) +	Game.createItem(config[1].itemId, 1, config[1].position) +	item:transform(1946) +	addEvent(revertLever, 4 * 1000, toPosition) +	elseif not diamondItem and player:getStorageValue(641311) < 1 then +	player:sendCancelMessage('You need to offer a small diamond.') +	else +	player:sendCancelMessage('You have already used this lever!') +	end +	else +	player:sendCancelMessage('You still don\'t have permission.') + [...]

2019-08-16 14:55 UTC, eduardodantas95 commented
Resolvido? @worthdavi  e @EPuncker ?

2019-08-16 15:41 UTC, mattyx14 approved these changes

2019-08-21 00:15 UTC, merged

2020-02-01 06:44 UTC, ivansho92 commented
sorry, but my fire bug is not working in ashes, with AID: 2243, cus i don't see the script and actions.xml is not the id 2243, so could you help me?

2020-02-01 06:48 UTC, dudantas commented
Is merged. You need open an issue.

2020-02-01 06:51 UTC, ivansho92 commented
ohh okok thnks