Golden outfit pull
opentibiabr/otservbr-global-archived pull request #397
Opened 2019-08-12 10:34 UTC by pitis91

2019-08-12 10:38 UTC, pitis91 commented
to make it more good if someone knows how to create action in the memorial to appear the player who has bought it it will be appreciated XD

2019-08-12 11:57 UTC, pitis91 commented
storages.lua

lines added:
666		-- Golden Outfit
667		GoldenBaseOutfit = 50580,
668		GoldenFirstAddon = 50581,
669		GoldenSecondAddon = 50582,

2019-08-12 15:10 UTC, ghost requested changes

2019-08-12 15:10 UTC, EPuncker commented on data/npc/scripts/Emperor Kruzak.lua
> +			if(doPlayerRemoveMoney(cid, 250000000) and player:getStorageValue(Storage.OutfitQuest.GoldenBaseOutfit) == 1  and player:getStorageValue(Storage.OutfitQuest.GoldenSecondAddon) < 1) then
player:removeMoney(250000000)

same with others

2019-08-12 15:10 UTC, EPuncker commented on data/npc/scripts/King Tibianus.lua
> +focusModule:addGreetMessage('hail king')
those lines are already in the end of the file

2019-08-12 15:11 UTC, EPuncker commented
also can you please add the golden outfit display to each part of the addon? so the npc will it it along with the addon/outfit, check items ID 36336 to 36351

2019-08-12 19:14 UTC, pitis91 commented on data/npc/scripts/King Tibianus.lua
> +focusModule:addGreetMessage('hail king')
what i should do, delete them? i just spent 6hours to make work that but i'm not rlly a scripter XD just "copy-pasted" the nobleman irmana function and tryed till make the script work xD

2019-08-13 20:24 UTC, ghost reviewed
test this one https://pastebin.com/raw/j0qvWirX and adapt it to other 2 npc

2019-08-13 20:24 UTC, EPuncker commented on data/npc/scripts/Queen Eloise.lua
> --- Postman
don't delete this part

2019-08-13 20:24 UTC, EPuncker commented on data/npc/scripts/King Tibianus.lua
> +			end
move all this block to line 77

2019-08-15 15:20 UTC, Flyckks commented
Npcs doesnt work. Test it.

2019-08-19 10:40 UTC, closed without merging