Issavi Monsters
opentibiabr/otservbr-global-archived pull request #400
Opened 2019-08-12 15:25 UTC by Flyckks

2019-08-13 22:46 UTC, ghost requested changes

2019-08-13 22:46 UTC, EPuncker commented on data/monster/Anuma/Manticore.xml
>  	<defenses armor="84" defense="84"/>
falta tirar o / da tag

2019-08-13 22:46 UTC, EPuncker commented on data/monster/Anuma/Feral Sphinx.xml
>  	<defenses armor="84" defense="84"/>
tirar o / da tag

2019-08-17 14:06 UTC, gpedro commented on data/monster/Anuma/Manticore.xml
>  	<defenses armor="84" defense="84"/>
por que tirar o `/`? É self-closed.

2019-08-17 16:20 UTC, EPuncker commented on data/monster/Anuma/Manticore.xml
>  	<defenses armor="84" defense="84"/>
<defenses>
   <defense>
      <attribute>
      </attribute>
   </defense>
</defenses>

2019-08-17 23:30 UTC, ghost approved these changes

2019-08-18 00:36 UTC, merged