Bestiary Init Configuration
opentibiabr/otservbr-global-archived pull request #401
Opened 2019-08-12 15:57 UTC by Flyckks

2019-08-12 19:39 UTC, mattyx14 approved these changes
Nice

2019-08-12 19:40 UTC, mattyx14 commented
No tested ... Good look

2019-08-12 19:44 UTC, westwol requested changes

2019-08-12 19:44 UTC, westwol commented on data/lib/bestiary/bestiaryAssets.lua
> +
Double check is not needed.

2019-08-12 19:44 UTC, westwol commented on data/lib/bestiary/bestiaryAssets.lua
> +
Here you are not considering the kill that triggered the event.
This should do.
``if player:getBestiaryCount(bestiaryId) + 1 == bestiaryFirstUnlock then``

2019-08-12 19:44 UTC, westwol commented on data/lib/bestiary/bestiaryAssets.lua
> +
Here you are not considering the kill that triggered the event.
This should do.
`if player:getBestiaryCount(bestiaryId) + 1 == bestiarySecondUnlock then`

2019-08-12 19:44 UTC, westwol commented on data/lib/bestiary/bestiaryAssets.lua
> +
Here you are not considering the kill that triggered the event.
This should do.
`if player:getBestiaryCount(bestiaryId) + 1 == bestiarytoKill then  `

2019-08-13 10:41 UTC, eduardodantas95 commented
> No tested ... Good look

approved without test?

2019-08-13 15:25 UTC, mattyx14 commented
no no have time for test now ... on my check i see goods changes .. considere to westwol suggestions

2019-08-13 15:33 UTC, Znote commented on data/global.lua
> +	math.randomseed(os.mtime())
Don't seed with mtime and don't re-seed in every function call. https://github.com/otland/forgottenserver/pull/2637/files

2019-08-13 15:46 UTC, Znote commented on data/global.lua
> +end
Indentation in this `function doCreatureSetNoMove(cid,allow)` is a mess.

2019-08-13 15:48 UTC, Znote commented on data/global.lua
> +end
Indentation in this `function timeString(timeDiff, roundVal, roundUpVal)` is a mess. And half of it is 2 space indentation instead of 4?

2019-08-13 15:49 UTC, Znote commented on data/global.lua
> +end
indentation missing in function scope `function showTimeLeft(number, usewords)`, small 2 space indentation instead of 4

2019-08-14 11:36 UTC, gpedro commented on data/creaturescripts/scripts/bestiary/bestiaryKill.lua
> +    if target:getMaster() ~= nil then
this cannot merge with previous condition? 

why are you using `~= nil` instead `not target:getMaster`?

2019-08-14 11:37 UTC, gpedro commented on data/creaturescripts/scripts/others/login.lua
> +    if player:getStorageValue(4431) == 1 then -- bestiary Check
can you move this raw value to some variable or constants file?

2019-08-20 13:40 UTC, closed without merging