AIDs System
opentibiabr/otservbr-global-archived pull request #432
Opened 2019-08-18 18:32 UTC by Flyckks

Using AIDs System, you will be able to set ActionID, UniqueID, Special Description and Articles based on Position and itemId, instead of applying through map editor.

2019-08-18 19:26 UTC, EPuncker commented on data/globalevents/scripts/server/privateKeys.lua
> +    addEvent(_questLoader, 1 * 1000)
isso vai ser executado uma vez por segundo enquanto o server estiver online?

2019-08-18 19:28 UTC, EPuncker commented on data/lib/privateKeys.lua
> +    article = 01,
praq serve esse article?

2019-08-18 19:28 UTC, EPuncker commented on data/lib/privateKeys.lua
> +    desc = "imagine se eu fosse uma piroca",
esses "testes" não são necessários, vc pode por um exemplo comentado no cabeçalho do arquivo

2019-08-18 19:29 UTC, EPuncker commented on data/globalevents/scripts/server/privateKeys.lua
> +  print("> Loaded Advanced Actioner by Fernando Mieza el Tuero Fuerte")
conversa com os adm do projeto e pede pra por seu nome/nick no cabeçalho do ot, mas pfv não coloca um print em cada sistema que vc colocar no ot, já pensou se todo mundo fizesse isso

2019-08-18 19:42 UTC, Flyckks commented on data/globalevents/scripts/server/privateKeys.lua
> +  print("> Loaded Advanced Actioner by Fernando Mieza el Tuero Fuerte")
Eu jurava que havia removido isso, ja subi commitado :)

2019-08-18 19:43 UTC, Flyckks commented on data/globalevents/scripts/server/privateKeys.lua
> +    addEvent(_questLoader, 1 * 1000)
Ele vai executar,  1 segundo após abrir

2019-08-18 19:43 UTC, Flyckks commented on data/lib/privateKeys.lua
> +    article = 01,
vou subir no example

2019-08-18 23:46 UTC, gpedro commented on data/globalevents/scripts/server/privateKeys.lua
> +    local item = getThingfromPos(questInfo.position)
remove this line.

2019-08-18 23:54 UTC, gpedro commented on data/globalevents/scripts/server/privateKeys.lua
> +local function createPrivate(params)
this function is not used?

2019-08-19 00:02 UTC, Flyckks commented on data/globalevents/scripts/server/privateKeys.lua
> +    local item = getThingfromPos(questInfo.position)
It was used by another system, just forgot it out there, changing.

2019-08-19 00:12 UTC, gpedro commented on data/globalevents/scripts/server/privateKeys.lua
> +            item:setActionId(questInfo.aid)
Do this needs double-check? if this action id already set, he will set again. this is overhead?

2019-08-19 00:13 UTC, gpedro commented on data/globalevents/scripts/server/privateKeys.lua
> +            item:setAttribute(ITEM_ATTRIBUTE_UNIQUEID, questInfo.uid)
Missing a check for `questInfo.uid` and `questInfo.desc` availability, uhm?

2019-08-19 00:42 UTC, Flyckks commented on data/globalevents/scripts/server/privateKeys.lua
> +            item:setActionId(questInfo.aid)
but u did that o.o

2019-08-19 20:22 UTC, LukSrT requested changes

2019-08-19 20:22 UTC, LucasCPrazeres commented on data/lib/miscellaneous/miscellaneous.lua
> +dofile('data/lib/privateAids.lua')
data/lib/miscellaneous/privateAids.lua

2019-08-19 20:22 UTC, LucasCPrazeres commented on data/lib/miscellaneous/miscellaneous.lua
> +dofile('data/lib/privateKeys.lua')
data/lib/miscellaneous/privateKeys.lua

2019-08-20 13:40 UTC, closed without merging