chore revscript: conversion talkactions
opentibiabr/otservbr-global-archived pull request #435
Opened 2019-08-19 05:31 UTC by eduardodantas95

2019-08-19 14:14 UTC, ghost requested changes

2019-08-19 14:14 UTC, EPuncker commented on data/scripts/talkactions/god/attributes.lua
> -	["uniqueid"] = { isActive = true, targetFunction = function (item, target) return item:setAttribute(ITEM_ATTRIBUTE_UNIQUEID, target) end },
pq removeu essa parte

2019-08-19 14:14 UTC, EPuncker commented on data/scripts/talkactions/god/create summon.lua
> +local talk = TalkAction("/s")
não é /summon ?

2019-08-19 14:49 UTC, eduardodantas95 commented on data/scripts/talkactions/god/create summon.lua
> +local talk = TalkAction("/s")
não

2019-08-20 01:41 UTC, gpedro commented on data/scripts/talkactions/god/add skill.lua
> +talk = TalkAction("/addskill")
não precisa definir ela como `local`?

2019-08-21 03:45 UTC, gpedro commented on data/scripts/talkactions/god/add skill.lua
> +	if(not player:getGroup():getAccess()) or player:getAccountType() < ACCOUNT_TYPE_GOD then
this parenthesis is not necessary.

2019-08-21 03:45 UTC, gpedro commented on data/scripts/talkactions/god/add skill.lua
> +	if(param == "") then
this parenthesis is not necessary.

2019-08-21 03:46 UTC, gpedro commented on data/scripts/talkactions/god/animationeffect.lua
> +	if(not player:getGroup():getAccess()) or player:getAccountType() < ACCOUNT_TYPE_GOD then
this parenthesis is not necessary.

2019-08-21 03:46 UTC, gpedro commented on data/scripts/talkactions/god/animationeffect.lua
> +	if(param == "") then
this parenthesis is not necessary.

2019-08-21 03:46 UTC, gpedro commented on data/scripts/talkactions/god/attributes.lua
>  	if(param == "") then
this parenthesis is not necessary.

2019-08-21 03:46 UTC, gpedro commented on data/scripts/talkactions/god/attributes.lua
>  	if(not player:getGroup():getAccess()) or player:getAccountType() < ACCOUNT_TYPE_GOD then
this parenthesis is not necessary.

2019-08-21 03:47 UTC, gpedro commented on data/scripts/talkactions/god/attributes.lua
>  		if(not item or not item:isItem()) then
this parenthesis is not necessary.

2019-08-21 03:47 UTC, gpedro commented on data/scripts/talkactions/god/attributes.lua
>  		if(itemFunction.targetFunction(item, split[2])) then
this parenthesis is not necessary.

2019-08-21 03:52 UTC, gpedro commented
just check lua code style .... except this, lgtm

2019-08-22 22:36 UTC, merged