With this, all Analyzers should work
opentibiabr/otservbr-global-archived pull request #443
Opened 2019-08-20 13:59 UTC by Flyckks

2019-08-20 14:01 UTC, gpedro commented on data/items/items.xml
> +		<attribute key="type" value="supply" />
this looks duplicated, uhm?

2019-08-20 14:03 UTC, gpedro commented on src/protocolgame.cpp
> +		if (operatingSystem >= CLIENTOS_OTCLIENT_LINUX && operatingSystem == CLIENTOS_WINDOWS) {
this is necessary?

2019-08-20 14:04 UTC, gpedro commented on src/protocolgame.cpp
> +		case 0xFE: parseStoreRequestTransactionHistory(msg); break;
why this is function commented are removed?

2019-08-20 14:04 UTC, gpedro commented on src/protocolgame.cpp
> +	if (version >= 1200)
what's is?

2019-08-20 14:05 UTC, gpedro commented on src/luascript.cpp
> +			int parameters = lua_gettop(L) - 1; // - 1 because self is a parameter aswell, which we want to skip ofc
this is necessary?

2019-08-20 14:07 UTC, Flyckks commented on data/items/items.xml
> +		<attribute key="type" value="supply" />
fixed

2019-08-20 14:07 UTC, Flyckks commented on src/protocolgame.cpp
> +		if (operatingSystem >= CLIENTOS_OTCLIENT_LINUX && operatingSystem == CLIENTOS_WINDOWS) {
yep

2019-08-20 14:07 UTC, Flyckks commented on src/protocolgame.cpp
> +		case 0xFE: parseStoreRequestTransactionHistory(msg); break;
explained in pv, testing about store crash

2019-08-20 14:07 UTC, Flyckks commented on src/luascript.cpp
> +			int parameters = lua_gettop(L) - 1; // - 1 because self is a parameter aswell, which we want to skip ofc
yes

2019-08-20 14:11 UTC, gpedro commented on src/luascript.cpp
> + std::mutex mutexReload;
mutex is not necessary.
read this PR #405

2019-08-20 14:14 UTC, gpedro commented on data/items/items.xml
> +	<item id="20591" article="a" name="dead amarie">
duplicated item id! o.O

2019-08-20 14:15 UTC, gpedro commented on data/items/items.xml
> +		<attribute key="type" value="supply" />
duplicated supply attribute

2019-08-20 14:15 UTC, gpedro commented on data/items/items.xml
> +		<attribute key="type" value="supply" />
duplicated supply attribute

2019-08-20 14:15 UTC, gpedro commented on data/items/items.xml
> +		<attribute key="type" value="supply" />
duplicated supply attribute

2019-08-20 14:15 UTC, gpedro commented on data/items/items.xml
> +		<attribute key="type" value="supply" />
triplicated supply attribute

2019-08-20 14:49 UTC, gpedro commented
there's missing some function. check travis-ci log:
```
/home/travis/build/opentibiabr/OTServBR-Global/src/game.cpp:1256:102: error: no
409      member named 'getIsLootTrackeable' in 'Item'
410  ...&& toCylinder->getContainer()->getTopParent() == player && item->getIsLo...
411                                                                ~~~~  ^
4121 error generated.
```

2019-08-20 15:47 UTC, ghost requested changes

2019-08-20 15:47 UTC, EPuncker commented on data/items/items.xml
> +	<item id="14903" article="a" name="bag with stolen gold">
não mistura meu PR com esse :(

2019-08-20 15:47 UTC, EPuncker commented on data/items/items.xml
> +	<item id="20591" article="a" name="dead amarie">
não mistura meu PR com esse :(

2019-08-20 15:47 UTC, EPuncker commented on data/items/items.xml
> +		<attribute key="wrapableTo" value="26054" />
não mistura meu PR com esse :(

2019-08-20 15:47 UTC, EPuncker commented on src/luascript.cpp
> + std::mutex mutexReload;
ele pois coisas de outros PRs q estavam abertos nesse PR dele, inclusive do meu :(

2019-08-20 15:47 UTC, EPuncker commented on src/luascript.cpp
> +	registerEnum(ITEM_EXERCISE_START)
coisa de outro PR

2019-08-20 15:47 UTC, EPuncker commented on src/luascript.cpp
> +	// spell:cooldown(cooldown)
coisa de outro PR

2019-08-20 15:47 UTC, EPuncker commented on src/luascript.cpp
> +			int parameters = lua_gettop(L) - 1; // - 1 because self is a parameter aswell, which we want to skip ofc
cara isso aki n é revert do PR dos fix do tfs q o @Costallat fez?

2019-08-20 15:47 UTC, EPuncker commented on src/protocolgame.cpp
> +		if (operatingSystem >= CLIENTOS_OTCLIENT_LINUX && operatingSystem == CLIENTOS_WINDOWS) {
não cara isso não é necessário pq CLIENTOS_OTCLIENT_LINUX é valor 10 e windows é valor 11, logo o ">=" já vai checar o windows tbm

2019-08-20 15:47 UTC, EPuncker commented on src/protocolgame.cpp
> +		if (operatingSystem >= CLIENTOS_OTCLIENT_LINUX && operatingSystem == CLIENTOS_WINDOWS) {
https://github.com/opentibiabr/OTServBR-Global/blob/a5ce7262428c464132693d2b7d985dc4b742f833/src/enums.h#L148

2019-08-20 15:55 UTC, Flyckks commented on src/protocolgame.cpp
> +		if (operatingSystem >= CLIENTOS_OTCLIENT_LINUX && operatingSystem == CLIENTOS_WINDOWS) {
nao, isso foi um teste referente a tipografia identificada no cliente linux, ja foi revertido, so ver que ta outdated antes do teu comentario, mas valeu pela ajuda

2019-08-20 15:56 UTC, Flyckks commented on data/items/items.xml
> +	<item id="14903" article="a" name="bag with stolen gold">
acontece ¯\_(ツ)_/¯

2019-08-20 15:56 UTC, Flyckks commented on data/items/items.xml
> +		<attribute key="wrapableTo" value="26054" />
acontece ¯\_(ツ)_/¯

2019-08-20 15:57 UTC, ghost requested changes

2019-08-20 15:57 UTC, EPuncker commented on src/luascript.cpp
> +#include <mutex>
desfaz tudo que ta aki
https://github.com/opentibiabr/OTServBR-Global/pull/405/files

2019-08-20 15:57 UTC, EPuncker commented on src/luascript.cpp
> +	mutexReload.lock();
desfaz tudo que ta aki
https://github.com/opentibiabr/OTServBR-Global/pull/405/files

2019-08-20 15:57 UTC, EPuncker commented on src/luascript.cpp
> +		mutexReload.unlock();
desfaz tudo que ta aki
https://github.com/opentibiabr/OTServBR-Global/pull/405/files

2019-08-20 15:57 UTC, EPuncker commented on src/luascript.cpp
> +	mutexReload.unlock();
desfaz tudo que ta aki
https://github.com/opentibiabr/OTServBR-Global/pull/405/files

2019-08-20 15:57 UTC, EPuncker commented on src/luascript.cpp
> +	registerEnum(ITEM_EXERCISE_END)
coisa de outro PR

2019-08-20 15:57 UTC, EPuncker commented on src/luascript.cpp
> +	mutexReload.lock();
desfaz

2019-08-20 15:57 UTC, EPuncker commented on src/luascript.cpp
> +	mutexReload.unlock();
desfaz

2019-08-20 15:57 UTC, EPuncker commented on src/luascript.cpp
> +	// spell:cooldown(cooldown)
https://github.com/opentibiabr/OTServBR-Global/commit/a3fe753821ce836fd23e3a3b54e2e94d16031497#diff-52cc0839e1c346634d8dad954bb7b30e

2019-08-20 15:57 UTC, EPuncker commented on src/luascript.cpp
> -			lua_pushnumber(L, spell->getSecondaryCooldown());
refaz isso

https://github.com/opentibiabr/OTServBR-Global/commit/a3fe753821ce836fd23e3a3b54e2e94d16031497#diff-52cc0839e1c346634d8dad954bb7b30e

2019-08-20 15:57 UTC, EPuncker commented on src/luascript.cpp
> -			spell->setSecondaryCooldown(getNumber<uint32_t>(L, 3));
refaz

2019-08-20 15:57 UTC, EPuncker commented on src/luascript.cpp
> +			int parameters = lua_gettop(L) - 1; // - 1 because self is a parameter aswell, which we want to skip ofc
https://github.com/opentibiabr/OTServBR-Global/commit/a3fe753821ce836fd23e3a3b54e2e94d16031497#diff-52cc0839e1c346634d8dad954bb7b30eR15816

2019-08-20 16:03 UTC, EPuncker commented on src/luascript.cpp
> +int LuaScriptInterface::luaPlayerOwnsItem(lua_State* L)
@gpedro isso n seria a mesma coisa q player:getItemCount?

2019-08-20 20:40 UTC, westwol approved these changes

2019-08-21 03:53 UTC, gpedro commented on data/items/items.xml
> +	<item id="20591" article="a" name="dead unused purple elf">
este item está duplicado.

2019-08-21 03:54 UTC, gpedro commented on src/game.cpp
> +	const ItemType& it = Item::items[fromCylinder->getItem()->getID()];
missing some indent here

2019-08-21 03:54 UTC, gpedro commented on src/game.cpp
> + 		 	if (it.corpseType != RACE_NONE && toCylinder->getContainer()->getTopParent() == player && item->getIsLootTrackeable()) {
exceeded indent here xd

2019-08-21 03:54 UTC, gpedro commented on src/game.cpp
> +				player->updateLootTracker(item);
exceeded indent here xd

2019-08-21 04:00 UTC, gpedro commented on data/actions/scripts/others/consumables/food.lua
> +	if not player:ownsItem(item) then
isso pode ser alterado para `item:getTopParent() == player` ou algo similar. sendo assim, dispensando o uso de uma função que já existe.

2019-08-21 08:03 UTC, vankk commented on data/actions/scripts/others/consumables/food.lua
> +	if not player:ownsItem(item) then
Invés de fazer o código sendo escapado por condições anteriores porque não faz ele segmentado, não vejo necessidade de fazer algo fora desse exemplo abaixo que enviei - visto que o código pode ser modificado por algum usuário sem muito entendimento usando cliente na versão 10.x adicionar o código abaixo de `player:updateSupplyTracker(item)` e não entender o porque não está funcionando.
```lua
local playerClient = player:getClientVersion()
if playerClient.os == CLIENTOS_NEW_WINDOWS and playerClient.version >= 1140 then
	if item:getTopParent() == player then
		player:updateSupplyTracker(item)
	end
end
```

2019-08-21 13:33 UTC, closed without merging