Fixes on Monster Behaviour
opentibiabr/otservbr-global-archived pull request #444
Opened 2019-08-20 17:47 UTC by Flyckks

Fixed Monster Spell Delay and SetUp to forge Falcon Shield

2019-08-20 19:24 UTC, vankk reviewed
I think that the falconscript should be better structured and also low case the area effects.

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/insane siren.xml
>  		<attribute key="areaEffect" value="FIREAREA"/>
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/insane siren.xml
>  		</attack>
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/lumbering carnivor.xml
>  		<attribute key="areaEffect" value="SMOKE"/>
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/lumbering carnivor.xml
>  		<attribute key="areaEffect" value="EXPLOSIONAREA"/>
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/menacing carnivor.xml
>  			<attribute key="areaEffect" value="SMOKE" />
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/menacing carnivor.xml
>  			<attribute key="areaEffect" value="POISON" />
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/menacing carnivor.xml
> +		<attack name="physical" interval="2000" chance="15" radius="4" min="-150" max="-330">
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/ripper spectre.xml
>  			<attribute key="areaEffect" value="EXPLOSIONAREA"/>
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/ripper spectre.xml
>  			<attribute key="areaEffect" value="GROUNDSHAKER"/>
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/spiky carnivor.xml
>  		<attribute key="areaEffect" value="SMOKE" />
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/spiky carnivor.xml
>  		<attribute key="areaEffect" value="POISON" />
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/spiky carnivor.xml
>  		<attribute key="areaEffect" value="GROUNDSHAKER" />
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/thanatursus.xml
>  		<attribute key="areaEffect" value="HOLYAREA"/>
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/thanatursus.xml
>  		<attribute key="areaEffect" value="ENERGYAREA"/>
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/spells/scripts/monster/plagirath bog.lua
> +	addEvent(spellDamage, 10 * 1000, creature, target, var)
It is not safe pass the userdata to addEvent even if you check on the other side. You shouldn't **EVER** do that.

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/crazed winter vanguard.xml
>  		<attribute key="shootEffect" value="ICE"/>
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/crazed winter vanguard.xml
>  		<attribute key="areaEffect" value="GIANTICE"/>
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/crazed winter vanguard.xml
>  		<attribute key="areaEffect" value="ICEAREA"/>
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/crazed winter rearguard.xml
>  		<attribute key="shootEffect" value="ICE"/>
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/crazed summer vanguard.xml
>  		<attribute key="areaEffect" value="EXPLOSIONAREA" />
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/crazed summer vanguard.xml
>  		<attribute key="areaEffect" value="FIREAREA" />
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/crazed summer rearguard.xml
>  		<attribute key="areaEffect" value="EXPLOSIONAREA"/>
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/monster/Winter Update/crazed summer rearguard.xml
>  		<attribute key="areaEffect" value="FIREAREA"/>
Set the area effect as low case

2019-08-20 19:24 UTC, vankk commented on data/actions/scripts/falcons/falconShield.lua
> +local function sendFalconSucess(position)
Holy, my eyes. I don't know if it is how works on Tibia Global, but based on your script you can do like this.

You can make something like this: 
```lua 
function onUse(player, item, fromPosition, target, toPosition, isHotkey)
	if not target or type(target) ~= 'userdata' or not target:isItem() then
		return false
	end

	if player:getItemCount(32521) < 1 or player:getItemCount(32518) < 1 then
		return false
	end

	if target:getId() ~= 8671 or target:getPosition() ~= Position(33363, 31342, 7) then
		return false
	end

	player:removeItem(32521, 1)  
	player:removeItem(32518, 1)  
	player:addItem(32422, 1)  
	item:remove(1)
	return true
end
```

2019-08-20 19:35 UTC, EPuncker commented on data/monster/Winter Update/alptramun.xml
> +<monster name="Alptramun" nameDescription="a Alptramun" race="blood" experience="15" speed="250" script="rewardboss.lua">
ele ja ta com a flag de boss

2019-08-20 22:58 UTC, worthdavi commented on data/spells/scripts/monster/plagirath bog.lua
> +	addEvent(spellDamage, 10 * 1000, creature, target, var)
My way (this one that you tryied to improve) is safer than yours, lol. As vankk said, you should not ever pass userdata with an addEvent. If the addEvent does not find the object, the server will crash - even checking on other side.

2019-08-20 23:04 UTC, westwol commented on data/spells/scripts/monster/plagirath bog.lua
> +	addEvent(spellDamage, 10 * 1000, creature, target, var)
I also agree, it's not safe passing userdata directly. You can do something like this:
`addEvent(spellDamage, 10 * 1000, creature:getId(), target:getId(), var)`

spellDamage function:
https://pastebin.com/PPfqcCWY

2019-08-20 23:28 UTC, Flyckks commented on data/monster/Winter Update/insane siren.xml
>  		<attribute key="areaEffect" value="FIREAREA"/>
Like you saw, the area effect was already on uppercase, but, it would be a pleasure to change that. Next time, try to comment about a change made.

2019-08-20 23:28 UTC, Flyckks commented on data/monster/Winter Update/insane siren.xml
>  		</attack>
Like you saw, the area effect was already on uppercase, but, it would be a pleasure to change that. Next time, try to comment about a change made.

2019-08-20 23:28 UTC, Flyckks commented on data/monster/Winter Update/lumbering carnivor.xml
>  		<attribute key="areaEffect" value="SMOKE"/>
Like you saw, the area effect was already on uppercase, but, it would be a pleasure to change that. Next time, try to comment about a change made.

2019-08-20 23:29 UTC, Flyckks commented on data/monster/Winter Update/lumbering carnivor.xml
>  		<attribute key="areaEffect" value="EXPLOSIONAREA"/>
Like you saw, the area effect was already on uppercase, but, it would be a pleasure to change that. Next time, try to comment about a change made.

2019-08-20 23:29 UTC, Flyckks commented on data/monster/Winter Update/menacing carnivor.xml
>  			<attribute key="areaEffect" value="SMOKE" />
Like you saw, the area effect was already on uppercase, but, it would be a pleasure to change that. Next time, try to comment about a change made.

2019-08-20 23:29 UTC, Flyckks commented on data/monster/Winter Update/crazed summer vanguard.xml
>  		<attribute key="areaEffect" value="EXPLOSIONAREA" />
Like you saw, the area effect was already on uppercase, but, it would be a pleasure to change that. Next time, try to comment about a change made.

2019-08-20 23:29 UTC, Flyckks commented on data/monster/Winter Update/crazed summer vanguard.xml
>  		<attribute key="areaEffect" value="FIREAREA" />
Like you saw, the area effect was already on uppercase, but, it would be a pleasure to change that. Next time, try to comment about a change made.

2019-08-20 23:29 UTC, Flyckks commented on data/monster/Winter Update/crazed summer rearguard.xml
>  		<attribute key="areaEffect" value="EXPLOSIONAREA"/>
Like you saw, the area effect was already on uppercase, but, it would be a pleasure to change that. Next time, try to comment about a change made.

2019-08-20 23:29 UTC, Flyckks commented on data/monster/Winter Update/crazed summer rearguard.xml
>  		<attribute key="areaEffect" value="FIREAREA"/>
Like you saw, the area effect was already on uppercase, but, it would be a pleasure to change that. Next time, try to comment about a change made.

2019-08-20 23:30 UTC, Flyckks commented on data/monster/Winter Update/alptramun.xml
> +<monster name="Alptramun" nameDescription="a Alptramun" race="blood" experience="15" speed="250" script="rewardboss.lua">
Pelo visto foi outro script outdated que subiu junto.
Alias, esse montro nem balanceado está, agradeço a competencia para a critica, mas solicito uma melhor proatividade para o teste.

2019-08-20 23:31 UTC, Flyckks commented on data/actions/scripts/falcons/falconShield.lua
> +local function sendFalconSucess(position)
Sounds nice, I'm excited to see ur next contribuitions !

2019-08-20 23:46 UTC, vankk commented on data/monster/Winter Update/menacing carnivor.xml
>  			<attribute key="areaEffect" value="SMOKE" />
Yeah, I saw that is already on the file, but since you are making some changes on the file you can't update that?

2019-08-20 23:49 UTC, Flyckks commented on data/monster/Winter Update/menacing carnivor.xml
>  			<attribute key="areaEffect" value="SMOKE" />
atleast I updated the chances, due I had ppls testing it.
Then ,when I start compare to global monsters i check areas and effects.
The first thing was only fix the chances.

2019-08-21 00:03 UTC, LukSrT requested changes

2019-08-21 00:03 UTC, LucasCPrazeres commented on data/spells/scripts/monster/plagirath bog.lua
> +	addEvent(spellDamage, 10 * 1000, creature, target, var)
This change may cause server instability.

2019-08-21 08:14 UTC, vankk commented on data/monster/Winter Update/menacing carnivor.xml
>  			<attribute key="areaEffect" value="SMOKE" />
Yeah sure, but can't you just update the areaeffects to lowercase?

2019-08-21 23:52 UTC, poor-user commented on data/spells/scripts/monster/plagirath bog.lua
> +	addEvent(spellDamage, 10 * 1000, creature, target, var)
This conversation was marked as resolved by Flyckks

???
did you resolve that they all are wrong and u're right?
nice! best programmer
pay for him
mony mony monyyyyy
lets crash somebody's server! \o/
crashes ftw

cya

2019-08-30 01:58 UTC, dudantas requested changes
accidentally deleted?

2019-08-30 02:57 UTC, dudantas approved these changes

2019-08-30 03:03 UTC, merged