feat: bestiary
opentibiabr/otservbr-global-archived pull request #474
Opened 2019-08-26 06:07 UTC by gpedro

- [x] races list
  - [x]  monsters list
     - [x] monster basic infos (level 1)
     - [ ] monster intermediate infos (level 2) 
     - [ ] monster all infos (level 3)

2019-08-26 23:35 UTC, westwol commented on data/modules/scripts/bestiary/bestiary.lua
> +                local chance = loot.chance / 1000
A wrapper with the difficulty calculations would look better so we maintain network packet structure clean and easy to read.

2019-09-16 18:05 UTC, LukSrT commented on data/modules/scripts/bestiary/bestiary.lua
> +Bestiary.sendRaces = function(playerId, msg)
Bestiary.sendRaces = function(playerId)

2019-09-21 15:18 UTC, MasterMacavelli commented
@gpedro  Refactored monster table:

BESTIARY_DIFFICULT_HARMLESS_ORDINARY = 0    -- 1
BESTIARY_DIFFICULT_HARMLESS_VERYRARE = 1    -- 5
BESTIARY_DIFFICULT_TRIVIAL_ORDINARY = 2     -- 5
BESTIARY_DIFFICULT_TRIVIAL_VERYRARE = 3     -- 10
BESTIARY_DIFFICULT_EASY_ORDINARY = 4        -- 15
BESTIARY_DIFFICULT_EASY_VERYRARE = 5        -- 30
BESTIARY_DIFFICULT_MEDIUM_ORDINARY = 6      -- 25
BESTIARY_DIFFICULT_MEDIUM_VERYRARE = 7      -- 50
BESTIARY_DIFFICULT_HARD_ORDINARY = 8        -- 50
BESTIARY_DIFFICULT_HARD_VERYRARE = 9        -- 100

Bestiary.configTracker = {
    [BESTIARY_DIFFICULT_HARMLESS_ORDINARY] = {firstUnlock = 5, secondUnlock = 10, fullUnlock = 25, charms = 1},
    [BESTIARY_DIFFICULT_HARMLESS_VERYRARE] = {firstUnlock = 1, secondUnlock = 3, fullUnlock = 5, charms = 5},
    [BESTIARY_DIFFICULT_TRIVIAL_ORDINARY] = {firstUnlock = 10, secondUnlock = 100, fullUnlock = 250, charms = 5},
    [BESTIARY_DIFFICULT_TRIVIAL_VERYRARE] = {firstUnlock = 1, secondUnlock = 3, fullUnlock = 5, charms = 10},
    [BESTIARY_DIFFICULT_EASY_ORDINARY] = {firstUnlock = 25, secondUnlock = 250, fullUnlock = 500, charms = 15},
    [BESTIARY_DIFFICULT_EASY_VERYRARE] = {firstUnlock = 1, secondUnlock = 3, fullUnlock = 5, charms = 30},
    [BESTIARY_DIFFICULT_MEDIUM_ORDINARY] = {firstUnlock = 50, secondUnlock = 500, fullUnlock = 1000, charms = 25},
    [BESTIARY_DIFFICULT_MEDIUM_VERYRARE] = {firstUnlock = 1, secondUnlock = 3, fullUnlock = 5, charms = 50},
    [BESTIARY_DIFFICULT_HARD_ORDINARY] = {firstUnlock = 100, secondUnlock = 1000, fullUnlock = 2500, charms = 50},
    [BESTIARY_DIFFICULT_HARD_VERYRARE] = {firstUnlock = 1, secondUnlock = 3, fullUnlock = 5, charms = 100}
}

2019-09-21 16:41 UTC, MasterMacavelli requested changes

2019-09-21 16:41 UTC, MasterMacavelli commented on data/modules/scripts/bestiary/assets.lua
> +
BESTIARY_DIFFICULT_HARMLESS_ORDINARY = 0    -- 1
BESTIARY_DIFFICULT_HARMLESS_VERYRARE = 1    -- 5
BESTIARY_DIFFICULT_TRIVIAL_ORDINARY = 2     -- 5
BESTIARY_DIFFICULT_TRIVIAL_VERYRARE = 3     -- 10
BESTIARY_DIFFICULT_EASY_ORDINARY = 4        -- 15
BESTIARY_DIFFICULT_EASY_VERYRARE = 5        -- 30
BESTIARY_DIFFICULT_MEDIUM_ORDINARY = 6      -- 25
BESTIARY_DIFFICULT_MEDIUM_VERYRARE = 7      -- 50
BESTIARY_DIFFICULT_HARD_ORDINARY = 8        -- 50
BESTIARY_DIFFICULT_HARD_VERYRARE = 9        -- 100

Bestiary.configTracker = {
    [BESTIARY_DIFFICULT_HARMLESS_ORDINARY] = {firstUnlock = 5, secondUnlock = 10, fullUnlock = 25, charms = 1},
    [BESTIARY_DIFFICULT_HARMLESS_VERYRARE] = {firstUnlock = 1, secondUnlock = 3, fullUnlock = 5, charms = 5},
    [BESTIARY_DIFFICULT_TRIVIAL_ORDINARY] = {firstUnlock = 10, secondUnlock = 100, fullUnlock = 250, charms = 5},
    [BESTIARY_DIFFICULT_TRIVIAL_VERYRARE] = {firstUnlock = 1, secondUnlock = 3, fullUnlock = 5, charms = 10},
    [BESTIARY_DIFFICULT_EASY_ORDINARY] = {firstUnlock = 25, secondUnlock = 250, fullUnlock = 500, charms = 15},
    [BESTIARY_DIFFICULT_EASY_VERYRARE] = {firstUnlock = 1, secondUnlock = 3, fullUnlock = 5, charms = 30},
    [BESTIARY_DIFFICULT_MEDIUM_ORDINARY] = {firstUnlock = 50, secondUnlock = 500, fullUnlock = 1000, charms = 25},
    [BESTIARY_DIFFICULT_MEDIUM_VERYRARE] = {firstUnlock = 1, secondUnlock = 3, fullUnlock = 5, charms = 50},
    [BESTIARY_DIFFICULT_HARD_ORDINARY] = {firstUnlock = 100, secondUnlock = 1000, fullUnlock = 2500, charms = 50},
    [BESTIARY_DIFFICULT_HARD_VERYRARE] = {firstUnlock = 1, secondUnlock = 3, fullUnlock = 5, charms = 100}
}

2019-09-21 16:54 UTC, MasterMacavelli requested changes

2019-09-21 16:54 UTC, MasterMacavelli commented on data/modules/scripts/bestiary/assets.lua
> +Bestiary.Monsters = {
Bestiary.Monsters = {
    [BESTIARY_DIFFICULT_HARMLESS_ORDINARY] = {
        "Berrypest", "Butterfly (Blue)", "Butterfly (Purple)", "Butterfly (Red)", "Cat", "Dog", "Husky", "Modified Gnarlhound",
        "Mushroom Sniffer", "Northern Pike", "Pigeon"
    },
    [BESTIARY_DIFFICULT_HARMLESS_VERYRARE] = {
    },
    [BESTIARY_DIFFICULT_TRIVIAL_ORDINARY] = {
        "Badger", "Bat", "Black Sheep", "Bog Frog", "Bug", "Cave Parrot", "Cave Rat", "Chicken",
        "Deer", "Dromedary", "Fish", "Flamingo", "Fox", "Frost Troll", "Goblin", "Green Frog",
        "Grynch Clan Goblin", "Horse (Brown)", "Horse (Gray)", "Horse (Taupe)", "Island Troll", "Parrot", "Penguin", "Pig",
        "Poison Spider", "Rabbit", "Rat", "Sandcrawler", "Seagull", "Sheep", "Silver Rabbit", "Skunk", "Snake",
        "Spider", "Squirrel", "Troll", "Undead Jester", "Wasp", "White Deer", "Wild Horse", "Winter Wolf", "Wisp", "Wolf"
    },
    [BESTIARY_DIFFICULT_TRIVIAL_VERYRARE] = {        
    },
    [BESTIARY_DIFFICULT_EASY_ORDINARY] = {
        "Abyssal Calamary", "Acolyte of Darkness", "Adventurer", "Amazon", "Assassin", "Azure Frog", "Bandit", "Barbarian Brutetamer",
        "Barbarian Headsplitter", "Barbarian Skullhunter", "Bear", "Blood Crab", "Boar", "Bonelord", "Cake Golem", "Calamary",
        "Carrion Worm", "Centipede", "Chakoya Toolshaper", "Chakoya Tribewarden", "Chakoya Windcaller", "Cobra", "Coral Frog", "Corym Charlatan", "Crab",
        "Crazed Beggar", "Crimson Frog", "Crocodile", "Crypt Defiler", "Crypt Shambler", "Cyclops", "Damaged Crystal Golem", "Damaged Worker Golem",
        "Elemental", "Gargoyle", "Merlkin", "Minotaur", "Guard", "Mage", "Archer", "Nomad",
        "Dark Apprentice", "Dark Magician", "Dark Monk", "Deepling Worker", "Deepsea Blood Crab", "Doomsday Cultist", "Dwarf", "Dwarf Guard", "Dwarf Soldier",
        "Dworc Fleshhunter", "Dworc Venomsniper", "Dworc Voodoomaster", "Elephant", "Elf", "Elf Arcanist", "Elf Scout", "Emerald Damselfly",
        "Feverish Citizen", "Filth Toad", "Fire Devil", "Firestarter", "Frost Giant", "Frost Giantess", "Furious Troll", "Gang Member",
        "Gargoyle", "Gazer", "Ghost", "Ghost Wolf", "Ghoul", "Gladiator", "Gloom Wolf", "Gnarlhound", "Goblin Assassin",
        "Goblin Leader", "Goblin Scavenger", "Gozzler", "Grave Robber", "Honour Guard", "Hunter", "Hyaena", "Insect Swarm",
        "Insectoid Scout", "Iron Servant", "Jellyfish", "Killer Rabbit", "Kongra", "Ladybug", "Larva", "Leaf Golem",
        "Lion", "Little Corym Charlatan", "Lizard Sentinel", "Lizard Templar", "Mad Scientist", "Mammoth", "Marsh Stalker", "Mercury Blob", "Merlkin",
        "Minotaur", "Minotaur Archer", "Minotaur Guard", "Minotaur Mage", "Mole", "Monk", "Mummy", "Nomad (Basic)",
        "Nomad (Blue)", "Nomad (Female)", "Novice of the Cult", "Orc", "Orc Rider", "Orc Shaman", "Orc Spearman", "Orc Warrior",
        "Orchid Frog", "Panda", "Pirate Ghost", "Pirate Marauder", "Pirate Skeleton", "Poacher", "Polar Bear", "Quara Mantassin Scout", "Redeemed Soul",
        "Rorc", "Rotworm", "Salamander", "Scarab", "Scorpion", "Sibang", "Skeleton", "Skeleton Warrior",
        "Slime", "Slug", "Smuggler", "Spit Nettle", "Squidgy Slime", "Stalker", "Starving Wolf", "Stone Golem",
        "Swamp Troll", "Swampling", "Tainted Soul", "Tarantula", "Tarnished Spirit", "Terramite", "Terror Bird", "Thornback Tortoise", "Tiger",
        "Toad", "Tortoise", "Troll Champion", "Troll Guard", "Undead Mine Worker", "Undead Prospector", "Valkyrie", "War Wolf",
        "Water Buffalo", "White Shade", "Wild Warrior", "Witch"
    },
    [BESTIARY_DIFFICULT_EASY_VERYRARE] = {
        "Dire Penguin"
    },
    [BESTIARY_DIFFICULT_MEDIUM_ORDINARY] = {
        "Acid Blob", "Acolyte of the Cult", "Adept of the Cult", "Ancient Scarab", "Animated Snowman", "Arctic Faun", "Askarak Demon", "Askarak Lord",
        "Askarak Prince", "Baleful Bunny", "Bane Bringer", "Bane of Light", "Banshee", "Barbarian Bloodwalker", "Barkless Devotee", "Barkless Fanatic",
        "Behemoth", "Berserker Chicken", "Betrayed Wraith", "Blood Beast", "Blood Hand", "Blood Priest", "Blue Djinn", "Bog Raider", "Bonebeast",
        "Boogy", "Braindeath", "Bride of Night", "Brimstone Bug", "Broken Shaper", "Carniphila", "Clay Guardian", "Clomp",
        "Corym Skirmisher", "Corym Vanguard", "Crawler", "Crystal Spider", "Crystal Wolf", "Crystalcrusher", "Cult Believer", "Cult Enforcer",
        "Cult Scholar", "Cyclops Drone", "Cyclops Smith", "Dark Faun", "Death Blob", "Death Priest", "Deepling Brawler", "Deepling Elite", "Deepling Guard",
        "Deepling Master Librarian", "Deepling Scout", "Deepling Spellsinger", "Deepling Warrior", "Demon Parrot", "Demon Skeleton", "Destroyer", "Devourer",
        "Diabolic Imp", "Diamond Servant", "Diamond Servant Replica", "Doom Deer", "Dragon", "Dragon Hatchling", "Dragon Lord", "Dragon Lord Hatchling",
        "Dragonling", "Draken Warmaster", "Drillworm", "Dryad", "Duskbringer", "Dwarf Geomancer", "Dwarf Henchman", "Earth Elemental", "Efreet",
        "Elder Bonelord", "Elder Forest Fury", "Elder Mummy", "Elf Overseer", "Energy Elemental", "Enfeebled Silencer", "Enlightened of the Cult", "Enraged Crystal Golem",
        "Enslaved Dwarf", "Eternal Guardian", "Evil Sheep", "Evil Sheep Lord", "Execowtioner", "Faun", "Feversleep", "Fire Elemental",
        "Flying Book", "Forest Fury", "Frost Dragon", "Frost Dragon Hatchling", "Frost Flower Asura", "Furious Fire Elemental", "Ghoulish Hyaena", "Giant Spider", "Glooth Anemone",
        "Glooth Bandit", "Glooth Blob", "Glooth Brigand", "Glooth Golem", "Golden Servant", "Golden Servant Replica", "Goldhanded Cultist", "Goldhanded Cultist Bride",
        "Grave Guard", "Gravedigger", "Green Djinn", "Gryphon", "Haunted Treeling", "Hellspawn", "Herald of Gloom", "Hero",
        "Hibernal Moth", "High Voltage Elemental", "Hot Dog", "Hydra", "Ice Dragon", "Ice Golem", "Ice Witch", "Infernal Frog", "Insectoid Worker",
        "Instable Breach Brood", "Instable Sparkion", "Iron Servant Replica", "Killer Caiman", "Kollos", "Lacewing Moth", "Lancer Beetle", "Lich",
        "Lizard Chosen", "Lizard Dragon Priest", "Lizard High Guard", "Lizard Legionnaire", "Lizard Magistratus", "Lizard Snakecharmer", "Lizard Zaogun", "Lost Basher",
        "Lost Exile", "Lost Husher", "Lost Soul", "Lost Thrower", "Lumbering Carnivor", "Manta Ray", "Marid", "Massive Earth Elemental", "Massive Energy Elemental",
        "Massive Fire Elemental", "Massive Water Elemental", "Metal Gargoyle", "Midnight Asura", "Midnight Spawn", "Midnight Warrior", "Minotaur Cult Follower", "Minotaur Cult Prophet",
        "Minotaur Cult Zealot", "Minotaur Hunter", "Minotaur Invader", "Misguided Bully", "Misguided Thief", "Mooh'Tah Warrior", "Moohtant", "Mutated Bat",
        "Mutated Human", "Mutated Rat", "Mutated Tiger", "Necromancer", "Nightfiend", "Nightmare", "Nightmare Scion", "Nightslayer", "Nightstalker",
        "Noble Lion", "Nymph", "Ogre Brute", "Ogre Savage", "Ogre Shaman", "Omnivora", "Orc Berserker", "Orc Cult Fanatic",
        "Orc Cult Inquisitor", "Orc Cult Minion", "Orc Cult Priest", "Orc Cultist", "Orc Leader", "Orc Marauder", "Orc Warlord", "Orclops Doomhauler",
        "Orclops Ravager", "Percht", "Pirate Buccaneer", "Pirate Corsair", "Pirate Cutthroat", "Pixie", "Plaguesmith", "Pooka", "Priestess",
        "Putrid Mummy", "Quara Constrictor", "Quara Constrictor Scout", "Quara Hydromancer", "Quara Hydromancer Scout", "Quara Mantassin", "Quara Pincher", "Quara Pincher Scout",
        "Quara Predator", "Quara Predator Scout", "Raging Fire", "Ravenous Lava Lurker", "Renegade Knight", "Renegade Quara Constrictor", "Renegade Quara Hydromancer", "Renegade Quara Mantassin",
        "Renegade Quara Pincher", "Renegade Quara Predator", "Roaring Lion", "Rot Elemental", "Rustheap Golem", "Sacred Spider", "Sandstone Scorpion", "Schiach", "Sea Serpent",
        "Serpent Spawn", "Shaburak Demon", "Shaburak Lord", "Shaburak Prince", "Shadow Hound", "Shadow  [...]

2019-09-21 17:11 UTC, MasterMacavelli commented
In my tests, everything seems ok.
But monster are getting wrong loots.
So, it would be necessary to set loot trough name instead of RaceId, right?

2019-12-22 02:54 UTC, MajestyOTBR commented
WIP forever? When will you finish the bestiary?

2020-03-27 12:56 UTC, dudztroyer commented
Alguma atualização dos arquivos aqui? Assets etc? Baixei ele, aparece os mobs mas os loots estão errados e alguns bixos crasham o cliente (acredito ser por causa do loot).

2020-04-12 02:42 UTC, merged