Fix Server Crash
opentibiabr/otservbr-global-archived pull request #501
Opened 2019-08-30 19:37 UTC by rickorion

Fix crash when monster walk in any field.

2019-08-30 20:00 UTC, Costallat approved these changes

2019-08-30 21:20 UTC, westwol approved these changes

2019-08-30 21:22 UTC, westwol requested changes
I would check if attackerPlayer is not nullptr
if (attackerPlayer && attackerPlayer->getPlayer()) {

2019-08-31 01:23 UTC, MajestyOTBR commented
Thanks for the fix.

2019-08-31 01:23 UTC, merged