[WIP]: Move raid system to globalevents
opentibiabr/otservbr-global-archived pull request #508
Opened 2019-09-01 20:17 UTC by liontts

"This effectively nukes the raid system in favor of global events, which permit better management for raids. It's easier to define raids on interval, on exact times, force execution, force scheduling, add monsters on different delays and randomized amounts and positions... and also gets rid of a command.

I added a lib with helper functions to add monsters to a raid. The event is called onRaid and there is an example bundled pretty equivalent to the previous XML raid example."

Credits to @ranisalt, code taken from the tfs repository.

I didn't have time to generate the raids, I hope someone takes the trouble to do it.

2019-09-02 02:55 UTC, ranisalt commented
Thanks for the mention :)

2019-09-02 23:41 UTC, gpedro commented
can you remove tools folder and the cmake changes?

2019-09-03 00:25 UTC, liontts commented
@gpedro This has already been done, I just need help fixing the error while compiling

2019-09-03 00:49 UTC, gpedro commented
@ranisalt can you help us? xd

2019-09-03 02:10 UTC, ranisalt requested changes

2019-09-03 02:10 UTC, ranisalt commented on src/luascript.cpp
> +		lua_pushboolean(L, event->executeEvent());
Try
```cpp
GlobalEvent& event = eventMap.at(eventName);
lua_pushboolean(L, event.executeEvent());
```

2019-09-03 04:57 UTC, closed without merging