Updated npc Jorge
opentibiabr/otservbr-global-archived pull request #606
Opened 2019-09-24 00:46 UTC by oualid6496

- Removed unnecessary repetitive code
- Added Pigeon Trophy, Loremaster Doll, Dragon Goblet & Jade Amulet Replica's

Credits to Rick for fixing a { } mistake that I made

2019-09-26 00:20 UTC, Costallat commented
- Build: :thumbsup:
- Server: :thumbsup:
- Test: :exclamation: (can't buy Ahmet.xml new itens, stopped test here)

2019-09-26 06:05 UTC, oualid6496 commented
> * Build: 👍
> * Server: 👍
> * Test: ❗️ (can't buy Ahmet.xml new itens, stopped test here)

Probably because the items are not updated yet.

2019-09-26 11:02 UTC, oualid6496 commented
Added the items to items.xml that were previous added to the npc's shouldn't bug now.

2019-09-26 17:46 UTC, liontts requested changes
The item name half-digested stones is also incorrect, if it is still possible to correct this pull request.
The correct id is: 30604

2019-09-26 17:46 UTC, liontts commented on data/npc/Yasir.xml
>  			glowing rune, 32217, 350;
The correct id is: 33317

2019-09-26 20:53 UTC, oualid6496 commented on data/npc/Yasir.xml
>  			glowing rune, 32217, 350;
fixed both ids

2019-09-27 01:01 UTC, MajestyOTBR commented
Thanks for your contribution!

2019-09-27 01:02 UTC, merged