[TFS]: Removing old functions
opentibiabr/otservbr-global-archived pull request #661
Opened 2019-10-16 22:18 UTC by Costallat

Update Lua codebase to use new (meta-table) functions

Signed-off-by: Renato Foot Guimarães Costallat <costallat@hotmail.com>

2019-10-18 04:15 UTC, yatozin commented
this breaks the being able to use bank money to pay for syuf at npcs

2019-10-20 16:09 UTC, Costallat commented
Restored that option, please test again, tks!

2019-10-20 19:42 UTC, yatozin commented
now it says " you do not have enough capacity" cant buy still

2019-10-20 21:19 UTC, Costallat commented
Tks for testing!

You can try again now!

2019-10-21 03:55 UTC, yatozin commented
'16:53 Sorc [500]: balance
16:53 Naji: You certainly have made a pretty penny. Your account balance is 982000 gold.
16:53 Sorc [500]: trade
16:53 Bought 1x bonelord shield for 7000 gold.
16:53 Bought 1x bonelord shield for 7000 gold.
16:53 Bought 1x bonelord shield for 7000 gold.
16:53 Bought 1x bonelord shield for 7000 gold.
16:53 Bought 1x bonelord shield for 7000 gold.
16:53 Bought 1x bonelord shield for 7000 gold.
16:53 Mega Mart: Of course, just browse through my wares.
16:53 Sorc [500]: balance
16:53 Naji: You certainly have made a pretty penny. Your account balance is 982000 gold.`

no money is taken from bank

2019-10-22 07:58 UTC, yatozin commented
when you try buy exercise weapons in bags you get an empty brown bag now instead of shopping bag with the weapons

2019-10-22 12:45 UTC, Costallat commented
Client 10 support will be dropped

2019-10-22 22:00 UTC, yatozin commented
shopping bags come with no items. money is taken

2019-10-22 22:10 UTC, Costallat commented
Still working on that, preparing the environment for test here too

2019-10-22 23:39 UTC, Costallat commented
How did you test?

I tried with Nah'Bob and it worked, it just don't gave me any backpack, just the items, and the money was took from my account.

I think that other npc will have another flow.

Tks

2019-10-22 23:52 UTC, yatozin commented
> How did you test?
> 
> I tried with Nah'Bob and it worked, it just don't gave me any backpack, just the items, and the money was took from my account.
> 
> I think that other npc will have another flow.
> 
> Tks

Xodet in thais
https://imgur.com/mE1fNWO

2019-10-23 02:15 UTC, Costallat commented
Check now

2019-10-23 09:59 UTC, yatozin commented
> Check now

cant see anymore problem at the moment.

2019-10-23 14:41 UTC, miezaF requested changes

2019-10-23 14:41 UTC, miezaF commented on data/creaturescripts/scripts/others/login.lua
> +
Make an option on config.lua
configKeys.ENABLE_QUEST_ACCESS = true, (false to disable, like global)
also add a Storage value to libs to give access only one time, if player doest have access yet

local strSto = player:getStorageValue(Storage.singleAccess)
if configManager.getNumber(configKeys.ENABLE_QUEST_ACCESS) and strSto < 1 then

2019-10-23 14:41 UTC, miezaF commented on data/creaturescripts/scripts/others/login.lua
end

2019-10-23 14:41 UTC, miezaF commented on data/creaturescripts/scripts/others/login.lua
player:setStorageValue(Storage.singleAccess, 1)

2019-10-23 21:48 UTC, Costallat commented
@yatozin can you do a final test now on client 10 and 12?

I restored the client 10 support that I removed, to keep it working until we reach some point where things get more complicated to keep the support of both versions.

Tks

2019-10-23 22:36 UTC, yatozin commented
> @yatozin can you do a final test now on client 10 and 12?
> 
> I restored the client 10 support that I removed, to keep it working until we reach some point where things get more complicated to keep the support of both versions.
> 
> Tks

it all appears good

2019-10-25 21:19 UTC, MajestyOTBR commented
Thanks for the contribution.

2019-10-25 21:20 UTC, merged