Some fixes: Monsters, Mounts and Items.
opentibiabr/otservbr-global-archived pull request #701
Opened 2019-10-28 09:11 UTC by CoehManeh

I didn't have time to add items for the new monsters. Maybe I'll be done later. Enjoy. :blush:

2019-10-28 23:12 UTC, lBaah requested changes
Scorpion mount name is Scorpion King. Sandstone Scorpion is the name of the creature you should use the sceptre to tame the mount.

2019-10-28 23:12 UTC, lBaah commented on data/XML/mounts.xml
> +	<mount id="21" clientid="406" name="Sandstone Scorpion" speed="20" premium="yes" />
https://tibia.fandom.com/wiki/Scorpion_King

It's Scorpion King actually.

2019-10-28 23:15 UTC, lBaah commented
Possible conflict with #700

2019-10-28 23:32 UTC, MajestyOTBR commented
**This branch has conflicts that must be resolved**
Use the **web editor** or the **command line** to resolve conflicts. 

**Conflicting files**
data/actions/scripts/others/mounts/mounts.lua

2019-10-29 01:53 UTC, CoehManeh commented on data/XML/mounts.xml
> +	<mount id="21" clientid="406" name="Sandstone Scorpion" speed="20" premium="yes" />
The mount that tames is the Sandstone Scorpion
https://www.tibiawiki.com.br/wiki/Sandstone_Scorpion

2019-10-29 22:47 UTC, EnzzoCaaue commented on data/XML/mounts.xml
> +	<mount id="21" clientid="406" name="Sandstone Scorpion" speed="20" premium="yes" />
sanstone scorpion is the name of the creature but the mount name is scorpion king

2019-10-29 22:49 UTC, EnzzoCaaue commented on data/events/scripts/player.lua
> +CONTAINER_WEIGHT = 10000000 -- 100.000,00 oz | this function is only for containers, item below the weight determined here can be moved inside the container, for others items look game.cpp at the src
dunno why change it to 100k

2019-10-29 22:54 UTC, lBaah commented on data/events/scripts/player.lua
> +CONTAINER_WEIGHT = 10000000 -- 100.000,00 oz | this function is only for containers, item below the weight determined here can be moved inside the container, for others items look game.cpp at the src
A better thing would be the count of items inside containers because i can threw trash with 0.01oz and load thousand of stackable items, such gold coin in 1 per slot.

take a look at https://github.com/otland/forgottenserver/pull/2659

2019-10-31 02:26 UTC, MajestyOTBR commented on data/items/items.xml
> +	</item>
Can you put this item in order by id please?

2019-11-01 02:22 UTC, closed without merging