[WIP] Blessing Window Review
opentibiabr/otservbr-global-archived pull request #766
Opened 2019-11-16 23:15 UTC by FakeShinoda

Feel free to leave a code revision.

Features:
- [x] Description based on account status and promotion
- [x] PvP and PvE loss percents
- [ ] Equipment drop percent
- [ ] Blessing History

Remember: this is a work in progress review !
Credits in the file.

2019-11-17 03:29 UTC, Lycanzito commented
Tem alguma relação com o :
OTServBR-Global/issues/712 
?

2019-11-17 05:02 UTC, dudantas commented
@Lycanzito utilize o #712 para citar issues, por favor...

2019-11-17 07:11 UTC, Lycanzito commented
> @Lycanzito utilize o #712 para citar issues, por favor...

Não sabia como , agora sei <3 obg

2019-11-17 14:01 UTC, FakeShinoda commented
> 
> 
> Tem alguma relação com o :
> OTServBR-Global/issues/712
> ?

Esta janela é somente algo visual, os valores reais estão na source, somente fiz um calculo baseado nos valores que estão lá.

2019-11-17 18:08 UTC, Lycanzito commented
> > Tem alguma relação com o :
> > OTServBR-Global/issues/712
> > ?
> 
> Esta janela é somente algo visual, os valores reais estão na source, somente fiz um calculo baseado nos valores que estão lá.

a ok ! =)

2019-11-26 23:59 UTC, Raphaellb reviewed
a

2019-12-05 13:34 UTC, Raphaellb requested changes

2019-12-05 13:34 UTC, Raphaellb commented on data/modules/scripts/blessings/blessings.lua
> +		"Correct percents for loot drop"
use "percent" for both singular and plural

2019-12-22 02:44 UTC, MajestyOTBR commented
PR closed due to inactivity. If you want, you can reopen to finish.

2019-12-22 02:44 UTC, closed without merging