Update creature.lua
opentibiabr/otservbr-global-archived pull request #823
Opened 2020-01-24 18:03 UTC by EleanorRigby1

It is not my proposal to remove it, the system is good if it works, I don't know much about programming, so I didn't fix it. But that corrected the error.

With that code, when you have White Skull and let the monsters attack you, you give it to exit and re-enter as in 20 seconds you will be kicked with white skull.

2020-01-24 20:28 UTC, FakeShinoda commented on data/events/scripts/creature.lua
> -			    if target:isPzLocked() then end
if target:isPzLocked() then return true end
this should fix it

2020-01-24 21:18 UTC, mattyx14 commented on data/events/scripts/creature.lua
> -			    if target:isPzLocked() then end
no require remove all function only require add condition skull or battle

2020-01-24 22:06 UTC, lBaah requested changes
Please keep the function and change the line 83: `if target:isPzLocked() then end` to `if target:isPzLocked() then return true end`

2020-01-24 22:06 UTC, lBaah commented on data/events/scripts/creature.lua
> -			    if target:isPzLocked() then end
isPzLocked() checks if the player is in fight (pz block), no matter if skulled or not, so it might work

2020-01-24 22:19 UTC, EleanorRigby1 reviewed
ty

2020-01-25 13:36 UTC, lBaah approved these changes

2020-01-25 13:39 UTC, merged

2020-01-25 13:42 UTC, lBaah commented
Thank you for the changes you made.