Changes in the source and datapack.
opentibiabr/otservbr-global-archived pull request #958
Opened 2020-03-30 08:29 UTC by dudantas

Synchronizations with the TFS source / pack:

* Fixed:
- [x] Bug in droploot
- [x] Issue in the houses system #724
- [x] Bug at the blessings system

* Changes:
- [x] Experience stages moved to Lua (credits for @ranisalt)
- [x] Moved encryption to XTEA
- [x] House functions moved back to housetile.cpp
- [ ] Change the speed of all monsters in the XML script.

* Removed:
- [x] Exhaust for look
- [x] Exhaust for move
- [x] Exhaust for trade
- [x] Exhaust for change outfit
- [x] Exhaust for speak
- [x] Spdlog lib
- [x] Multiplication of 2.5 * for monsters speed in the source

* Added:
- [x] Bless talkaction
- [x] Sigbreak handler for windows
- [x] Revscriptys check register interface

* Added missing functions:
- [x] hasFlag (group)
- [x] getMana (player)
- [x] addMana (player)
- [x] getMaxMana (player)
- [x] hasCondition (creature)
- [x] getMonsterTypes (game)
- [x] addLoot (monsterType)
- [x] registerEvent (monsterType)

Some modifications were just to move functions to other locations, staying as in TFS and making it easier in case someone needs to make a diff between the source OTBR and TFS.

Credits to: 
The Forgotten Server
dudantas.

2020-03-30 08:48 UTC, Leo32onGIT commented on src/game.cpp
> -}
Are you removing stages.xml?
Users existing code that is referencing stages.xml, will either be stale or broken after this.

i.e. ACC Makers do this

2020-03-30 08:57 UTC, dudantas commented on src/game.cpp
> -}
Ok. Terá que ser feito outro script. Estou movendo os stages para lua, como você pode ver aqui: https://github.com/opentibiabr/otservbr-global/blob/ae3946a94d280c6f9bc0e34be9600463b5cf0ddd/data/events/scripts/player.lua#L24

Ok. Another script will have to be made for the sites, it is not something out of this world. I'm moving the stages to the moon, as you can see here: https://github.com/opentibiabr/otservbr-global/blob/ae3946a94d280c6f9bc0e34be9600463b5cf0ddd/data/events/scripts/player.lua#L24

I did the tests and it seemed ok, better refactored and easier to change.

2020-03-30 17:32 UTC, gpedro requested changes

2020-03-30 17:32 UTC, gpedro commented on data/creaturescripts/scripts/others/droploot.lua
> +	if player:hasFlag(PlayerFlag_NotGenerateLoot) or player:getVocation():getId() == VOCATION_NONE then
players without vocation cannot drop loot?

2020-03-30 17:32 UTC, gpedro commented on data/events/scripts/player.lua
> +	experienceStages = {
we cannot move this config to another file?

2020-03-30 17:32 UTC, gpedro commented on src/configmanager.cpp
> -	if (luaL_dofile(L, configFileLua.c_str())) {
i disagree with that. once we can use a custom config file using argument `-c xablau.lua`

https://github.com/opentibiabr/otservbr-global/blob/93e13351ee12661c84693f208723c9abcd44dff4/src/otserv.cpp#L139-L144

2020-03-30 17:32 UTC, gpedro commented on src/connection.cpp
> +			msg.skipBytes(1);    // Skip protocol ID
trailing spaces

2020-03-30 17:32 UTC, gpedro commented on src/connection.cpp
> +		protocol->onRecvMessage(msg);    // Send the packet to the current protocol
trailing spaces

2020-03-30 17:32 UTC, gpedro commented on src/const.h
> -	MESSAGE_STATUS_CONSOLE_BLUE = MESSAGE_EVENT_ADVANCE,
have you checked all references?

2020-03-30 17:32 UTC, gpedro commented on src/protocolold.cpp
> - * @file protocolold.cpp
protocolold is unused, maybe we can remove this protocol.

2020-03-30 17:32 UTC, gpedro commented on src/protocollogin.h
> - * @file protocollogin.h
protocollogin is unused too

2020-03-30 17:32 UTC, gpedro commented on src/game.cpp
> -	saveGameState();
we need to check if when press ctrl-c to finish the process, he still saving the server

2020-03-30 17:32 UTC, gpedro commented on data/lib/compat/compat.lua
> +function isContainer(uid) return Container(uid) end
and you double check this method? Methods with prefix `is` should returns boolean and `Creature(cid)` returns an obj

2020-03-30 18:01 UTC, dudantas commented on data/events/scripts/player.lua
> +	experienceStages = {
Yes we can.
I initially thought about moving to config.lua, but I ran into problems reading login.lua and installing the websites.
Any suggestion?

2020-03-30 18:08 UTC, dudantas commented on src/game.cpp
> -	saveGameState();
I'll check.

2020-03-30 18:08 UTC, dudantas commented on src/protocolold.cpp
> - * @file protocolold.cpp
Ok

2020-03-30 22:42 UTC, dudantas commented on src/const.h
> -	MESSAGE_STATUS_CONSOLE_BLUE = MESSAGE_EVENT_ADVANCE,
@gpedro yes, it's deprecated.

2020-03-30 22:46 UTC, dudantas commented on src/game.cpp
> -	saveGameState();
@gpedro checked, working.

2020-03-30 23:13 UTC, dudantas commented on src/configmanager.cpp
> -	if (luaL_dofile(L, configFileLua.c_str())) {
Reverted

2020-03-30 23:14 UTC, dudantas commented on src/protocollogin.h
> - * @file protocollogin.h
Removed

2020-03-30 23:14 UTC, dudantas commented on data/lib/compat/compat.lua
> +function isContainer(uid) return Container(uid) end
Reverted to original changes.

2020-03-30 23:15 UTC, dudantas commented on data/events/scripts/player.lua
> +	experienceStages = {
Moved to data/stages.lua and created /reload stages

2020-03-31 01:08 UTC, mattyx14 approved these changes
marge to  lasted changed are good very nice work

2020-03-31 01:12 UTC, dudantas commented
> marge to lasted changed are good very nice work

Thanks, we still need to correct the speed of the monsters, but soon it will be ready and I will go up so we can merge.

2020-03-31 02:19 UTC, gpedro approved these changes
LGTM;

2020-03-31 19:07 UTC, dudantas commented
Speed in the XML of the monsters fixed.

2020-04-01 03:50 UTC, merged

2020-04-01 23:24 UTC, worthdavi commented
Where is the credits for skillstages creator? :P @LukSrT

2020-04-02 19:13 UTC, slawkens commented
To be honest, I don't like that stages are saved in Lua instead of XML.

This will make it harder to parse it by AAC makers.

Why no keep the format of the original stages.xml in TFS as a standard?